import {OUTCOMES,outcome,outcomeLabel} from '../catalog/model.mjs';
import {renderDataUsed,outcomeGuide} from '../catalog/data-used.mjs';
import {accessShareUrl} from '../assets/share-state.mjs';
import {csvText,download} from '../lab/io.mjs';
import {distance,clock,seconds} from '../lab/gtfs.mjs';
import {ACCESS_VERSION,validateOptions} from './engine.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>Number.isFinite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:d}):'—';
const time=t=>Number.isFinite(t)?clock(t).slice(0,5):'—';
const safeLink=(url,label)=>/^https?:\/\//.test(url??'')?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:esc(label);
const categories={all:{name:'すべて',color:'#173b50'},shopping:{name:'買物',color:'#c37b15'},hospital:{name:'病院',color:'#b54b62'},school:{name:'学び',color:'#366bc8'},library:{name:'図書館・交流',color:'#7b5eb4'},civic:{name:'公共施設',color:'#087e80'}};
const statusNames={feasible:'入力条件内で成立',conditional:'往復候補あり・条件確認',not_met:'利用条件を満たさない',unknown:'収録条件で見つからない'};
const statusColors={feasible:'#087852',conditional:'#ba811d',not_met:'#b44c3e',unknown:'#7e8b98'};
let places=[],catalog=[],transport=null,map,placeLayer,stopLayer,homeLayer,voiceLayer,routeLayer,category='all',selected=null,home=null,pickMode=null,voicePoint=null,voices=[],conditions={},results=new Map(),sources=[],shown=20,tab='places',worker=null,jobId=0,busy=false,feedChoiceExplicit=false;
const inputIds=['date','departure','activity-from','activity-to','dwell','deadline','leg-minutes','transfers','max-walk','total-walk','walk-speed','walk-factor','budget','reservation','profile'];
const conditionIds={open:'facility-open',close:'facility-close',acceptance:'facility-acceptance',walking:'facility-walking',entry:'facility-entry',comfort:'facility-comfort',roundCost:'facility-cost',evidence:'facility-evidence',alternative:'facility-alternative'};
const group=p=>p.category==='clinic'?'hospital':p.category;
function effective(p){const c=conditions[p.id];return c?.position?{...p,...c.position,needsCoordinateConfirmation:false}:p;}
function error(e){if(busy)cancel();$('#error').textContent=e.message??String(e);$('#error').hidden=false;}
function guard(fn){return (...args)=>{try{Promise.resolve(fn(...args)).catch(error)}catch(e){error(e)}};}
function on(id,event,fn){$(id).addEventListener(event,guard(fn));}
function validPoint(p){return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&p.lat>=32.5&&p.lat<=34&&p.lon>=130.5&&p.lon<=132.3;}
function filtered(){const city=$('#city').value,q=$('#search').value.trim().toLowerCase();return places.filter(p=>(city==='all'||p.city===city)&&(category==='all'||group(p)===category)&&(!q||[p.name,p.address,p.city,categories[group(p)]?.name].join(' ').toLowerCase().includes(q)));}
function badge(r){const state=outcome(r);return r?`<span class="badge data-result ${state}"><b>${state.replaceAll('_',' ')}</b>${outcomeLabel(r)}</span>`:'';}
function updateDataUsed(){const done=[...results.values()];renderDataUsed('#access-data-used',{kind:'access',mode:done.length?'result':'selection',sources:done.length?sources:feedOptions(),facilityIds:done.length?done.map(r=>r.facilityId):selected?[selected]:[],date:done[0]?.date??$('#date').value,health:done[0]?.dataEvidence?.feeds,complete:!busy});}
function renderCategories(){const city=$('#city').value;$('#categories').innerHTML=Object.entries(categories).map(([id,c])=>{const n=places.filter(p=>(city==='all'||p.city===city)&&(id==='all'||group(p)===id)).length;return `<button class="category ${category===id?'active':''}" data-category="${id}" aria-pressed="${category===id}"><i style="--dot:${c.color}"></i>${c.name}<small>${n}</small></button>`;}).join('');}
function fitPlaces(){const rows=filtered();if(rows.length)map.fitBounds(L.latLngBounds(rows.map(p=>[effective(p).lat,effective(p).lon])),{padding:[25,25],maxZoom:14});}
function renderList(){const rows=filtered();$('#list-count').textContent=fmt(rows.length)+'件';$('#place-list').innerHTML=rows.slice(0,shown).map(p=>`<button class="place-card ${selected===p.id?'selected':''}" data-place="${esc(p.id)}"><span class="kind" style="--dot:${categories[group(p)]?.color}">${esc(categories[group(p)]?.name)} · ${esc(p.city)}</span><strong>${esc(p.name)}</strong><small>${esc(p.address)}</small>${badge(results.get(p.id))}${p.needsCoordinateConfirmation?'<small>公式地図の概略位置</small>':''}</button>`).join('')||'<p class="help">この条件で収録した施設はありません。地域・種類・検索語を変えてください。</p>';$('#more-places').hidden=shown>=rows.length;}
function renderMap(){
  placeLayer.clearLayers();voiceLayer.clearLayers();homeLayer.clearLayers();
  const rows=filtered();$('#map-count').textContent=fmt(rows.length)+'件の目的地';
  if($('#layer-places').checked)for(const raw of rows){const p=effective(raw),r=results.get(p.id),color=$('#layer-results').checked?(r?OUTCOMES[outcome(r)].color:'#bbc6ce'):categories[group(p)]?.color??'#657585';L.circleMarker([p.lat,p.lon],{radius:selected===p.id?10:7,color:selected===p.id?'#173b50':'white',weight:selected===p.id?2.5:1.2,fillColor:color,fillOpacity:p.needsCoordinateConfirmation ? .65 : .9}).addTo(placeLayer).on('click',()=>selectPlace(p.id,false)).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.city)} · ${esc(categories[group(p)]?.name)}${p.needsCoordinateConfirmation?'<br>公式地図の概略位置':''}<br>${r?outcomeLabel(r):'施設情報は一覧に表示'}<br><button class="button" data-check="${esc(p.id)}">ここへの往復を確認</button>`);}
  if(home)L.marker([home.lat,home.lon],{icon:L.divIcon({className:'',html:'<div style="background:#173b50;color:white;border:2px solid white;border-radius:8px;padding:5px 9px;white-space:nowrap;font:600 14px sans-serif">出発地</div>',iconSize:[65,31],iconAnchor:[32,31]})}).addTo(homeLayer);
  if($('#layer-voices').checked)for(const v of voices)L.circleMarker([v.lat,v.lon],{radius:9,color:'#173b50',fillColor:'#e8c84b',fillOpacity:.9,weight:2}).addTo(voiceLayer).bindPopup(`<b>${esc(v.name)}</b><br>${esc(v.purpose)} · ${esc(v.situation)}<br>${v.count===null?'人数未確認':fmt(v.count)+'人（聞き取りの集計）'}<br>${esc(v.note)}<br>${esc(v.source)}`);
  $('#map-legend').innerHTML=$('#layer-results').checked?Object.entries(OUTCOMES).map(([s,n])=>`<span><i style="--dot:${n.color}"></i>${s.replaceAll('_',' ')} · ${n.label}</span>`).join('')+'<span><i style="--dot:#bbc6ce"></i>未計算</span>':Object.entries(categories).filter(([k])=>k!=='all'&&(category==='all'||category===k)).map(([,c])=>`<span><i style="--dot:${c.color}"></i>${c.name}</span>`).join('');
  renderStops();
}
async function ensureTransport(){if(transport)return;const r=await fetch('data/map-data.json');if(!r.ok)throw Error('停留所データを読み込めませんでした');transport=await r.json();}
function renderStops(){stopLayer.clearLayers();if(!$('#layer-stops').checked||!transport)return;const b=map.getBounds();for(const s of transport.stops)if(b.contains([s.lat,s.lon]))L.circleMarker([s.lat,s.lon],{radius:3,color:'#506e83',weight:0,fillOpacity:.65}).addTo(stopLayer).bindPopup(`<b>${esc(s.name)}</b><br>${esc(transport.feeds[s.feedIndex].name)}<br>9/8の予定出発 ${s.departures[0]}回`);}
function hoursText(p){const h=p.openingHours;return typeof h==='string'?h:h?[h.days,h.start&&h.end?h.start+'〜'+h.end:'',h.notes].filter(Boolean).join(' / '):'未確認';}
function selectPlace(id,focus=true){selected=id;const raw=places.find(p=>p.id===id);if(!raw)return;const p=effective(raw);$('#selected-place').hidden=false;$('#selected-place').innerHTML=`<span class="kind" style="--dot:${categories[group(p)]?.color}">${esc(categories[group(p)]?.name)} · ${esc(p.city)}</span><h2>${esc(p.name)}</h2><p>${esc(p.address)}</p><dl class="meta-list"><div><dt>営業・受付</dt><dd>${esc(hoursText(p))}<small class="small-note">（出典の記載。当日の利用可否は別途確認）</small></dd></div><div><dt>設備情報</dt><dd>${esc((p.accessibilityReported??[]).join('・')||p.wheelchairAccess||'未確認')}<small class="small-note">施設までの経路の対応は未確認</small></dd></div><div><dt>位置</dt><dd>${conditions[id]?.position?'地図で指定した位置':p.needsCoordinateConfirmation?'公式地図の概略位置。入口の確認が必要':'公開データの施設位置。入口は未確認'}</dd></div><div><dt>資料時点</dt><dd>${esc(p.dataAsOf??'未確認')}</dd></div><div><dt>MDL取得日</dt><dd>${esc(p.retrievedAt??'未確認')}</dd></div><div><dt>公開ページ確認日</dt><dd>${esc(p.checkedAt??'未確認')}</dd></div><div><dt>原典の更新記録</dt><dd>${esc(p.sourceUpdatedAt??'未確認')}</dd></div></dl><p>${safeLink(p.url??p.sourceUrl,'施設・店舗の案内')} · ${safeLink(p.sourceUrl,'位置情報の出典')}</p>${badge(results.get(id))}<button class="button primary" data-check="${esc(id)}">ここへ行って、帰れるか確認</button>`;
  $('#target-label').textContent='目的地：'+p.name;loadConditions();updateDataUsed();renderList();renderMap();renderJourneyResult(results.get(id));if(focus)map.setView([p.lat,p.lon],Math.max(map.getZoom(),14));
}
function showTab(next,scroll=false){tab=next;for(const t of ['places','journey','voices'])$('#tab-'+t).hidden=t!==next;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===next);b.setAttribute('aria-pressed',String(b.dataset.tab===next))});if(scroll&&window.innerWidth<801)$('.sidebar').scrollIntoView({block:'start',behavior:'smooth'});}
function pick(mode){pickMode=mode;$('.map-work').classList.add('selecting');$('#map-tip').classList.add('picking');$('#map-tip').textContent=mode==='home'?'出発したい地区・場所を、地図上で1回押してください。':mode==='entrance'?'選んだ施設の入口を、地図上で1回押してください。':'聞き取った地区の代表地点を、地図上で1回押してください。';$('#map').scrollIntoView({block:'center',behavior:'smooth'});}
function finishPick(){$('.map-work').classList.remove('selecting');$('#map-tip').classList.remove('picking');$('#map-tip').textContent='目的地を押して情報を見るか、条件を指定して往復を確認してください。';pickMode=null;}
function invalidate(message='条件を変えました。計算ボタンで結果を更新してください。'){if(busy)cancel();results.clear();sources=[];$('#results-section').hidden=true;$('#journey-result').innerHTML='';routeLayer.clearLayers();$('#calculation-status').textContent=message;renderMap();renderList();updateDataUsed();}
function values(){return Object.fromEntries(inputIds.map(id=>[id,$('#'+id).value]));}
function options(){const number=id=>{const value=$('#'+id).value;if(value==='')throw Error('数値の空欄を確認してください');return Number(value)},o={departure:seconds($('#departure').value+':00'),deadline:seconds($('#deadline').value+':00'),activityFrom:seconds($('#activity-from').value+':00'),activityTo:seconds($('#activity-to').value+':00'),dwell:number('dwell'),legMinutes:number('leg-minutes'),maxWalk:number('max-walk'),totalWalk:number('total-walk'),walkSpeed:number('walk-speed'),walkFactor:number('walk-factor'),maxTransfers:number('transfers'),wheelchair:$('#profile').value==='wheelchair',reservation:$('#reservation').value,budget:$('#budget').value===''?null:number('budget')};validateOptions(o);if(o.budget!==null&&(!Number.isFinite(o.budget)||o.budget<0))throw Error('交通予算を確認してください');return o;}
function loadConditions(){const c=conditions[selected]??{};for(const [k,id]of Object.entries(conditionIds))$('#'+id).value=c[k]??(id.includes('acceptance')||id.includes('walking')||id.includes('entry')||id.includes('comfort')?'unknown':'');}
function saveConditions(){if(!selected)return;conditions[selected]={...conditions[selected],...Object.fromEntries(Object.entries(conditionIds).map(([k,id])=>[k,$('#'+id).value]))};}
function feedOptions(){return catalog.filter(f=>$$('#feed-options input:checked').some(x=>x.value===f.file));}
async function chooseNearby(){if(feedChoiceExplicit)return;await ensureTransport();const raw=places.find(p=>p.id===selected),points=[home,raw?effective(raw):null].filter(Boolean);if(!points.length)return;const chosen=new Set();for(const s of transport.stops)if(points.some(p=>distance(p,s)<=2000))chosen.add(transport.feeds[s.feedIndex].sha256);$$('#feed-options input').forEach(i=>{i.checked=chosen.has(catalog.find(f=>f.file===i.value)?.sha256)});}
function setBusy(value){busy=value;$('#calculate-one').disabled=value;$('#calculate-area').disabled=value;$('#cancel').hidden=!value;}
function cancel(){if(worker){worker.terminate();worker=null;}jobId++;setBusy(false);$('#calculation-status').textContent='計算を中止しました。条件を変えて再実行できます。';}
async function calculate(area=false){
  if(busy)return;$('#error').hidden=true;if(!home)throw Error('「地図を押して、出発地を決める」から出発地を指定してください');if(!selected&&!area)throw Error('地図から目的地を選んでください');saveConditions();const o=options();setBusy(true);await chooseNearby();const files=feedOptions();if(!files.length)throw Error('「使う時刻表を選ぶ」で事業者を選んでください');
  let targets=area?filtered().filter(p=>map.getBounds().contains([effective(p).lat,effective(p).lon])).sort((a,b)=>distance(home,effective(a))-distance(home,effective(b))).slice(0,20):[places.find(p=>p.id===selected)];if(!targets.length)throw Error('地図内に目的地がありません。表示範囲を広げてください');targets=targets.map(effective);
  if(!worker)worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});const id=++jobId;setBusy(true);updateDataUsed();$('#calculation-status').textContent='時刻表と施設の条件から往復を確認しています…';
  worker.onmessage=({data})=>{if(data.id!==jobId)return;if(data.progress){$('#calculation-status').textContent=data.progress;return;}setBusy(false);if(data.error){error(data.error);$('#calculation-status').textContent='計算を完了できませんでした。条件を確認してください。';return;}for(const r of data.results)results.set(r.facilityId,{...r,date:$('#date').value,sources:data.sources});sources=[...new Map([...results.values()].flatMap(r=>r.sources??[]).map(s=>[s.hash,s])).values()];updateDataUsed();$('#layer-results').checked=true;renderMap();renderList();renderResults();if(selected)renderJourneyResult(results.get(selected));$('#calculation-status').textContent=data.results.length+'施設の確認が完了しました。未確認の条件も結果に表示しています。';};
  worker.onerror=()=>{setBusy(false);error('計算を続けられませんでした。施設数・事業者を減らして再実行してください。');worker?.terminate();worker=null;};
  worker.postMessage({id,files,date:$('#date').value,home,facilities:targets,options:o,conditions});
}
function timeline(r){if(!r.outbound)return '';const legRows=(path)=>path.filter(l=>l.mode==='bus'||l.meters>5).map(l=>l.mode==='bus'?`<li><b>${time(l.departure)}〜${time(l.arrival)}　${esc(l.routeName)}</b>${esc(l.from.name)} → ${esc(l.to.name)}<br>乗る前の待ち ${fmt(l.wait/60,1)}分</li>`:`<li><b>${time(l.departure)}〜${time(l.arrival)}　徒歩概算 ${fmt(l.meters)}m</b>${esc(l.from.name??'地点')} → ${esc(l.to.name??'地点')}</li>`).join('');return `<ol class="timeline">${legRows(r.outbound.path)}<li><b>${time(r.begin)}〜${time(r.end)}　${esc(r.facilityName)}</b>用事・滞在 ${r.options.dwell}分${r.begin>r.outbound.arrival?` ／ 到着後の待ち ${fmt((r.begin-r.outbound.arrival)/60,1)}分`:''}</li>${legRows(r.inbound.path)}</ol>`;}
function renderJourneyResult(r){routeLayer.clearLayers();if(!r){$('#journey-result').innerHTML='';return;}
  $('#journey-result').innerHTML=`<div class="journey-card">${badge(r)}<h3>${esc(r.facilityName)}</h3>${r.outbound?`<p>帰宅できる時刻<br><span class="big">${time(r.homeAt)}</span></p><p>往復の徒歩 ${fmt(r.walk)}m（概算）<br>交通・施設での待ち ${fmt(r.waitMinutes,1)}分<br>交通費 ${r.cost===null?'未確認':fmt(r.cost)+'円（入力値）'}</p>`:''}${r.reasons.length?'<h3>確認された障害</h3><ul>'+r.reasons.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':''}${r.unknowns.length?'<h3>まだ確認が必要</h3><ul>'+r.unknowns.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':''}${r.searchIncomplete?'<p>探索の一部を省略しています。最良の経路であることは確認できていません。</p>':''}${r.outbound?'<details><summary>行き・用事・帰りの時刻を見る</summary>'+timeline(r)+'</details>':''}<p class="help">${r.outbound?'候補経路と入力条件の照合です。実際の利用には各項目の確認が必要です。':'鉄道・タクシー・送迎など、未収録の手段も確認してください。地域にアクセスがないとは断定できません。'}</p></div>`;
  if(r.outbound)for(const path of [r.outbound.path,r.inbound.path])for(const l of path)L.polyline([[l.from.lat,l.from.lon],[l.to.lat,l.to.lon]],{color:l.mode==='walk'?'#9b7541':'#173b50',weight:l.mode==='walk'?2:4,dashArray:l.mode==='walk'?'4 6':null,opacity:.65}).addTo(routeLayer).bindPopup(l.mode==='walk'?'徒歩の起終点を結ぶ概略線（道路経路ではありません）':'乗降する停留所を結ぶ概略線（実際の走行経路ではありません）');
}
function rowsForExport(){return [...results.values()].map(r=>({facility:r.facilityName,category:categories[group(r.facility)]?.name,city:r.facility.city,status:outcomeLabel(r),data_status:outcome(r),date:r.date??$('#date').value,home_departure:time(r.options.departure),activity_begin:time(r.begin),activity_end:time(r.end),home_return:time(r.homeAt),round_walk_m:r.walk??'',waiting_min:r.waitMinutes??'',round_fare_yen:r.cost??'',obstacles:r.reasons.join(' / '),unconfirmed:r.unknowns.join(' / '),data_source:r.facility.sourceUrl,source_license:r.facility.license??'個別の利用条件を確認',source_notes_url:'https://mobilitydlab.com/oita-mobility/usage.html#sources',transport_sources:(r.sources??[]).map(s=>s.name+' / '+s.hash).join(' | '),calculation_version:ACCESS_VERSION}));}
function renderResults(){const rows=rowsForExport();$('#results-section').hidden=!rows.length;$('#results-caption').textContent=$('#date').value+' ／ '+time(options().departure)+'出発 ／ '+rows.length+'施設。徒歩は概算、未収録の手段は未評価です。';$('#results-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>目的地</th><th>判定</th><th>用事の時間</th><th>帰宅</th><th>徒歩合計</th><th>未確認・障害</th></tr></thead><tbody>${[...results.values()].map(r=>`<tr><td><button class="text-button" data-check="${esc(r.facilityId)}">${esc(r.facilityName)}</button><small>${esc(r.facility.city)}</small></td><td>${badge(r)}</td><td>${time(r.begin)}〜${time(r.end)}</td><td>${time(r.homeAt)}</td><td>${fmt(r.walk)}m</td><td>${esc([...r.reasons,...r.unknowns].join(' / '))}</td></tr>`).join('')}</tbody></table></div>`;}
function renderVoices(){ $('#voice-list').innerHTML=voices.map(v=>`<div class="voice-card"><strong>${esc(v.name)}</strong><p>${esc(v.purpose)} · ${esc(v.situation)}<br>${v.count===null?'人数未確認':fmt(v.count)+'人（集計値）'}</p><p>${esc(v.note)}</p><button class="button" data-voice-home="${esc(v.id)}">この地区を出発地にする</button> <button class="button quiet" data-voice-delete="${esc(v.id)}">削除</button></div>`).join('');renderMap();}
function sourceHTML(){return `<h2>出典と収録範囲</h2><ul><li>病院147施設：${safeLink('https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryou/newpage_43373.html','厚生労働省 医療情報ネット（2026年6月1日時点）')}を抽出・加工。${safeLink('https://www.digital.go.jp/resources/open_data/public_data_license_v1.0','PDL1.0')}。</li><li>買物23施設：各店舗の公式案内から所在地と掲載情報を確認（2026年9月8日）。21施設は公式地図中心等の概略位置。各施設の出典を確認できます。</li><li>公共施設等29施設：玖珠町・日田市・別府市・日出町の公共施設データを抜粋・加工（CC BY 4.0）。更新時点は主に2024年。診療所はこの抜粋に含む一部だけです。</li><li>公共交通：大分県公開GTFSを加工（CC BY 4.0）。2026年9月8日取得。各事業者の公開データを選択して計算します。</li><li>背景：${safeLink('https://maps.gsi.go.jp/development/ichiran.html','国土地理院 地理院タイル')}。計算方法：${safeLink('https://gtfs.org/documentation/schedule/reference/','GTFS公式仕様')}。</li><li>${safeLink('https://mobilitydlab.com/oita-mobility/usage.html#sources','再利用時の出典・ライセンス・データの扱い')}を確認してください。</li></ul>`;}
function project(){return {schema:'oita-activity-access/1',engine:ACCESS_VERSION,created:new Date().toISOString(),home,voices,conditions,selected,filters:{category,city:$('#city').value,search:$('#search').value},inputs:values(),feeds:feedOptions().map(f=>f.file),sources,results:[...results.values()]};}
async function loadProject(file){const text=await file.text();if(text.length>8*1024*1024)throw Error('調査ファイルが大きすぎます');const p=JSON.parse(text);if(p.schema!=='oita-activity-access/1'||p.home&&!validPoint(p.home)||!Array.isArray(p.voices)||p.voices.length>1000||p.voices.some(v=>!validPoint(v)))throw Error('このマップで保存した調査ファイルを選んでください');
  if(p.conditions&&typeof p.conditions!=='object')throw Error('施設の条件を確認してください');for(const c of Object.values(p.conditions??{}))if(c.position&&!validPoint(c.position))throw Error('保存した施設位置を確認してください');
  cancel();home=p.home;voices=p.voices;conditions=p.conditions??{};selected=places.some(x=>x.id===p.selected)?p.selected:null;
  for(const id of inputIds)if(p.inputs?.[id]!==undefined)$('#'+id).value=String(p.inputs[id]);options();
  category=categories[p.filters?.category]?p.filters.category:'all';$('#city').value=p.filters?.city??'all';if(!$('#city').value)$('#city').value='all';$('#search').value=p.filters?.search??'';
  $$('#feed-options input').forEach(x=>x.checked=(p.feeds??[]).includes(x.value));feedChoiceExplicit=true;invalidate('調査を読み込みました。保存された判定は使わず、現在の条件で再計算してください。');$('#home-label').textContent=home?'出発地：'+(home.name??'保存した地点'):'出発地：未指定';renderCategories();renderVoices();renderList();if(selected)selectPlace(selected);else loadConditions();showTab('journey',true);fitPlaces();}
function reportMap(){const points=[...results.values()].map(r=>({...r.facility,status:outcome(r)}));if(!points.length)points.push(...filtered());if(home)points.push({...home,status:'home'});if(!points.length)return '';let minX=Math.min(...points.map(p=>p.lon)),maxX=Math.max(...points.map(p=>p.lon)),minY=Math.min(...points.map(p=>p.lat)),maxY=Math.max(...points.map(p=>p.lat));const cos=Math.cos((minY+maxY)/2*Math.PI/180),scale=Math.min(760/Math.max(.005,(maxX-minX)*cos),380/Math.max(.005,maxY-minY)),x=v=>40+(v-minX)*cos*scale,y=v=>420-(v-minY)*scale;return `<svg viewBox="0 0 850 460" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="目的地と出発地の位置図"><rect width="850" height="460" fill="#f0f5f7"/><text x="25" y="27" font-size="14" fill="#526978">北 ↑ ／ 緯度・経度による位置図。道路は描いていません。</text>${points.map(p=>`<circle cx="${x(p.lon)}" cy="${y(p.lat)}" r="${p.status==='home'?8:5}" fill="${p.status==='home'?'#173b50':OUTCOMES[p.status]?.color??categories[group(p)]?.color??'#758494'}"><title>${esc(p.name)}</title></circle>`).join('')}</svg>`;}
function exportReport(){const records=[...results.values()];const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>暮らしへのアクセス 調査</title><style>body{font:16px/1.8 sans-serif;color:#173b50;max-width:1080px;margin:30px auto;padding:0 20px}h1{font-size:28px}h2{font-size:21px;margin-top:30px}h3{font-size:17px}.badge{font-weight:bold}svg{width:100%;max-height:500px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{border:1px solid #d4e0e8;padding:10px;text-align:left;vertical-align:top}a{color:#215ec7}.timeline{padding-left:22px}.timeline li{margin:8px 0}.timeline b{display:block}.note{background:#edf4fa;padding:18px;border-radius:10px}small{display:block}.section{break-inside:avoid}@media print{body{max-width:none;margin:0}h2{break-after:avoid}}</style><h1>暮らしへのアクセス 調査</h1><p>保存日 ${esc(new Date().toISOString())} ／ 計算方法 ${ACCESS_VERSION}</p><div class="note">活動機会へのアクセシビリティ：出発地から、必要な時間に目的地へ行き、用事を済ませて帰れるか。施設の存在と、当日の利用成立は別に確認します。徒歩と経路線は概算。未確認条件はゼロや利用可能に置き換えていません。</div><h2>目的地と出発地</h2>${reportMap()}<p>出発地：${esc(home?.name??'未指定')}。調査日 ${esc($('#date').value)}。地図の色はサイトと同じ判定色、未計算は施設の種類の色です。</p><h2>計算条件</h2><table>${Object.entries(values()).map(([k,v])=>`<tr><th>${esc(document.querySelector('#'+k)?.closest('label')?.childNodes[0]?.textContent.trim()??k)}</th><td>${esc(v)}</td></tr>`).join('')}</table><h2>施設ごとの結果</h2>${records.length?records.map(r=>`<div class="section"><h3>${esc(r.facilityName)}：${outcomeLabel(r)}</h3><p>${esc(r.facility.address)} ／ ${safeLink(r.facility.sourceUrl,'施設位置の出典')}</p><p>障害：${esc(r.reasons.join(' / ')||'入力範囲では未検出')}<br>未確認：${esc(r.unknowns.join(' / ')||'入力範囲ではなし')}<br>探索の省略：${r.searchIncomplete?'あり':'なし'}</p>${r.outbound?`<p>用事 ${time(r.begin)}〜${time(r.end)} ／ 帰宅 ${time(r.homeAt)} ／ 徒歩概算 ${fmt(r.walk)}m ／ 交通費 ${r.cost===null?'未確認':fmt(r.cost)+'円（入力値）'}</p>${timeline(r)}`:''}<p>使用時刻表：${esc((r.sources??[]).map(s=>s.name).join(' / '))}<br>条件の確認元：${esc(r.conditions.evidence||'未記入')}<br>代替手段・依存：${esc(r.conditions.alternative||'未確認')}</p></div>`).join(''):'<p>未計算。地図に表示中の施設を位置図に掲載しています。</p>'}<h2>地区の声</h2>${voices.length?voices.map(v=>`<p><b>${esc(v.name)}</b> ／ ${esc(v.purpose)} ／ ${esc(v.situation)} ／ ${v.count===null?'人数未確認':fmt(v.count)+'人'}<br>${esc(v.note)}<br>出典 ${esc(v.source)} ／ ${esc(v.date)}</p>`).join(''):'<p>未入力。移動困難な人口を推計したものではありません。</p>'}<h2>使用した時刻表</h2>${sources.map(s=>`<p>${safeLink(s.source,s.name)}<small>SHA-256 ${esc(s.hash)}</small></p>`).join('')||'<p>未計算</p>'}${sourceHTML()}<h2>次に確認すること</h2><p>未確認の受付・費用・歩行経路・本人の許容を、施設・事業者・本人と確認してください。実地での移動や用事の成立は未検証です。交通の変更、施設側の時間調整、別の目的地・送迎・配達等も個別に比較できます。</p></html>`;download('oita-activity-access-report.html',html,'text/html;charset=utf-8');}
async function start(){
  if(!window.L)throw Error('地図を読み込めませんでした');map=L.map('map',{preferCanvas:true,scrollWheelZoom:false}).setView([33.28,131.45],9);const tiles=L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',{maxZoom:18,attribution:'背景：<a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noopener">地理院タイル</a>｜施設：厚生労働省・各自治体・各店舗公式'}).addTo(map);tiles.on('tileerror',()=>{$('#map-tip').textContent='背景地図を取得できない場合も、施設の位置と一覧は確認できます。';});
  stopLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);placeLayer=L.layerGroup().addTo(map);voiceLayer=L.layerGroup().addTo(map);homeLayer=L.layerGroup().addTo(map);
  const [pr,cr]=await Promise.all([fetch('access/destinations.json'),fetch('data/gtfs/catalog.json')]);if(!pr.ok||!cr.ok)throw Error('施設・時刻表一覧を読み込めませんでした');places=await pr.json();catalog=await cr.json();
  $('#city').innerHTML='<option value="all">大分県全体</option>'+[...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'ja')).map(c=>`<option>${esc(c)}</option>`).join('');
  $('#feed-options').innerHTML=catalog.map(f=>`<label><input type="checkbox" value="${esc(f.file)}">${esc(f.name)}</label>`).join('');$('#source-list').innerHTML=sourceHTML();const query=new URLSearchParams(location.search);category=categories[query.get('category')]?query.get('category'):'all';$('#city').value=query.get('city')??'all';if(!$('#city').value)$('#city').value='all';$('#search').value=query.get('q')??'';
  renderCategories();renderList();renderMap();fitPlaces();
  on('#city','change',()=>{shown=20;renderCategories();renderList();renderMap();fitPlaces()});on('#search','input',()=>{shown=20;renderList();renderMap()});on('#fit','click',fitPlaces);on('#more-places','click',()=>{shown+=20;renderList()});
  on('#categories','click',e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;shown=20;renderCategories();renderList();renderMap();fitPlaces()}});
  document.addEventListener('click',guard(async e=>{const place=e.target.closest('[data-place]'),check=e.target.closest('[data-check]'),side=e.target.closest('[data-tab]'),vh=e.target.closest('[data-voice-home]'),vd=e.target.closest('[data-voice-delete]');if(place){selectPlace(place.dataset.place);showTab('places');}if(check){selectPlace(check.dataset.check);showTab('journey',true);await chooseNearby();}if(side)showTab(side.dataset.tab);if(vh){const v=voices.find(v=>v.id===vh.dataset.voiceHome);home={name:v.name,lat:v.lat,lon:v.lon};$('#home-label').textContent='出発地：'+v.name;invalidate();showTab('journey',true);await chooseNearby();}if(vd){voices=voices.filter(v=>v.id!==vd.dataset.voiceDelete);renderVoices();}}));
  on('#pick-home','click',()=>pick('home'));on('#pick-voice','click',()=>pick('voice'));on('#adjust-entrance','click',()=>{if(!selected)throw Error('施設を先に選んでください');pick('entrance')});
  map.on('click',guard(async e=>{if(!pickMode)return;const p={lat:e.latlng.lat,lon:e.latlng.lng};if(!validPoint(p))throw Error('大分県の周辺で地点を選んでください');if(pickMode==='home'){home={...p,name:'地図で指定した出発地'};$('#home-label').textContent='出発地：地図で指定（'+p.lat.toFixed(4)+', '+p.lon.toFixed(4)+'）';invalidate();await chooseNearby();}else if(pickMode==='entrance'){saveConditions();conditions[selected]={...conditions[selected],position:p,positionConfirmed:true};invalidate();selectPlace(selected,false);}else{voicePoint=p;$('#voice-position').textContent='地区の位置：地図で指定済み';}finishPick();renderMap();showTab(tab,true);}));
  map.on('moveend',renderStops);for(const id of ['layer-places','layer-results','layer-voices'])on('#'+id,'change',renderMap);on('#layer-stops','change',async()=>{if($('#layer-stops').checked)await ensureTransport();renderStops()});
  for(const id of inputIds)on('#'+id,'change',()=>{if(id==='profile'){const slow=$('#profile').value==='slow';$('#walk-speed').value=slow?'2.5':'4';$('#max-walk').value=slow?'250':'500';$('#total-walk').value=slow?'1000':'2000';}invalidate()});
  for(const id of Object.values(conditionIds))on('#'+id,'change',()=>{saveConditions();invalidate()});on('#feed-options','change',()=>{feedChoiceExplicit=true;invalidate()});
  on('#calculate-one','click',()=>calculate(false));on('#calculate-area','click',()=>calculate(true));on('#cancel','click',cancel);
  on('#voice-form','submit',e=>{e.preventDefault();if(!voicePoint)throw Error('地区の代表点を地図で選んでください');const count=$('#voice-count').value===''?null:Number($('#voice-count').value);if(count!==null&&(!Number.isInteger(count)||count<0))throw Error('人数を確認してください');voices.push({...voicePoint,id:'voice-'+Date.now(),name:$('#voice-name').value.trim().slice(0,100),purpose:$('#voice-purpose').value,situation:$('#voice-situation').value,count,date:$('#voice-date').value,source:$('#voice-source').value.slice(0,500),note:$('#voice-note').value.slice(0,2000)});renderVoices();$('#voice-note').value='';});
  on('#about-open','click',()=>{$('#about').open=true;$('#about').scrollIntoView({block:'start',behavior:'smooth'})});
  on('#share-url','click',async()=>{const url=new URL(accessShareUrl(location.href,{category,city:$('#city').value}));try{await navigator.clipboard.writeText(url.href);$('#map-tip').textContent='目的地の種類・地域を含むURLをコピーしました。検索語・出発地・記録は含みません。';}catch{window.prompt('このURLをコピーして共有できます。検索語・出発地・記録は含みません。',url.href)}});
  on('#save-project','click',()=>{saveConditions();download('oita-activity-access-project.json',JSON.stringify(project()),'application/json')});on('#load-project','change',e=>e.target.files[0]?loadProject(e.target.files[0]):null);on('#export-csv','click',()=>download('oita-activity-access-results.csv','\uFEFF'+csvText(rowsForExport(),{safe:true}),'text/csv;charset=utf-8'));on('#export-report','click',()=>{saveConditions();exportReport()});
  updateDataUsed();$('#outcome-guide').innerHTML=outcomeGuide();document.documentElement.dataset.atlasReady='true';document.dispatchEvent(new Event('atlas:ready'));
}
guard(start)();
