import { cookies,headers } from 'next/headers';
import { scrypt,randomBytes,createHash,timingSafeEqual } from 'node:crypto';
export const SHARED_COOKIE='__Host-omc_shared';
export const SESSION_SECONDS=6*60*60;
const IDLE_SECONDS=2*60*60;
let hashesInFlight=0;
export type AccessConfig={password_hash:string;salt:string;version:number;enabled:number;role:string;updated_at:string};
export function digest(value:string){return createHash('sha256').update(value).digest('hex')}
export function randomToken(){return randomBytes(32).toString('base64url')}
export function randomSalt(){return randomBytes(16).toString('hex')}
export async function passwordHash(password:string,salt:string):Promise<Buffer>{if(hashesInFlight>=2)throw new Error('HASH_BUSY');hashesInFlight++;try{return await new Promise((resolve,reject)=>scrypt(password,Buffer.from(salt,'hex'),32,{N:32768,r:8,p:3,maxmem:64*1024*1024},(error,key)=>error?reject(error):resolve(key)))}finally{hashesInFlight--}}
export async function verifyPassword(password:string,config:AccessConfig){const candidate=await passwordHash(password,config.salt);const expected=Buffer.from(config.password_hash,'hex');return expected.length===candidate.length&&timingSafeEqual(expected,candidate)}
export async function getAccessConfig(db:D1Database){return db.prepare('SELECT password_hash,salt,version,enabled,role,updated_at FROM shared_access WHERE id=1').first<AccessConfig>()}
export async function readSharedSession(db:D1Database){const jar=await cookies();const token=jar.get(SHARED_COOKIE)?.value;if(!token||!/^[A-Za-z0-9_-]{43}$/.test(token))return null;const now=Math.floor(Date.now()/1000);const hash=digest(token);const row=await db.prepare('SELECT s.csrf,s.expires_at,s.idle_until,s.last_seen,c.role FROM shared_sessions s JOIN shared_access c ON c.id=1 AND c.version=s.version AND c.enabled=1 WHERE s.token_hash=? AND s.expires_at>? AND s.idle_until>?').bind(hash,now,now).first<{csrf:string;expires_at:number;idle_until:number;last_seen:number;role:string}>();if(!row)return null;if(row.last_seen<now-300)await db.prepare('UPDATE shared_sessions SET last_seen=?,idle_until=? WHERE token_hash=?').bind(now,Math.min(row.expires_at,now+IDLE_SECONDS),hash).run();return {...row,tokenHash:hash}}
export function sessionCookie(token:string,maxAge=SESSION_SECONDS){return `${SHARED_COOKIE}=${token}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`}
export async function issueSession(db:D1Database,version:number){const token=randomToken(),csrf=randomToken(),now=Math.floor(Date.now()/1000);await db.prepare('INSERT INTO shared_sessions (token_hash,csrf,version,expires_at,idle_until,last_seen) VALUES (?,?,?,?,?,?)').bind(digest(token),csrf,version,now+SESSION_SECONDS,now+IDLE_SECONDS,now).run();return {cookie:sessionCookie(token),csrf}}
export async function consumeLoginBudget(db:D1Database,salt:string){const now=Math.floor(Date.now()/1000),window=Math.floor(now/900),minute=Math.floor(now/60);await db.batch([db.prepare('DELETE FROM login_attempts WHERE bucket IN (SELECT bucket FROM login_attempts WHERE expires_at<? LIMIT 100)').bind(now),db.prepare('DELETE FROM shared_sessions WHERE token_hash IN (SELECT token_hash FROM shared_sessions WHERE expires_at<? OR idle_until<? LIMIT 100)').bind(now,now)]);const h=await headers();const ip=h.get('cf-connecting-ip');async function admit(id:string,limit:number){const row=await db.prepare('INSERT INTO login_attempts (bucket,attempts,expires_at) VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(id,now+1800).first<{attempts:number}>();return !!row&&row.attempts<=limit}if(ip&&!await admit(`client:${window}:${digest(salt+':'+ip)}`,8))return false;if(!await admit(`burst:${minute}`,10))return false;return admit(`global:${window}`,60)}
