'use client';
import {useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,CheckCircle2,Clock3,Link2,Zap,ShieldCheck,Copy} from 'lucide-react';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {integrationStatus} from '@/lib/integration/status';
import './style.css';
const duration=(n:number)=>n>=60?`${Math.floor(n/60)}時間${n%60?`${n%60}分`:''}`:`${n}分`;
type ProposalView={id:string;status:string;summary:Record<string,unknown>;expiresAt:string};
export default function Connections({date,proposals}:{date:string;proposals:ProposalView[]}){
 const retry=useRef<{signature:string;key:string}|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[charge,setCharge]=useState<any>(null),[selectedDate,setDate]=useState(date),[candidates,setCandidates]=useState<any[]|null>(null),[copied,setCopied]=useState('');
 async function invoke(name:string,args:unknown){const signature=JSON.stringify({name,args});const key=retry.current?.signature===signature?retry.current.key:Array.from(crypto.getRandomValues(new Uint8Array(16))).map(v=>v.toString(16).padStart(2,'0')).join('');retry.current={signature,key};const r=await fetch('/api/v1/actions/'+name,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(args)});const value=await r.json() as any;if(!r.ok){if(r.status<500)retry.current=null;throw Error(value.error?.message??'接続を確認してください。');}retry.current=null;return value;}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'接続を確認してください。');}finally{setBusy(false);}}
 const pending=proposals.filter(p=>p.status==='pending');
 return <div className="integration-shell"><header className="integration-top"><a href="/" className="back-link"><ArrowLeft/>今日へ戻る</a><b>e-Palette <span>ONE</span></b></header><main className="integration-main"><p className="eyebrow">AI・ほかの交通サービスとの連携</p><h1>入口が変わっても、<br/>同じ予定につながる。</h1><p className="integration-lead">検索や計算を頼み、内容を見て、確定する。<br/>予約・空席・車両予定は、いつもの画面と共通です。</p><div className="integration-note"><ShieldCheck/><div><strong>いまは模擬データで確認する検証版です</strong><p>外部AI・交通事業者とは未接続です。実際の送迎や課金は行われません。</p></div></div>
 {error&&<div className="integration-error" role="alert">{error}</div>}
 {pending.length>0&&<section className="integration-card"><div className="integration-section-title"><Clock3/><h2>内容の確認が必要です</h2><span>{pending.length}件</span></div>{pending.map(p=><a className="proposal-row" href={'/approvals/'+p.id} key={p.id}><div><strong>{String(p.summary.title)}</strong><small>内容を見て、確定または見送り</small></div><ArrowRight/></a>)}</section>}
 <div className="integration-grid"><section className="integration-card"><Zap/><h2>次の利用までに、<br/>充電は間に合う？</h2><p>残量と予定から、普通・急速それぞれの時間と出発期限を確認します。</p><button disabled={busy} onClick={()=>void run(async()=>setCharge(await invoke('get_charge_plan',{vehicleId:'EP-01'})))}>EP-01の充電を確認<ArrowRight/></button>{charge&&<div className="charge-answer" aria-live="polite"><strong>計算処理による見込み</strong>{charge.plans?.filter((p:any)=>!p.uncertain).map((p:any)=><div key={p.stationId}><b>{p.mode==='ac'?'普通充電':'急速充電'}</b>{p.valid?<><span>{duration(p.min)}〜{duration(p.max)}</span><p>{new Date(p.leaveAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}までに出発</p><small>{p.possible?'間に合う見込み':'開始期限を過ぎています'}</small></>:<p>{p.reason}</p>}</div>)}{!charge.plans&&<p>{charge.reason}</p>}<small>模擬の残量・車両仕様による計算です。</small></div>}</section>
 <section className="integration-card"><Link2/><h2>乗りたい便を探して、<br/>内容を確認する。</h2><p>大分駅前 → 地域拠点、1人。検証用の無料運行です。</p><label className="integration-label">利用日<input type="date" value={selectedDate} onChange={e=>setDate(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(async()=>{const r=await invoke('search_trips',{date:selectedDate,fromStop:'oita-station',toStop:'community-hub',count:1});setCandidates(r.trips);})}>乗れる便を探す<ArrowRight/></button>{candidates&&<div aria-live="polite">{candidates.length===0?<p>この条件では受付可能な便がありません。</p>:candidates.map(t=><div className="candidate-row" key={t.id}><strong>{new Date(t.start).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'})}　{t.name}</strong><p>空席 {t.available}人・検証用 0円</p><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{const a=await invoke('prepare_ride_booking',{tripId:t.id,count:1,fromStop:'oita-station',toStop:'community-hub'});window.location.assign(a.approvalUrl);})}>予約内容を確認する<ArrowRight/></button></div>)}</div>}</section></div>
 <section className="integration-card"><h2>使い方は、3つだけ。</h2><ol className="integration-steps"><li><span>1</span><div><strong>話す・選ぶ</strong><p>AIまたは画面から、検索や計画を依頼。</p></div></li><li><span>2</span><div><strong>内容を見る</strong><p>日時・場所・人数・金額を確認。</p></div></li><li><span>3</span><div><strong>本人が確定する</strong><p>内容が変わった場合は、もう一度確認。</p></div></li></ol></section>
 <Collapsible className="integration-card"><CollapsibleTrigger className="detail-trigger">接続方法と、現在できること<span>＋</span></CollapsibleTrigger><CollapsibleContent><p>AIサービス側の登録と認証設定が必要です。ここにURLがあるだけで接続済みにはなりません。</p><div className="endpoint-row"><label>MCP</label><code>/mcp</code><button className="secondary" onClick={()=>void navigator.clipboard.writeText(window.location.origin+'/mcp').then(()=>setCopied('MCPのURLをコピーしました'))}><Copy/>URLをコピー</button></div><div className="endpoint-row"><label>A2A</label><code>/a2a</code></div><p aria-live="polite">{copied}</p><a className="back-link" href="/api/v1/openapi" target="_blank" rel="noreferrer">通常APIの定義を開く<ArrowRight/></a><a className="back-link" href="/api/v1/gtfs">検証用の時刻表データを取得する<ArrowRight/></a><div className="standards-list">{integrationStatus.map(s=><div key={s.name}><h3>{s.name} <small>{s.version}</small></h3><strong>{s.connection}</strong><p>{s.scope}</p><small>{s.implementation} / {s.verification}</small></div>)}</div><p>接続確認の記録：外部AI 0件・交通事業者 0件・QR認証ハブ 0件。</p></CollapsibleContent></Collapsible>
 </main></div>;
}
