'use strict';
const EVENTS = window.JMS_EVENTS || [];
const DAYS = ['2026-10-13','2026-10-14','2026-10-15','2026-10-16'];
const WEEK = ['火','水','木','金'];
const KEY = 'mdl-jms-bizweek-2026-public-v1';
const VENUES = {
 stage:{name:'ステージ',hall:'展示ホール2側',note:'未来モビリティ会議・ステージプログラムの会場。公式会場図の右奥にあります。',link:'https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf'},
 a:{name:'コミュニケーションエリア A',hall:'展示ホール3側',note:'アクセラレーション・共創推進プログラムの会場。公式会場図の左側、CEATEC連絡通路寄りです。',link:'https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf'},
 b:{name:'コミュニケーションエリア B',hall:'展示ホール2側',note:'アクセラレーション・共創推進プログラムの会場。公式会場図の右手前にあります。',link:'https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf'},
 ceatec:{name:'コンベンションホールB（HB）',hall:'国際会議場 2F / 展示ホールとは別棟',note:'10/13（火）13:00–13:45「日本の未来社会に向けて」の会場。要予約。展示ホール2・3との移動時間に余裕をみてください。',link:'https://www.m-messe.co.jp/facility/'}
};
let themeFilter='all';
const THEMES={digital:{label:'AI・データ・デジタル',mark:'＋'},green:{label:'環境・エネルギー',mark:'◇'},people:{label:'人・共創・事業づくり',mark:'◎'},life:{label:'暮らし・まち・移動',mark:'⌂'},engineering:{label:'技術・ものづくり',mark:'△'},future:{label:'未来社会・総合',mark:'☆'},unspecified:{label:'テーマ未指定',mark:'○'}};
function topic(e){return window.JMS_TOPIC_BY_ID?.[e.id]||'unspecified';}
function topicTag(e){const t=THEMES[topic(e)];return `<span class="topic-tag topic-${topic(e)}"><span aria-hidden="true">${t.mark}</span> ${t.label}</span>`;}
let venueFilter='all',selectedPlace='stage';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = n => `<svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true">${({heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h3m3 0h3"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'})[n]||''}</svg>`;
const mins = t => Number(t.slice(0,2))*60+Number(t.slice(3,5));
const sortEvents = (a,b) => (a.date+a.start).localeCompare(b.date+b.start)||a.id.localeCompare(b.id);
const dayLabel = d => `10月${Number(d.slice(8))}日（${WEEK[DAYS.indexOf(d)]||''}）`;
const dateShort = d => `10/${Number(d.slice(8))} ${WEEK[DAYS.indexOf(d)]||''}`;
let state={saved:[],plan:[],custom:[],travel:{outbound:'',inbound:'',buffer:'15',homeby:''}},storageOK=true;
try { const s=JSON.parse(localStorage.getItem(KEY)||'null'); if(s){ if(Array.isArray(s.saved))state.saved=s.saved.filter(x=>typeof x==='string'); if(Array.isArray(s.plan))state.plan=s.plan.filter(x=>typeof x==='string'); if(Array.isArray(s.custom))state.custom=s.custom.filter(e=>e&&typeof e.id==='string'&&typeof e.title==='string'&&DAYS.includes(e.date)&&/^\d{2}:\d{2}$/.test(e.start)&&/^\d{2}:\d{2}$/.test(e.end)&&mins(e.end)>mins(e.start));if(s.travel&&typeof s.travel==='object') Object.keys(state.travel).forEach(k=>state.travel[k]=String(s.travel[k]??state.travel[k])); } } catch { storageOK=false; }
let view=['explore','saved','plan','map'].includes(location.hash.slice(1))?location.hash.slice(1):'explore';
const todayJST = new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let selectedDay=DAYS.includes(todayJST)?todayJST:'2026-10-13',query='',category='all',travelDay='2026-10-13',undoAction=null,toastTimer=null,currentDetail=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('#storage-warning').hidden=storageOK;}
function allEvents(){return [...EVENTS,...state.custom];}
function planned(){return allEvents().filter(e=>state.plan.includes(e.id)).sort(sortEvents);}
function group(e){return e.category==='ワークショップ'?'workshop':e.category==='インプットセッション'?'input':['特別セッション','ビジネスセッション'].includes(e.category)?'forum':e.category==='CEATEC 特別企画セッション'?'ceatec':e.category==='自分の予定'?'custom':'stage';}
function catLabel(e){return ({workshop:'ワークショップ',input:'インプット',forum:'未来モビリティ会議',stage:'ステージ',ceatec:'CEATEC特別企画',custom:'自分の予定'})[group(e)];}
function shortVenue(v){return String(v).replace('コミュニケーションエリア ','エリア ').replace('国際会議場2F コンベンションホールB (HB)','国際会議場 2F・ホールB');}
function showToast(message,undo){clearTimeout(toastTimer);undoAction=undo||null;$('#toast').innerHTML=`<span>${esc(message)}</span>${undo?'<button data-action="undo">元に戻す</button>':''}`;$('#toast').hidden=false;toastTimer=setTimeout(()=>{$('#toast').hidden=true;undoAction=null;},7000);}
function toggle(id,key){const existed=state[key].includes(id);if(existed)state[key]=state[key].filter(x=>x!==id);else state[key].push(id);save();render();if(currentDetail)detail(currentDetail,false);showToast(key==='plan'?(existed?'予定から外しました':'マイ予定に保存しました'):(existed?'候補から外しました':'気になるに保存しました'),()=>{if(existed&&!state[key].includes(id))state[key].push(id);else if(!existed)state[key]=state[key].filter(x=>x!==id);save();render();if(currentDetail)detail(currentDetail,false);});}
function buttons(e){const p=state.plan.includes(e.id),s=state.saved.includes(e.id);return `<div class="event-actions">${e.category!=='自分の予定'?`<button class="save-button" data-save="${esc(e.id)}" aria-label="${esc(e.title)}を${s?'気になるから外す':'気になるに保存'}" aria-pressed="${s}">${icon('heart')}</button>`:''}<button class="plan-button" data-plan="${esc(e.id)}" aria-label="${esc(e.title)}を${p?'予定から外す':'予定に保存'}" aria-pressed="${p}">${icon(p?'check':'plus')}<span>${p?'保存済':'予定'}</span></button></div>`;}
function card(e,showDate=false){return `<article class="event-card topic-${topic(e)} ${state.plan.includes(e.id)?'in-plan':''}" data-event="${esc(e.id)}"><div class="time-rail">${showDate?`<span class="date-mini">${dateShort(e.date)}</span>`:''}<b>${esc(e.start)}</b><span>– ${esc(e.end)}</span></div><div class="event-main"><div class="card-top">${topicTag(e)}<span class="tag ${group(e)}">${catLabel(e)}</span>${e.reservation==='required'?'<span class="reserve">要予約</span>':''}</div><button class="card-title" data-detail="${esc(e.id)}" aria-label="詳細：${esc(e.title)}"><span>${esc(e.title.replace(/^【[^】]+】/,''))}</span></button>${e.venueKey?`<button class="venue-link venue-${esc(e.venueKey)}" data-map-venue="${esc(e.venueKey)}" aria-label="会場を見る：${esc(e.venue)}、${esc(e.hall)}">${icon('pin')}<span><b>${esc(shortVenue(e.venue))}</b><small>${esc(e.hall)} · 会場を見る ↗</small></span></button>`:`<p class="meta-line">${icon('pin')}<span>${esc(e.venue)}</span></p>`}</div>${buttons(e)}</article>`;}
function empty(title,body,action='explore',label='スケジュールを探す'){return `<div class="empty"><img class="empty-mascot" loading="lazy" src="yaseuma-scooter.png" alt="やせうまスクーター｜非公式ガイドのキャラクター" width="1312" height="1199" decoding="async"><h2>${title}</h2><p>${body}</p><button class="primary" data-empty="${action}">${label}</button></div>`;}
function render(){
 $('#guide-hero').hidden=view!=='explore';$('.day-bar').hidden=view==='map';document.title=({explore:'探す',saved:'気になる',plan:'マイ予定',map:'会場ガイド'})[view]+'｜JMS BIZWEEK 2026 非公式ガイド';
 document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==view);document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelectorAll('[data-count]').forEach(b=>b.textContent=b.dataset.count==='saved'?state.saved.length:planned().length);
 $('#days').innerHTML=`<button data-day="all" class="${selectedDay==='all'?'active':''}" aria-pressed="${selectedDay==='all'}">全日</button>`+DAYS.map((d,i)=>`<button data-day="${d}" class="${d===selectedDay?'active':''}" aria-pressed="${d===selectedDay}"><span>10/${13+i}</span><small>${WEEK[i]}</small><span class="day-count">${EVENTS.filter(e=>e.date===d).length}</span></button>`).join('');
 const cats=[['all','すべて'],['forum','未来モビリティ会議'],['workshop','ワークショップ'],['input','インプット'],['stage','ステージ'],['ceatec','CEATEC']];$('#categories').innerHTML=cats.map(([v,l])=>`<button data-category="${v}" class="${category===v?'active':''}" aria-pressed="${category===v}">${l}</button>`).join('');
 const filtered=EVENTS.filter(e=>(selectedDay==='all'||e.date===selectedDay)&&(themeFilter==='all'||topic(e)===themeFilter)&&(category==='all'||group(e)===category)&&(venueFilter==='all'||e.venueKey===venueFilter)&&[e.title,THEMES[topic(e)].label,e.venue,e.hall||'',e.category,...(e.speakers||[]),...(e.moderators||[]),...(e.aliases||[])].join(' ').normalize('NFKC').toLowerCase().includes(query.normalize('NFKC').toLowerCase())).sort(sortEvents);
 $('#result-count').innerHTML=`<strong>${filtered.length}</strong> 枠<span> / ${selectedDay==='all'?'4日間':dayLabel(selectedDay)}${query?'・検索結果':''}</span>`;$('#event-list').innerHTML=filtered.length?filtered.map(e=>card(e,selectedDay==='all')).join(''):empty('条件に合う予定がありません','検索語や日付を変えてみてください。','reset','絞り込みを解除');$('#clear-query').hidden=!query;$('#reset-filters').hidden=!query&&category==='all'&&venueFilter==='all'&&themeFilter==='all';
 const favorites=EVENTS.filter(e=>state.saved.includes(e.id)&&(selectedDay==='all'||e.date===selectedDay)).sort(sortEvents);$('#saved-list').innerHTML=favorites.length?favorites.map(e=>card(e,selectedDay==='all')).join(''):empty('気になる企画を、ここに。',state.saved.length?'選択した日には候補がありません。全日で確認できます。':'ハートを押すと、参加を迷っている企画を残せます。',state.saved.length?'all':'explore',state.saved.length?'全日の候補を見る':'スケジュールを探す');
 renderPlan();renderTravel();renderVenue();$('#storage-warning').hidden=storageOK;
}
function renderPlan(){const events=planned().filter(e=>selectedDay==='all'||e.date===selectedDay);if(!events.length){$('#plan-list').innerHTML=empty('今日の動きを、ひとつずつ。',planned().length?'選択した日には予定がありません。全日で確認できます。':'「＋ 予定」で1タップ保存。商談や展示見学も追加できます。',planned().length?'all':'explore',planned().length?'全日の予定を見る':'スケジュールを探す');return;}
 let html='';for(const d of DAYS){const es=events.filter(e=>e.date===d);if(!es.length)continue;html+=`<div class="group-heading"><h2>${dayLabel(d)}</h2><span>${es.length}件・日本時間</span></div><div class="event-list">`;es.forEach((e,i)=>{const overlaps=es.slice(0,i).filter(p=>mins(p.end)>mins(e.start));if(overlaps.length)html+=`<p class="conflict">時間が重なっています：${esc(overlaps.map(p=>p.title.replace(/^【[^】]+】/,'')).join(' / '))}</p>`;else if(i){const gap=mins(e.start)-Math.max(...es.slice(0,i).map(p=>mins(p.end)));html+=`<p class="gap-note">${gap>0?`次まで ${gap} 分`:'次の予定まで余裕なし'}${es[i-1].venue!==e.venue?'・会場間の移動を確認':''}</p>`;}html+=card(e);});html+='</div>'; }$('#plan-list').innerHTML=html;}
function navigate(v){view=v;location.hash=v;render();window.scrollTo({top:0,behavior:'instant'});}
function openDialog(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;if(!$('#dialog').open)$('#dialog').showModal();}
function detail(id,open=true){const e=allEvents().find(e=>e.id===id);if(!e)return;currentDetail=id;const reservation=e.reservation==='required'?'要予約':e.reservation==='not_required'?'予約不要・自由席':e.category==='自分の予定'?'自分で追加した予定':'個別の参加条件を公式で確認';openDialog('プログラム詳細',`${topicTag(e)} <span class="tag ${group(e)}">${catLabel(e)}</span><h3 class="detail-title">${esc(e.title)}</h3><dl class="detail-grid"><dt>日時</dt><dd><strong>${dayLabel(e.date)} ${esc(e.start)}–${esc(e.end)}</strong><br><span class="muted small">2026年・日本時間</span></dd><dt>会場</dt><dd><strong>${esc(e.venue)}</strong>${e.hall?`<p>${esc(e.hall)}</p><button class="text-button" data-map-venue="${esc(e.venueKey)}">会場の位置を確認 ↗</button>`:''}</dd><dt>参加</dt><dd>${reservation}${e.reservationNote?`<p class="small muted">${esc(e.reservationNote)}</p>`:''}</dd>${e.speakers?.length?`<dt>登壇者</dt><dd>${e.speakers.map(esc).join('、')}${e.moderators?.length?`<p class="small muted">進行：${e.moderators.map(esc).join('、')}</p>`:''}</dd>`:''}</dl>${e.relatedNote?`<p class="notice">${esc(e.relatedNote)} このガイドでは同時刻・同会場の1枠として表示しています。</p>`:''}${e.notes?`<p class="small muted">${esc(e.notes)}</p>`:''}${e.source?`<div class="source-links"><a href="${esc(e.source)}" target="_blank" rel="noopener noreferrer">公式の詳細・最新情報 ↗</a>${e.reservationUrl?`<a href="${esc(e.reservationUrl)}" target="_blank" rel="noopener noreferrer">公式の予約ページ ↗</a>`:''}${e.relatedSource?`<a href="${esc(e.relatedSource)}" target="_blank" rel="noopener noreferrer">同枠のリバースピッチ案内 ↗</a>`:''}</div>`:''}<div class="detail-actions">${e.category!=='自分の予定'?`<button class="secondary" data-save="${esc(e.id)}">${state.saved.includes(id)?'♥ 候補に保存済み':'♡ 気になるに保存'}</button>`:''}<button class="plan-button" data-plan="${esc(e.id)}" aria-pressed="${state.plan.includes(id)}">${icon(state.plan.includes(id)?'check':'plus')}${state.plan.includes(id)?'予定から外す':'マイ予定に保存'}</button></div><p class="small muted" style="margin-top:12px">このアプリで保存しても、参加予約は完了しません。</p>`);}
function about(){currentDetail=null;openDialog('このガイドについて',`<div class="about-copy"><p><strong>Japan Mobility Show Bizweek 2026</strong><br>2026年10月13日（火）–16日（金）<br>幕張メッセ 国際展示場2・3ホール</p><h3>掲載範囲</h3><p>公式に日付と時刻が公開された41枠を収録。未来モビリティ会議・ステージ12枠、共創推進プログラム28枠、CEATEC特別企画1枠です。同じ日時・会場に掲載されたリバースピッチ1件は、関連枠の詳細に併記しています。</p><p>時刻未掲載のショートピッチなど、全企画を網羅したものではありません。</p><h3>予約・最新情報</h3><p>MDL（モビリティデザインラボ）が制作した非公式ガイドです。主催者・共催者の公式サイト、提携・公認サービスではありません。保存は参加予約ではありません。来場登録や各企画の予約は公式サイトで行ってください。満席・残席・予約済み状況は取得していません。</p><p>プログラム確認日：2026年10月7日。会場案内更新日：2026年10月8日（日本時間）。自動更新ではありません。変更は各カードの公式リンクで確認できます。</p><h3>予定の保存</h3><p>候補・マイ予定・移動設定は、この端末のブラウザ内だけに保存します。別の端末には同期されず、閲覧データの削除で消えます。マイ予定はカレンダーファイル（.ics）で書き出せます。独自のアクセス解析や予定の外部送信は行いません。配信元のGitHub Pagesはアクセス時の技術情報を取り扱います。外部リンクを開くと、リンク先の規約・プライバシーポリシーが適用されます。公開版は、各訪問者の端末で空の予定から始まります。</p><h3>地図・画像について</h3><p>会場の概略図は、公式公開情報の位置関係をもとにMDLが作成しました。縮尺・方位・正確な通路は再現していません。公式写真・ロゴ・公式PDFの画像は転載せず、公式資料へ直接リンクしています。名称・商標は各権利者に帰属します。</p><h3>公式出典</h3><div class="source-links"><a href="https://www.japan-mobility-show.com/outline/" target="_blank" rel="noopener noreferrer">開催概要 ↗</a><a href="https://www.japan-mobility-show.com/future-mobility-forum/" target="_blank" rel="noopener noreferrer">未来モビリティ会議 ↗</a><a href="https://www.japan-mobility-show.com/acc-cocreation/" target="_blank" rel="noopener noreferrer">アクセラレーション・共創推進プログラム ↗</a><a href="https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf" target="_blank" rel="noopener noreferrer">公式会場マップ ↗</a><a href="https://www.japan-mobility-show.com/faq/" target="_blank" rel="noopener noreferrer">公式FAQ・参加条件 ↗</a><a href="https://www.ceatec.com/ja/conference/detail.html?id=3347" target="_blank" rel="noopener noreferrer">CEATEC特別企画 ↗</a></div></div>`);}
function custom(booth=false){currentDetail=null;openDialog(booth?'Garraway 0 / F の見学':'自分の予定を追加',`<form id="custom-form" class="custom-form"><div class="field"><label for="custom-title">予定の名前</label><input id="custom-title" required maxlength="120" placeholder="例：ブース見学・商談" value="${booth?'Garraway 0 / F ブース見学':''}"></div><div class="field"><label for="custom-date">日付</label><select id="custom-date">${DAYS.map(d=>`<option value="${d}" ${d===(selectedDay==='all'?DAYS[0]:selectedDay)?'selected':''}>${dayLabel(d)}</option>`).join('')}</select></div><div class="field-grid"><div class="field"><label for="custom-start">開始</label><input id="custom-start" type="time" required min="10:00" max="17:00" value="10:00"></div><div class="field"><label for="custom-end">終了</label><input id="custom-end" type="time" required min="10:00" max="17:00" value="10:30"></div></div><div class="field"><label for="custom-venue">場所</label><input id="custom-venue" maxlength="100" value="${booth?'展示ホール2・3 C-05 Garraway 0 / F':'幕張メッセ'}"></div><p class="small muted" style="margin-top:14px">自分用の予定です。相手への連絡や参加予約は行いません。</p><p id="custom-error" class="error-text" role="alert"></p><button type="submit" class="primary">マイ予定に保存</button></form>`);}
function timeDisplay(value){const days=Math.floor(value/1440);const n=((value%1440)+1440)%1440;return `${days<0?'前日 ':days>0?'翌日 ':''}${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function renderTravel(){const es=planned().filter(e=>e.date===travelDay);const out=Number(state.travel.outbound),back=Number(state.travel.inbound),buffer=Number(state.travel.buffer);if(!es.length){$('#travel-result').innerHTML='<p class="travel-placeholder">この日の予定を保存すると、出発と帰着の目安が出ます。</p>';return;}if(state.travel.outbound===''||state.travel.inbound===''||![out,back,buffer].every(Number.isFinite)||out<0||back<0||buffer<0||out>1440||back>1440||buffer>180){$('#travel-result').innerHTML='<p class="travel-placeholder">行き・帰りの所要時間を入力してください。余裕時間は0〜180分、所要時間は0〜1440分で設定できます。</p>';return;}const start=mins(es[0].start),end=Math.max(...es.map(e=>mins(e.end)));const homeby=/^\d{2}:\d{2}$/.test(state.travel.homeby)?mins(state.travel.homeby):null;$('#travel-result').innerHTML=`<div class="travel-result"><div class="travel-row"><span>出発の目安</span><strong>${timeDisplay(start-out-buffer)}</strong></div><div class="travel-row"><span>会場を出る目安</span><strong>${timeDisplay(end)}</strong></div><div class="travel-row"><span>帰着の目安</span><strong>${timeDisplay(end+back)}</strong></div><p>${dayLabel(travelDay)}・最初 ${esc(es[0].start)} / 最後 ${timeDisplay(end)}<br>行き ${out}分＋余裕 ${buffer}分 / 帰り ${back}分</p></div>${homeby!==null?`<div class="travel-warn">${end+back>homeby?`帰着希望 ${state.travel.homeby} に間に合わせるには、<strong>${timeDisplay(homeby-back)}</strong> までに会場を出る必要があります。最後の予定を見直してください。`:`帰着希望 ${state.travel.homeby} まで、${homeby-end-back}分の余裕があります。`}</div>`:''}`;}
function calendarExport(){const events=planned();if(!events.length){showToast('まず予定を保存してください');return;}const escapeICS=v=>String(v??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const utc=(d,t)=>new Date(`${d}T${t}:00+09:00`).toISOString().replace(/[-:]/g,'').replace('.000','');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//JMS Unofficial Guide//JP','CALSCALE:GREGORIAN','METHOD:PUBLISH',...events.flatMap(e=>['BEGIN:VEVENT',`UID:${e.id}@jms-unofficial.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace('.000','')}`,`DTSTART:${utc(e.date,e.start)}`,`DTEND:${utc(e.date,e.end)}`,`SUMMARY:${escapeICS(e.title)}`,`LOCATION:${escapeICS(e.venue)}`,`DESCRIPTION:${escapeICS('非公式ガイドから保存。参加予約ではありません。'+(e.source?'公式：'+e.source:''))}`,'END:VEVENT']),'END:VCALENDAR'];const folded=lines.flatMap(line=>{let chunks=[],chunk='',bytes=0;for(const ch of line){const n=new TextEncoder().encode(ch).length;if(bytes+n>75){chunks.push(chunk);chunk=' ';bytes=1;}chunk+=ch;bytes+=n;}chunks.push(chunk);return chunks;});const blob=new Blob([folded.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='JMS-2026-my-plan.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`${events.length}件をカレンダーファイルに書き出しました`);}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.view){navigate(b.dataset.view);return;}if(b.dataset.mapVenue){selectedPlace=b.dataset.mapVenue;$('#dialog').close();navigate('map');$('#venue-detail').scrollIntoView({block:'center',behavior:'smooth'});return;}if(b.dataset.place){selectedPlace=b.dataset.place;renderVenue();return;}if(b.dataset.venuePrograms){themeFilter='all';$('#theme-filter').value='all';venueFilter=b.dataset.venuePrograms;$('#venue-filter').value=venueFilter;query='';category='all';$('#query').value='';navigate('explore');$('#event-list').scrollIntoView({block:'start'});return;}if(b.dataset.day){selectedDay=b.dataset.day;if(selectedDay!=='all'){travelDay=selectedDay;$('#travel-day').value=travelDay;}render();return;}if(b.dataset.category){category=b.dataset.category;render();return;}if(b.dataset.plan){toggle(b.dataset.plan,'plan');return;}if(b.dataset.save){toggle(b.dataset.save,'saved');return;}if(b.dataset.detail){detail(b.dataset.detail);return;}if(b.dataset.empty){if(b.dataset.empty==='all'){selectedDay='all';render();}else if(b.dataset.empty==='reset'){category='all';themeFilter='all';$('#theme-filter').value='all';venueFilter='all';$('#venue-filter').value='all';query='';selectedDay='all';$('#query').value='';render();}else navigate('explore');return;}
 const action=b.dataset.action;if(action==='garraway'){navigate('map');$('#garraway-guide').scrollIntoView({block:'start',behavior:'smooth'});}if(action==='find'){$('#query').focus({preventScroll:true});$('.search-wrap').scrollIntoView({block:'start',behavior:'smooth'});}if(action==='about')about();if(action==='close')$('#dialog').close();if(action==='undo'){undoAction?.();$('#toast').hidden=true;undoAction=null;}if(action==='custom'||action==='booth')custom(action==='booth');if(action==='export')calendarExport();if(action==='travel'){navigate('map');$('#travel-panel').scrollIntoView({behavior:'smooth',block:'start'});$('#outbound').focus({preventScroll:true});}});
$('#theme-filter').addEventListener('change',e=>{themeFilter=e.target.value;render();});
$('#query').addEventListener('input',e=>{query=e.target.value;render();});$('#clear-query').addEventListener('click',()=>{query='';$('#query').value='';render();$('#query').focus();});$('#reset-filters').addEventListener('click',()=>{query='';category='all';themeFilter='all';$('#theme-filter').value='all';venueFilter='all';$('#venue-filter').value='all';$('#query').value='';selectedDay='all';render();});
$('#dialog').addEventListener('close',()=>{currentDetail=null;});$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close();}});
document.addEventListener('submit',e=>{if(e.target.id!=='custom-form')return;e.preventDefault();const start=$('#custom-start').value,end=$('#custom-end').value,title=$('#custom-title').value.trim();if(!title||mins(end)<=mins(start)){$('#custom-error').textContent='予定の名前と、開始より後の終了時刻を入力してください。';return;}const item={id:'custom-'+crypto.randomUUID(),date:$('#custom-date').value,start,end,title,category:'自分の予定',venue:$('#custom-venue').value.trim()||'場所未定',speakers:[],reservation:'personal'};state.custom.push(item);state.plan.push(item.id);save();$('#dialog').close();selectedDay=item.date;navigate('plan');showToast('自分の予定を保存しました',()=>{state.plan=state.plan.filter(x=>x!==item.id);state.custom=state.custom.filter(x=>x.id!==item.id);save();render();});});
$('#travel-day').innerHTML=DAYS.map(d=>`<option value="${d}">${dayLabel(d)}</option>`).join('');$('#travel-day').addEventListener('change',e=>{travelDay=e.target.value;renderTravel();});['outbound','inbound','buffer','homeby'].forEach(id=>{$('#'+id).value=state.travel[id];$('#'+id).addEventListener('input',e=>{state.travel[id]=e.target.value;save();renderTravel();});});document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['explore','saved','plan','map'].includes(v)&&view!==v){view=v;render();}});window.addEventListener('storage',e=>{if(e.key===KEY)showToast('別のタブで予定が変更されました。再読み込みすると反映されます。');});render();

function renderVenue(){
 const v=VENUES[selectedPlace]||VENUES.stage;
 document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.place===selectedPlace)));
 $('#venue-detail').innerHTML=`<p class="eyebrow">${esc(v.hall)}</p><h3>${esc(v.name)}</h3><p>${esc(v.note)}</p><div class="map-shortcuts"><button class="primary" data-venue-programs="${esc(selectedPlace)}">この会場の企画を見る</button><a class="secondary" href="${esc(v.link)}" target="_blank" rel="noopener noreferrer">公式の会場図を開く ↗</a></div>`;
}
$('#venue-filter').addEventListener('change',e=>{venueFilter=e.target.value;render();});
