window.JMS_EVENTS = [
  {
    "id": "acc-1013-w1",
    "date": "2026-10-13",
    "start": "10:15",
    "end": "11:00",
    "title": "【W1】オープンイノベーションとは？なぜ共創が必要なのか？スタートアップに学ぶ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1013-special",
    "date": "2026-10-13",
    "start": "11:00",
    "end": "12:00",
    "title": "動かし続ける日本を、どのように創るか",
    "category": "特別セッション",
    "venue": "特設ステージ",
    "speakers": [
      "滝野 一征",
      "野呂 侑希",
      "佐藤 恒治",
      "三部 敏宏"
    ],
    "reservation": "not_required",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "佐々木 紀彦"
    ],
    "reservationNote": "未来モビリティ会議は事前申込・座席予約なしの自由席。入場登録は別途必要。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-t1",
    "date": "2026-10-13",
    "start": "12:00",
    "end": "12:45",
    "title": "【T1】製造業のDX・データ駆動型開発",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-t4",
    "date": "2026-10-13",
    "start": "12:30",
    "end": "13:15",
    "title": "【T4】最新AI技術による業務生産性向上と人的資本活用",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T4",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "ceatec-1013-future",
    "date": "2026-10-13",
    "start": "13:00",
    "end": "13:45",
    "title": "日本の未来社会に向けて",
    "category": "CEATEC 特別企画セッション",
    "venue": "国際会議場2F コンベンションホールB (HB)",
    "speakers": [
      "佐藤 恒治",
      "新野 隆"
    ],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "moderators": [
      "佐久間 あすか"
    ],
    "group": "CEATEC 2026",
    "reservationNote": "要予約。JMSの展示ホールとは別の国際会議場で開催。予約済みかどうかは未確認。",
    "detailUrl": "https://www.ceatec.com/ja/conference/detail.html?id=3347",
    "reservationUrl": "https://www.ceatec.com/ja/conference/reservation-guide.html",
    "availability": null,
    "availabilityNote": "CEATECの動的な残席・受付状態は取得できていません。締切・満席とは判断していません。",
    "venueKey": "ceatec",
    "hall": "国際会議場 2F（別棟）",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/"
  },
  {
    "id": "fm-1013-japia",
    "date": "2026-10-13",
    "start": "13:00",
    "end": "14:00",
    "title": "構想を社会実装へ 〜協働から生まれる自動車部品産業の新たな価値〜",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "島田 淳",
      "川嵜 隆司",
      "中村 智",
      "河村 繁",
      "小松 隆史"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [],
    "organizer": "一般社団法人 日本自動車部品工業会",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "relatedListing": "acc-1013-reverse",
    "relationshipNote": "アクセラレーションページにも同日同時刻・会場のリバースピッチ表記あり。同一企画かどうか公式ページに明記なし。",
    "relatedNote": "同日同時刻・会場にJAPIAの「構想を社会実装へ」も掲載。同一企画かどうか公式ページに明記なし。独立した別セッションと断定しないこと。",
    "relatedSource": "https://www.japan-mobility-show.com/acc-cocreation/",
    "aliases": [
      "リバースピッチ"
    ],
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-w2",
    "date": "2026-10-13",
    "start": "14:00",
    "end": "15:00",
    "title": "【W2】イノベーション活動推進における困りごとの解決、次の一手",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-t2",
    "date": "2026-10-13",
    "start": "15:00",
    "end": "15:45",
    "title": "【T2】人材基盤の強化：ベテランの技・知見をどう引き継いでいくか",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1013-business",
    "date": "2026-10-13",
    "start": "15:00",
    "end": "16:30",
    "title": "テクノロジーとともに、人がもっと人らしく",
    "category": "ビジネスセッション",
    "venue": "特設ステージ",
    "speakers": [
      "岡田 利久",
      "尾形 哲也",
      "イヴァン・エスピノーサ"
    ],
    "reservation": "not_required",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "須黒 清華"
    ],
    "reservationNote": "未来モビリティ会議は事前申込・座席予約なしの自由席。入場登録は別途必要。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-w4",
    "date": "2026-10-13",
    "start": "15:30",
    "end": "16:30",
    "title": "【W4】モノづくり課題解決 共創ワークショップ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W4",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1013-n1",
    "date": "2026-10-13",
    "start": "16:00",
    "end": "16:45",
    "title": "【N1】Physical-AIテクノロジーが支える新たな労働力",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day1",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-w1",
    "date": "2026-10-14",
    "start": "10:30",
    "end": "11:30",
    "title": "【W1】オープンイノベーションとは？なぜ共創が必要なのか？海外事例から学ぶ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1014-connected",
    "date": "2026-10-14",
    "start": "11:00",
    "end": "12:00",
    "title": "データが社会を動かす 〜車両データで挑む、これからの社会課題解決〜",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "小山田 哲也",
      "福森 穣",
      "竹本 毅"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "桃田 建史"
    ],
    "organizer": "一般社団法人 日本自動車工業会 コネクティッド部会",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-n9",
    "date": "2026-10-14",
    "start": "11:30",
    "end": "12:30",
    "title": "【N9】世界に貢献できる日本DeepTechとは何か",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N9",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-t6",
    "date": "2026-10-14",
    "start": "12:15",
    "end": "13:15",
    "title": "【T6】スタートアップの海外展開と現地企業との連携",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T6",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1014-business",
    "date": "2026-10-14",
    "start": "13:00",
    "end": "14:30",
    "title": "環境も経済も、ともにより良い方へ",
    "category": "ビジネスセッション",
    "venue": "特設ステージ",
    "speakers": [
      "山﨑 敦義",
      "大場 紀章",
      "毛籠 勝弘",
      "岸浦 恵介"
    ],
    "reservation": "not_required",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "須黒 清華"
    ],
    "reservationNote": "未来モビリティ会議は事前申込・座席予約なしの自由席。入場登録は別途必要。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-w2",
    "date": "2026-10-14",
    "start": "13:30",
    "end": "14:30",
    "title": "【W2】イノベーション活動推進における困りごとの解決、次の一手",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-n2",
    "date": "2026-10-14",
    "start": "14:15",
    "end": "15:15",
    "title": "【N2】資源循環とサーキュラーエコノミー",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-w6",
    "date": "2026-10-14",
    "start": "15:15",
    "end": "16:15",
    "title": "【W6】エネルギー課題解決共創ワークショップ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W6",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1014-n3",
    "date": "2026-10-14",
    "start": "15:30",
    "end": "16:30",
    "title": "【N3】次世代電動化技術とエネルギー・マネジメント",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N3",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day2",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1014-physical-ai",
    "date": "2026-10-14",
    "start": "15:30",
    "end": "16:30",
    "title": "フィジカルAIが再創造するモビリティ開発・運用サイクル 〜産業アーキテクチャからのアプローチ〜",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "細井 裕介",
      "阿部 健太郎"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [],
    "organizer": "PwCコンサルティング合同会社",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-w1",
    "date": "2026-10-15",
    "start": "10:30",
    "end": "11:30",
    "title": "【W1】オープンイノベーションとは？なぜ共創が必要なのか？スタートアップに学ぶ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1015-bestcar",
    "date": "2026-10-15",
    "start": "10:30",
    "end": "11:30",
    "title": "東京モビリティ会議2026withベストカー",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "佐藤 恒治",
      "遠藤 佑馬",
      "上野 亜斗瑠",
      "出川 貴久",
      "加藤 介",
      "高橋 百佳"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "寺崎 彰吾"
    ],
    "organizer": "講談社BECK",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-t7",
    "date": "2026-10-15",
    "start": "11:00",
    "end": "12:00",
    "title": "【T7】海外スタートアップと日本企業の連携",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T7",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-t5",
    "date": "2026-10-15",
    "start": "12:00",
    "end": "13:00",
    "title": "【T5】投資・CVCセッション",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T5",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1015-business",
    "date": "2026-10-15",
    "start": "13:00",
    "end": "14:30",
    "title": "滞らないシステムで、広がる安心",
    "category": "ビジネスセッション",
    "venue": "特設ステージ",
    "speakers": [
      "村上 建治郎",
      "加藤 真平",
      "山口 真宏",
      "サティヤカーム・アーリャ",
      "伊藤 公一"
    ],
    "reservation": "not_required",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "須黒 清華"
    ],
    "reservationNote": "未来モビリティ会議は事前申込・座席予約なしの自由席。入場登録は別途必要。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-w2",
    "date": "2026-10-15",
    "start": "13:30",
    "end": "14:30",
    "title": "【W2】イノベーション活動推進における困りごとの解決、次の一手",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-t3",
    "date": "2026-10-15",
    "start": "14:00",
    "end": "15:00",
    "title": "【T3】製造・設備保全からアフターマーケットまでAIとデータで繋ぐサプライチェーン変革",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "T3",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-w5",
    "date": "2026-10-15",
    "start": "15:15",
    "end": "16:15",
    "title": "【W5】モビリティインフラ共創ワークショップ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W5",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1015-n6",
    "date": "2026-10-15",
    "start": "15:30",
    "end": "16:30",
    "title": "【N6】空間コンピューティングとXR・デジタルツイン",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N6",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day3",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1015-vision2050",
    "date": "2026-10-15",
    "start": "15:30",
    "end": "16:30",
    "title": "“モビリティビジョン2050”ダイアログ 〜ビジョンから実装へ モビリティを通じた社会課題解決への挑戦〜",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "木津 雅文",
      "山下 浩行",
      "小澤 崇",
      "吉田 真一郎",
      "林 範人",
      "染道 颯人",
      "山本 晋也"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "岡田 雅司"
    ],
    "organizer": "一般社団法人 日本自動車工業会 次世代モビリティ政策部会",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-w1",
    "date": "2026-10-16",
    "start": "10:30",
    "end": "11:30",
    "title": "【W1】オープンイノベーションとは？なぜ共創が必要なのか？海外事例から学ぶ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W1",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-n8",
    "date": "2026-10-16",
    "start": "11:00",
    "end": "12:00",
    "title": "【N8】社会実装の起点としての大学研究機関",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N8",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1016-privacy",
    "date": "2026-10-16",
    "start": "11:00",
    "end": "12:00",
    "title": "改正個人情報保護法から考える、データ保護と利活用",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "竹澤 玲央",
      "冨重 亜紀子",
      "香月 健太郎"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "小林 慎太郎"
    ],
    "organizer": "一般社団法人 日本自動車工業会 情報トラスト部会",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-n5",
    "date": "2026-10-16",
    "start": "12:00",
    "end": "13:00",
    "title": "【N5】街づくり・地域交通と非自動車産業との接続",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N5",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1016-business",
    "date": "2026-10-16",
    "start": "13:00",
    "end": "14:30",
    "title": "人もモノもデータも、すべてがシームレスに",
    "category": "ビジネスセッション",
    "venue": "特設ステージ",
    "speakers": [
      "齊藤 せつな",
      "三輪 富生",
      "設楽 元文",
      "大崎 篤",
      "井上 雅宏"
    ],
    "reservation": "not_required",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "須黒 清華"
    ],
    "reservationNote": "未来モビリティ会議は事前申込・座席予約なしの自由席。入場登録は別途必要。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-w2",
    "date": "2026-10-16",
    "start": "13:30",
    "end": "14:30",
    "title": "【W2】イノベーション活動推進における困りごとの解決、次の一手",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W2",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-n7",
    "date": "2026-10-16",
    "start": "14:00",
    "end": "15:00",
    "title": "【N7】テクノロジーが拡張するヘルスケアとウェルビーイング",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N7",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-w3",
    "date": "2026-10-16",
    "start": "15:15",
    "end": "16:15",
    "title": "【W3】次世代の街づくり共創ワークショップ",
    "category": "ワークショップ",
    "venue": "コミュニケーションエリア B",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "W3",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "b",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "acc-1016-n4",
    "date": "2026-10-16",
    "start": "15:30",
    "end": "16:30",
    "title": "【N4】マイクロモビリティと多様な移動",
    "category": "インプットセッション",
    "venue": "コミュニケーションエリア A",
    "speakers": [],
    "reservation": "required",
    "source": "https://www.japan-mobility-show.com/acc-cocreation/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "programCode": "N4",
    "group": "アクセラレーション・共創推進プログラム",
    "reservationUrl": "https://jms-meetup-box.com/mypage/seminar_reservation/#day4",
    "reservationNote": "要予約。Meet-up Boxへのログインが必要。予約済みかどうかはこのデータでは確認していません。",
    "speakerStatus": "公開タイムテーブルに登壇者の記載なし",
    "venueKey": "a",
    "hall": "展示ホール3側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  },
  {
    "id": "fm-1016-china",
    "date": "2026-10-16",
    "start": "15:30",
    "end": "16:30",
    "title": "中国自動車産業の強みとその活かし方",
    "category": "ステージプログラム",
    "venue": "特設ステージ",
    "speakers": [
      "佐藤 涼太"
    ],
    "reservation": "unknown",
    "source": "https://www.japan-mobility-show.com/future-mobility-forum/",
    "timezone": "Asia/Tokyo",
    "verifiedAt": "2026-10-07",
    "group": "未来モビリティ会議",
    "moderators": [
      "南保 賢"
    ],
    "organizer": "PwCコンサルティング合同会社",
    "reservationNote": "個別プログラムに予約要否の明記なし。公式FAQは未来モビリティ会議を自由席と案内し、その他のステージは各主催者へ問い合わせとしています。",
    "reservationSource": "https://www.japan-mobility-show.com/faq/",
    "venueKey": "stage",
    "hall": "展示ホール2側",
    "venueVerifiedAt": "2026-10-08",
    "venueSource": "https://www.japan-mobility-show.com/JMS2026_MAP_JP.pdf"
  }
];
