import {renderAccess} from './access-view.mjs';
import {directionsUrl} from './access-model.mjs';
import {VIEWS,ROLES,CITY_INFO,esc,number,displayValue,nearbyStops,readState,stateUrl,filterRecords,csvFor,lodgingComparison} from './model.mjs?v=1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data,state,geo,map,pointLayer,routeLayer,radiusLayer,page=0,compareMode='lodging',stopLimit=12,transportPromise,toastTimer;
const link=(url,label)=>/^https?:\/\//.test(url??'')?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:esc(label);
const find=(area,metric,period)=>data.records.find(r=>r.area===area&&r.metric===metric&&r.period===period);
const source=id=>data.sources.find(s=>s.id===id);
const recordSource=r=>r?.sourceId?`<button class="text-link" data-record="${r.id}">数字の条件・出典</button>`:'';
const sourceLine=id=>{const s=source(id);return s?`<p class="source-line">出典：${link(s.url,s.publisher+'｜'+s.title)}</p>`:''};
function metricCard(label,r,{featured=false,change=null,sub=null}={}){const v=displayValue(r,true);return `<article class="metric-card ${featured?'featured':''}"><p class="metric-label">${esc(label)}</p><p class="metric-value">${v.value}<span class="metric-unit">${esc(v.unit)}</span></p><p class="metric-sub">${esc(r?.period??'未取得')}<br>${esc(sub??r?.method??'原表の取得が必要です')}</p>${change!==null?`<span class="change">前年比 ${change>0?'+':''}${number(change,1)}%</span>`:''}${recordSource(r)}</article>`;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3600);}
function download(content,name,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function updateUrl(replace=false){history[replace?'replaceState':'pushState'](null,'',stateUrl(location.href,state));}
function navigate(view,changes={},scroll=true){state={...state,...changes,view:VIEWS.includes(view)?view:'overview'};if(state.area!=='all'&&!data.anchors.some(a=>a.id===state.anchor&&a.area===state.area))state.anchor=data.anchors.find(a=>a.area===state.area)?.id??data.anchors[0].id;page=0;updateUrl();render();if(scroll){window.scrollTo({top:0,behavior:'auto'});$('#main').focus({preventScroll:true})}}
function render(){
 $('#area').value=state.area;$('#role').value=state.role;
 const role=ROLES[state.role];$('#role-guide').innerHTML=`<b>${esc(role.label)}</b><span>${esc(role.text)}</span><a href="#guide">使い方を見る</a>`;
 $$('.app-nav a').forEach(a=>{if(a.dataset.view===state.view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 $$('.view').forEach(p=>p.hidden=p.id!=='panel-'+state.view);
 document.title=(state.area==='all'?'大分':state.area)+'｜'+({'overview':'観光の特徴','compare':'数字を比べる','mobility':'現地でのアクセス','access':'観光地へのアクセス','issues':'課題と検証','data':'データを探す','guide':'使い方'})[state.view]+'｜観光・周遊データマップ';
 if(state.view==='overview')renderOverview();
 if(state.view==='compare')renderCompare();
 if(state.view==='issues')renderIssues();
 if(state.view==='data')renderData();
 if(state.view==='guide')renderGuide();
 if(state.view==='mobility')showMobility();
 if(state.view==='access')renderAccess(data,state,accessChanged);
}
function accessChanged(changes,focusId){state={...state,...changes};updateUrl(true);renderAccess(data,state,accessChanged);document.getElementById(focusId)?.focus();}
function quickStart(){return `<div class="quick-start"><p><strong>何を調べますか？</strong><span>目的を選んで、すぐに始められます。</span></p><div class="access-entries"><button data-navigate="access"><span class="entry-symbol" aria-hidden="true">↗</span><span><b>観光地へのアクセスを調べる</b><small>駅・空港からの行き方と、行って帰れる条件</small></span><span class="entry-arrow" aria-hidden="true">→</span></button><button data-navigate="mobility"><span class="entry-symbol" aria-hidden="true">↔</span><span><b>観光地でのアクセスを調べる</b><small>着いてからの周遊、近くの乗り場・運行予定</small></span><span class="entry-arrow" aria-hidden="true">→</span></button></div><div class="quick-secondary"><button data-open-modes>交通分担率・利用割合を調べる <span>→</span></button><button data-navigate="issues">地域の課題・検証項目を整理する <span>→</span></button><button data-navigate="guide">初めての方へ <span>→</span></button></div></div>`;}

function renderOverview(){
 const all=state.area==='all',city=CITY_INFO[state.area];
 const cards=all?[
  metricCard('大分県を訪れた回数',find('大分県','観光入込客数・計','2025年'),{featured:true,change:-3.94047486,sub:'共通基準／観光・業務を含む'}),
  metricCard('県内の観光消費額',find('大分県','観光消費額・計','2025年'),{change:-7.38629647,sub:'共通基準／名目の推計額'}),
  metricCard('県調査の延べ宿泊',find('大分県','延べ宿泊客数','2025年'),{change:4.29285938,sub:'従業員10人以上の対象施設'}),
  metricCard('国内客の自家用車利用',data.records.find(r=>r.category==='交通手段'&&r.population==='国内居住者'&&r.metric==='自家用車・社用車等'),{sub:'国内居住者4,742回答／複数回答'})
 ].join(''):cityMetrics(state.area);
 const intro=all?'宿泊の増加と、入込・消費の減少が同時に起きています。':'地域の特徴を、数字と移動から確認します。';
 const body=all?`<div class="section-head"><div><h2>６市町、それぞれの問い。</h2><p>対象年・集計範囲が違うため、カードの大小で順位付けしません。</p></div><button class="button small" data-navigate="compare">同じ条件で比べる →</button></div><div class="city-grid">${data.municipalities.map(m=>cityCard(m.name)).join('')}</div>`:cityDetail(state.area);
 $('#panel-overview').innerHTML=quickStart()+`<div class="section-head"><div><span class="eyebrow">01 / ${all?'PREFECTURE OVERVIEW':city.en}</span><h2>${all?'まず、大分全体をつかむ。':esc(state.area)+'を知る。'}</h2><p>${intro}</p></div></div><div class="metric-grid">${cards}</div><div class="insight-strip"><b>${all?'数字から考えること':esc(city.focus)}</b><p>${all?'人数・宿泊・消費は別の調査系列です。ひとつの増減だけで判断せず、地域と移動の条件を確認します。':esc(city.note)}</p></div>${body}${all?`<div class="two-col">${modesPanel()}${stayPanel()}</div><div class="two-col">${yufuPanel()}${beppuPanel()}</div>`:''}`;
}
function cityMetrics(area){const list=data.records.filter(r=>r.area===area&&r.provenance.sheet==='01_6市町データ'&&r.value!==null);const spec=CITY_INFO[area],headline=find(area,spec.metric,spec.period);const chosen=[headline,...list.filter(r=>r!==headline&&!r.period.includes('2017')&&!r.period.includes('2019'))].filter(Boolean).slice(0,4);if(chosen.length===1){const gw=data.records.find(r=>r.area===area&&r.category==='GW・施設'&&r.period.startsWith('2026'));if(gw&&gw!==headline)chosen.push(gw)}return chosen.map((r,i)=>metricCard(r.metric,r,{featured:i===0,sub:r.method})).join('');}
function cityCard(area){const c=CITY_INFO[area],r=find(area,c.metric,c.period),v=displayValue(r,true);const label=r?.category==='GW・施設'?'GW・'+c.metric+'入場者':c.metric;return `<article class="city-card" style="--city-color:${c.color}"><div class="city-top"><h3 class="city-name">${area}</h3><span class="city-en">${c.en}</span></div><p class="city-question">${c.question}</p><p class="city-number">${v.value}<small>${v.unit}</small></p><p class="city-measure">${esc(label)}<br>${esc(c.period)} · ${esc(r?.method??'')}</p><p class="city-note">${c.note}</p><button class="button" data-city="${area}">この地域を調べる <span aria-hidden="true">→</span></button></article>`;}
function cityDetail(area){const c=CITY_INFO[area],rows=data.records.filter(r=>r.area===area&&r.provenance.sheet==='01_6市町データ');return `<div class="two-col"><div class="panel"><h3>この地域で考えたいこと</h3><p class="description">${c.question}</p><ul class="plain-list">${c.needs.map(t=>'<li>'+esc(t)+'</li>').join('')}</ul><div class="tab-buttons"><button data-navigate="mobility">周辺の交通を見る →</button><button data-navigate="issues">課題と検証を見る →</button></div></div><div class="panel"><h3>不足しているデータも確認する</h3><p class="description">移動の供給を見ても、実際の需要や住民への影響はまだ分かりません。</p><p class="subtle">日帰りの滞在時間、地点間の移動、時間帯別の混雑、地域に残る追加消費は別途計測が必要です。</p><button class="text-link" data-navigate="data">${area}の収録データをすべて見る →</button></div></div>${area==='由布市'?yufuPanel():area==='別府市'?beppuPanel():''}<div class="section-head"><div><h3>原典ごとの観光実績</h3><p>古い基準値・指定施設の集計・未取得を区別しています。</p></div></div>${recordTable(rows)}`;}
function bars(rows,{max=null,unit='',color='var(--blue)'}={}){const top=max??Math.max(1,...rows.map(r=>r.value??0));return `<div class="bar-chart">${rows.map(r=>`<div class="bar-row ${r.value===null?'missing':''}"><span class="bar-label">${esc(r.label)}</span><div class="bar-track">${r.value===null?'':`<span style="width:${Math.max(.3,r.value/top*100)}%;background:${r.color??color}"></span>`}</div><span class="bar-value">${r.value===null?'未収録':esc(r.formatted??number(r.value))+'<small> '+esc(unit)+'</small>'}</span></div>`).join('')}</div>`;}
function modesPanel(){const rows=data.tables['03_県内交通手段'];const names=['自家用車・社用車等','レンタカー','JR在来線','貸切バス','高速バス','市内バス','タクシー'];return `<div class="panel"><h3>交通分担率・利用割合を調べる</h3><p class="description">国内客・海外客の県内での交通利用｜2025年度</p><div class="legend"><span><i></i>国内居住者 n=4,742</span><span><i class="orange"></i>海外居住者 n=200</span></div><div class="dual-bars">${names.map(n=>{const a=rows.find(r=>r[1]==='国内居住者'&&r[2]===n),b=rows.find(r=>r[1]==='海外居住者'&&r[2]===n);return `<div class="dual-row"><strong>${esc(n.replace('・社用車等','等'))}</strong><div><span class="dual-track"><i style="width:${a[5]*100}%"></i></span><b>${number(a[5]*100,1)}%</b><span class="dual-track orange"><i style="width:${b[5]*100}%"></i></span><b>${number(b[5]*100,1)}%</b></div></div>`}).join('')}</div><p class="footnote">ここで確認できるのは複数回答の「利用割合」です。主な交通手段を１つ選ぶ分担率とは異なり、合計100%にはなりません。国内は全体から海外回答を差し引いて再集計。６市町別や、観光地までの交通分担率は未取得です。</p>${sourceLine('P04')}</div>`;}
function stayPanel(){const stay=data.tables['04_滞在と消費'].filter(r=>r[0]==='宿泊日数');return `<div class="panel"><h3>県内での宿泊は、１泊が中心。</h3><p class="description">宿泊旅行者が大分県内に泊まった日数｜2025年度</p>${bars(stay.map(r=>({label:r[2],value:r[3]*100,formatted:number(r[3]*100,1)+'%'})),{max:100})}<div class="notice">「県内0泊」は、旅行中に宿泊していても大分県内には泊まらない人です。全観光客の日帰り率ではありません。</div><p class="footnote">宿泊旅行者 n=2,178。平均泊数は、この区分表から算出していません。</p>${sourceLine('P04')}<button class="text-link" data-navigate="data">滞在・消費のデータを見る →</button></div>`;}
function yufuPanel(){const rows=data.tables['05_由布2025月次'].filter(r=>r[0]!=='年間計'),max=Math.max(...rows.map(r=>r[5]));return `<div class="panel"><h3>由布市の月ごとの動き</h3><p class="description">2025年・市観光動態調査／外国人は内数</p><div class="legend"><span><i></i>日帰り</span><span><i class="orange"></i>宿泊</span><span>上の数字は総数・万人</span></div><div class="vertical-chart" role="img" aria-label="由布市2025年月次。最多は11月397,558人、最少は7月279,091人。詳細は下の表。">${rows.map(r=>`<div class="month-column" title="${r[0]} 日帰り${number(r[1])}人、宿泊${number(r[2])}人"><span class="month-value">${number(r[5]/1e4,1)}</span><div class="month-bar" style="height:${r[5]/max*87}%"><span class="stay-segment" style="height:${r[2]/r[5]*100}%"></span></div><span class="month-label">${r[0]}</span></div>`).join('')}</div><p class="footnote">月間の客数は、昼間の混雑密度や交通需要を示すものではありません。</p><details><summary>月別の正確な数字を見る</summary>${simpleTable(['月','日帰り','宿泊','総数'],rows.map(r=>[r[0],number(r[1]),number(r[2]),number(r[5])]))}</details>${sourceLine('M01')}</div>`;}
function beppuPanel(){const rows=data.tables['06_別府詳細'].filter(r=>r[0]==='地区別宿泊');return `<div class="panel"><h3>別府では、どこに泊まっている？</h3><p class="description">2024年・市の宿泊地区別集計</p>${bars(rows.map(r=>({label:r[2],value:r[3],formatted:number(r[3]/1e4,1)+'万人'})))}<div class="notice">宿泊が多い地区と、昼間の混雑地点は同じとは限りません。地区間の移動を確認する必要があります。</div><p class="footnote">入湯税申告に基づく市の調査。課税対象でない施設は含まれません。</p>${sourceLine('M02')}</div>`;}
function simpleTable(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((c,i)=>`<td${i?' class="numeric"':''}>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function renderCompare(){
 compareMode=state.comparison??'lodging';
 let body='';
 if(compareMode==='lodging'){const rows=lodgingComparison(data);body=`<div class="panel"><h3>2025年・同じ県調査で見る延べ宿泊</h3><p class="description">従業員10人以上の対象施設。県内すべての宿泊施設を網羅するものではありません。</p>${bars(rows.map(r=>({label:r.area,value:r.record?.value??null,formatted:r.record?number(r.record.value/1e4,1)+'万人泊':null})))}<p class="footnote">日出・宇佐・国東の個別値は、この比較系列に未収録です。ゼロや「宿泊が少ない」とは判定しません。</p>${sourceLine('P02')}</div><div class="notice amber">由布市の市調査139.3万人と、県調査41.8万人泊は対象・定義が違います。このグラフへ市独自調査の値を代入しません。</div>`;}
 if(compareMode==='gw'){let rows=data.tables['07_GW2026'];if(state.area!=='all')rows=rows.filter(r=>r[0]===state.area);body=`<div class="panel"><h3>GWの同じ８日間を、施設ごとに比較</h3><p class="description">各年4月29日〜5月6日。掲載は主要10施設で、県全体の合計ではありません。</p>${rows.length?simpleTable(['施設・所在','2025年','2026年','前年比'],rows.map(r=>[r[1]+'（'+r[0]+'）',number(r[2])+'人',number(r[3])+'人',(r[4]>0?'+':'')+number(r[4]*100,1)+'%'])):'<div class="empty">この地域の施設は、今回のGW一覧に収録されていません。</div>'}<p class="footnote">曜日・天候・開園状況の違いがあります。年間トレンドや混雑率に外挿しません。</p>${sourceLine('E01')}</div>`;}
 if(compareMode==='monthly')body=`<div class="two-col">${yufuPanel()}${beppuPanel()}</div><p class="footnote">別々の調査です。由布と別府を同じグラフに重ねたり合算したりしていません。</p>`;
 if(compareMode==='modes')body=`<div class="two-col">${modesPanel()}<div class="panel"><h3>交通を考えるときの読み方</h3><p class="description">県全体のアンケートから、移動の仮説を分けます。</p><ol class="step-list"><li><div><strong>自家用車で来る人</strong>中心部への流入、駐車待ち、乗り換える理由を調べる。</div></li><li><div><strong>鉄道・バスで来る人</strong>最後の移動、荷物、乗り継ぎ、帰りの便を調べる。</div></li><li><div><strong>現地で実際に確かめる</strong>この県全体の割合を、各施設の人数へ掛けて需要予測にしない。</div></li></ol><button class="button primary" data-navigate="mobility">観光地周辺のバスを見る →</button></div></div>`;
 $('#panel-compare').innerHTML=`<div class="section-head"><div><span class="eyebrow">02 / COMPARABLE DATA</span><h2>比べられる数字を、同じ条件で。</h2><p>調査の対象と期間がそろう組み合わせを用意しました。</p></div></div><div class="tab-buttons" aria-label="比較するデータ">${[['lodging','県調査の宿泊'],['gw','GWの施設入場'],['monthly','月別・地区別'],['modes','国内客・海外客の交通']].map(([id,t])=>`<button data-compare="${id}" aria-pressed="${compareMode===id}">${t}</button>`).join('')}</div>${compareMode!=='gw'&&state.area!=='all'?'<p class="footnote">比較のため、県全体・関連地域も表示しています。</p>':''}${body}`;
}
async function ensureTransport(){if(geo)return geo;if(!transportPromise)transportPromise=fetch(data.transport.url).then(r=>{if(!r.ok)throw Error('交通データを読み込めませんでした。再読み込みしてください。');return r.json()}).then(g=>{geo=g;return g}).catch(e=>{transportPromise=null;throw e});return transportPromise;}
async function showMobility(){
 const anchors=data.anchors.filter(a=>state.area==='all'||a.area===state.area);
 if(!anchors.some(a=>a.id===state.anchor))state.anchor=anchors[0].id;
 $('#anchor').innerHTML=anchors.map(a=>`<option value="${a.id}">${esc(a.area+'｜'+a.name)}</option>`).join('');$('#anchor').value=state.anchor;
 $('#map-day').innerHTML=data.transport.dates.map((d,i)=>`<option value="${i}">${esc(d)}</option>`).join('');$('#map-day').value=state.day;$('#radius').value=state.radius;
 try{await ensureTransport();if(state.view!=='mobility')return;if(!map){if(!window.L)throw Error('地図を読み込めません。ページを再読み込みしてください。');map=L.map('tourism-map',{scrollWheelZoom:false,preferCanvas:true,minZoom:7,maxZoom:18});let failures=0;const tiles=L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',{maxZoom:18,attribution:'背景：<a href="https://maps.gsi.go.jp/development/ichiran.html">地理院タイル</a>｜交通：大分県・CC BY 4.0'}).addTo(map);tiles.on('tileerror',()=>{if(++failures>2)$('#tile-warning').hidden=false});tiles.on('tileload',()=>{$('#tile-warning').hidden=true;failures=0});routeLayer=L.layerGroup().addTo(map);radiusLayer=L.layerGroup().addTo(map);pointLayer=L.layerGroup().addTo(map);}drawTransport(true);setTimeout(()=>map.invalidateSize(),50);}catch(e){$('#transport-status').textContent=e.message;$('#transport-status').classList.add('error');}
}
function drawTransport(fit=false){
 const a=data.anchors.find(a=>a.id===state.anchor);if(!a||!map)return;
 const localPlaces=data.anchors.filter(p=>p.area===a.area&&p.id!==a.id);
 $('#local-trip').innerHTML=`<div class="local-trip-head"><div><span class="eyebrow">GETTING AROUND / ${CITY_INFO[a.area].en}</span><h3>${esc(a.name)}から、次の場所へ。</h3><p>周遊先を選ぶと、徒歩・公共交通の経路や直通バスの往復を調べられます。</p></div><button class="button small" data-navigate="access">ここまでのアクセスを見る →</button></div><div class="local-places">${localPlaces.map(p=>`<article><strong>${esc(p.name)}</strong><span>${esc(p.area)} · 停留所を基準に検索</span><div><a href="${esc(directionsUrl(a,p,'walking'))}" target="_blank" rel="noopener noreferrer">徒歩の道順 ↗</a><a href="${esc(directionsUrl(a,p,'transit'))}" target="_blank" rel="noopener noreferrer">公共交通 ↗</a></div><button class="text-link" data-local-from="${a.id}" data-local-to="${p.id}">直通便・帰りを調べる →</button></article>`).join('')}</div><p class="footnote">地図サービスで道路・入口を確認してください。徒歩経路をこのアプリで算出したものではありません。</p>`;

 $('#transport-status').classList.remove('error');$('#transport-status').innerHTML=`<b>交通：${esc(geo.meta.dateLabels[state.day])}の運行予定</b> ／ 観光統計は各カードの期間。異なる時期のため、人数÷便数で混雑や不足を判定しません。`;
 const rows=nearbyStops(geo,a,state.radius,state.day,$('#active-only').checked);pointLayer.clearLayers();routeLayer.clearLayers();radiusLayer.clearLayers();
 geo.shapes.filter(s=>s.trips[state.day]>0&&s.coordinates.some(p=>Math.abs(p[0]-a.lat)<.022&&Math.abs(p[1]-a.lon)<.024)).forEach(s=>L.polyline(s.coordinates,{color:'#4961bb',opacity:.3,weight:2,interactive:false}).addTo(routeLayer));
 L.circle([a.lat,a.lon],{radius:state.radius,color:'#263ddb',weight:1,dashArray:'4 5',fillOpacity:.035}).addTo(radiusLayer);
 rows.forEach(s=>{const n=s.departures[state.day],color=n===null?'#8d99a9':n>0?'#2439dc':'#a4aebb';L.circleMarker([s.lat,s.lon],{radius:n>0?5:3,color:'white',weight:1.5,fillColor:color,fillOpacity:.9}).addTo(pointLayer).bindTooltip(esc(s.name)).bindPopup(stopPopup(s));});
 L.circleMarker([a.lat,a.lon],{radius:10,color:'white',weight:3,fillColor:'#d95727',fillOpacity:1}).addTo(pointLayer).bindTooltip(esc(a.name)+'（停留所基準点）');
 if(fit)map.fitBounds(L.latLngBounds([[a.lat-state.radius/111000,a.lon-state.radius/92000],[a.lat+state.radius/111000,a.lon+state.radius/92000]]),{padding:[20,20],maxZoom:15});
 $('#nearby-caption').textContent=`${rows.length}乗り場 ／ 近い順に${Math.min(stopLimit,rows.length)}件。方向・事業者ごとのIDを保持。`;
 $('#stop-list').innerHTML=rows.length?rows.slice(0,stopLimit).map(s=>stopCard(s)).join('')+(rows.length>stopLimit?'<button class="button" data-more-stops>さらに12件を見る</button>':''):'<div class="empty">この範囲・条件で収録した乗り場はありません。範囲を広げるか、チェックを外してください。未収録の交通がないという意味ではありません。</div>';
 const gw=a.gwFacility?data.records.find(r=>r.category==='GW・施設'&&r.metric===a.gwFacility&&r.period.startsWith('2026')):null;
 const local=gw??find(a.area,CITY_INFO[a.area].metric,CITY_INFO[a.area].period),v=displayValue(local,true);
 $('#place-insight').innerHTML=`<span class="eyebrow">${CITY_INFO[a.area].en} / PLACE & DATA</span><h3>${esc(a.name)}</h3><p>${esc(CITY_INFO[a.area].question)}</p><div class="map-stat"><small>${esc(gw?'関連施設：'+a.gwFacility+'入場者':a.area+'の参考指標')}</small><b>${v.value}<span class="metric-unit">${esc(v.unit)}</span></b><small>${esc(local?.period??'未取得')}<br>${esc(local?.metric??'')}</small>${recordSource(local)}</div><p class="footnote">${esc(a.positionNote)}${gw?' 統計の施設と停留所の地点は区別しています。':''}</p><p class="footnote">${link(a.sourceUrl,'停留所位置の出典')}</p><button class="button" data-navigate="issues" data-area="${a.area}">この地域で何を測る？ →</button>`;
}
function trafficUrl(s){const q=new URLSearchParams({feedId:geo.feeds[s.feedIndex].id,stopId:s.id,day:String(state.day)});return '../oita-mobility/?'+q+'#map';}
function stopPopup(s){const f=geo.feeds[s.feedIndex],n=s.departures[state.day];return `<strong>${esc(s.name)}</strong><br>${esc(f.name.replace('GTFSデータ',''))}<br>${esc(geo.meta.dateLabels[state.day])}<br>出発：${n===null?'対象期間外':number(n)+'本'}<br><a href="${esc(trafficUrl(s))}">この乗り場を交通マップで開く →</a>`;}
function stopCard(s){const f=geo.feeds[s.feedIndex];return `<article class="stop-card"><h3>${esc(s.name)}</h3><p class="operator">${esc(f.name.replace('GTFSデータ',''))}<br>基準点から直線${number(s.distance)}m · 乗り場ID ${esc(s.id)}</p><div class="stop-times">${s.departures.map((n,i)=>`<span class="${i===state.day?'active':''}">9/${[8,12,13][i]} ${['火','土','日'][i]}<b>${n===null?'—':number(n)}</b>${n===null?'対象期間外':'本／日'}</span>`).join('')}</div><a href="${esc(trafficUrl(s))}">同じ乗り場を交通マップで開く →</a></article>`;}
function renderIssues(){const municipalities=data.municipalities.filter(m=>state.area==='all'||m.name===state.area);const resident=data.records.find(r=>r.sourceId==='P05'&&r.unit==='割合');$('#panel-issues').innerHTML=`<div class="section-head"><div><span class="eyebrow">04 / QUESTIONS TO TEST</span><h2>混雑と、地域に残る価値を一緒に考える。</h2><p>確認された事実と、これから検証する仮説を分けています。</p></div><button id="export-brief" class="button primary">検証項目を保存</button></div><div class="notice">ここは実測の混雑マップではありません。年の客数から市全域の「危険度」を付けず、場所・時間・住民への影響を個別に確認します。</div>${municipalities.map(m=>{const c=CITY_INFO[m.name],rows=data.tables['08_混雑と検証'].filter(r=>r[0]===m.name),r=rows[0];return `<article class="issue-card"><div class="issue-top"><h3>${m.name}</h3><span class="tag ${['由布市','別府市'].includes(m.name)?'blue':'muted'}">${esc(r[1])}</span></div><div class="issue-grid"><div><h4>資料で確認できること</h4><p>${esc(r[2])}</p><p class="footnote">${esc(r[3])}</p><p class="source-line">${link(r[8],'根拠資料')}</p><div class="notice">${esc(r[4])}</div></div><div><h4>次に、何を測る？</h4><ul>${c.needs.map(n=>'<li>'+n+'</li>').join('')}</ul><p class="footnote">対象：${esc(r[5])}</p></div></div><div class="hypothesis"><b>施策の仮説</b><br>${esc(r[7])}</div>${rows.length>1?`<details><summary>既存の対策を確認する</summary><p class="subtle">${esc(rows[1][2])} ${esc(rows[1][4])}</p><p>${link(rows[1][8],'既存プロジェクト')}</p></details>`:''}<div class="issue-actions"><button class="button small" data-navigate="mobility" data-area="${m.name}">周辺の交通を見る →</button><button class="text-link" data-navigate="data" data-area="${m.name}">この地域のデータを見る</button></div></article>`}).join('')}<div class="two-col"><div class="panel"><h3>住民側のものさしも持つ。</h3>${resident?`<p class="value-large">${number(resident.value*100,1)}<span class="metric-unit">%</span></p><p class="subtle">2025年・県公式カタログ掲載の観光客受容度</p>${recordSource(resident)}`:''}<p class="footnote">県全体の指標であり、各市町や特定時刻の住民負担を示すものではありません。</p></div><div class="panel"><h3>実証の前後で、３つを確認。</h3><ol class="step-list"><li><div><strong>移動・滞在が変わったか</strong>行けた場所、待ち時間、帰路、追加の立ち寄り。</div></li><li><div><strong>地域に価値が残ったか</strong>追加消費と県内所得は区別。県内調達や継続費用も確認。</div></li><li><div><strong>住民・現場の負担はどうか</strong>生活交通、清掃・接客、自然・文化財への負荷。</div></li></ol></div></div>`;}
function recordTable(rows){return `<div class="records-table"><table><thead><tr><th>地域・期間</th><th>指標・対象</th><th>値・単位</th><th>根拠</th></tr></thead><tbody>${rows.map(r=>{const v=displayValue(r);return `<tr><td>${esc(r.area)}<small>${esc(r.period)}</small></td><td><button class="table-link" data-record="${r.id}">${esc(r.metric)}</button><small>${esc(r.method)}</small></td><td class="numeric">${v.value}${v.unit?' '+esc(v.unit):''}</td><td><span class="tag ${r.value===null?'amber':''}">${esc(r.status)}</span><small>${esc(source(r.sourceId)?.publisher??'原表未取得')}</small></td></tr>`}).join('')}</tbody></table></div>`;}
function filtered(){return filterRecords(data.records,{area:state.area,category:$('#category').value,year:$('#year').value,query:$('#search').value});}
function renderData(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/20));page=Math.min(page,pages-1);$('#record-count').textContent=number(rows.length)+'件の指標';$('#record-list').innerHTML=rows.length?recordTable(rows.slice(page*20,page*20+20)):'<div class="empty">この条件のデータはありません。種類・対象年・キーワードを変更してください。<button class="button small" data-reset-search>検索条件をリセット</button></div>';$('#page-count').textContent=(page+1)+' / '+pages;$('#prev-page').disabled=page===0;$('#next-page').disabled=page===pages-1;}
function showRecord(id){const r=data.records.find(r=>r.id===id);if(!r)return;const s=source(r.sourceId),v=displayValue(r);$('#detail-body').innerHTML=`<span class="tag">${esc(r.area)} · ${esc(r.period)}</span><h2>${esc(r.metric)}</h2><p class="value-large">${v.value}<span class="metric-unit">${esc(v.unit)}</span></p><dl class="detail-grid"><dt>系列</dt><dd>${esc(r.series)}</dd><dt>対象・方法</dt><dd>${esc(r.method)}</dd><dt>扱い</dt><dd>${esc(r.status)}</dd>${r.denominator?`<dt>回答数</dt><dd>${number(r.numerator)}選択／${number(r.denominator)}回答・複数回答</dd>`:''}<dt>確認状況</dt><dd>${esc(r.verification)}</dd>${r.unit!==r.originalUnit?`<dt>原表の単位</dt><dd>${esc(r.originalUnit)}（表示では${esc(r.unit)}に整理）</dd>`:''}</dl><div class="detail-note">${esc(r.note||'原典の対象範囲と期間を確認して利用してください。')}</div>${s?`<h3>${esc(s.publisher)}｜${esc(s.title)}</h3><p class="footnote">${esc(s.locator)}<br>${esc(s.period)}</p><p style="margin-top:15px">${link(s.url,'原典を開く')}</p>`:'<p>比較できる原表は未取得です。ゼロや県平均に置き換えていません。</p>'}<details><summary>収録元と訂正記録</summary><p class="footnote">${esc(r.provenance.sheet)}${r.provenance.row?'・'+r.provenance.row+'行':''}／整理日 ${data.researchAsOf}</p>${data.revisionNotes.filter(n=>n.sourceId===r.sourceId).map(n=>'<p class="footnote">'+esc(n.note)+'</p>').join('')}</details>`;$('#detail-dialog').showModal();}
function renderGuide(){
 $('#panel-guide').innerHTML=`<div class="section-head"><div><span class="eyebrow">START HERE / USER GUIDE</span><h2>何ができる？ どう使う？</h2><p>旅行や案内の前にアクセスを調べたい方と、地域の観光・交通を企画する方のためのアプリです。</p></div></div><div class="panel visitor-guide"><h3>旅行・観光案内に使う方</h3><p class="description">まず「観光地へ行く」で出発地と行き先を選びます。到着後の移動は「現地を回る」へ。旅行当日の経路・時刻は地図サービスで確認できます。</p><button class="button primary" data-navigate="access">アクセスを調べ始める →</button></div><div class="guide-grid"><article class="guide-card"><span class="number">01</span><h3>自治体・観光協会の方</h3><p>観光の特徴、混雑の根拠、住民影響を確認し、施策や調査の優先順位を考える。</p><button class="text-link" data-example="yufu">例：由布の混雑課題を調べる →</button></article><article class="guide-card"><span class="number">02</span><h3>宿泊・観光施設の方</h3><p>周辺の交通と来訪者の行動を確認し、駅・宿泊・飲食・体験をつなぐ条件を考える。</p><button class="text-link" data-example="hiji">例：ハーモニーランド周辺を見る →</button></article><article class="guide-card"><span class="number">03</span><h3>交通事業者の方</h3><p>場所・日ごとの運行予定を確認し、現地で需要や乗り継ぎを調べる地点を絞る。</p><button class="text-link" data-example="beppu">例：別府の地獄エリアを見る →</button></article></div><div class="panel"><h3>基本は、この３ステップ。</h3><ol class="step-list"><li><div><strong>① 調べる地域を選ぶ</strong>画面上部で市町を選択。「地域を知る」で人数・宿泊・消費と注意点を見る。</div></li><li><div><strong>② 観光地まで・現地でのアクセスを調べる</strong>「現地を回る」で場所・日・範囲を選択。近くの乗り場と出発本数を確認する。</div></li><li><div><strong>③ 次に測ることを整理する</strong>「課題を考える」で事実と仮説を分けて確認。「検証項目を保存」で打合せ用に持ち出す。</div></li></ol><button class="button primary" data-example="hiji">この流れを日出町で試す →</button></div><div class="two-col"><div class="panel"><h3>このアプリでできること</h3><ul class="plain-list"><li>県・６市町の統計を、年度と出典付きで読む。</li><li>同じ系列の宿泊、GW施設実績、交通手段を比べる。</li><li>13地点から出発地・行き先を選び、直通便と帰りの候補を見る。</li><li>出発・滞在・帰着の条件から、アクセシビリティを確認する。</li><li>近くの乗り場や周遊先を調べ、外部地図で徒歩・車・公共交通の経路を見る。</li><li>混雑の根拠と、地域ごとの検証項目を確認する。</li><li>検索した指標をCSV保存し、表示条件をURL共有する。</li></ul></div><div class="panel"><h3>判断に追加データが必要なこと</h3><ul class="plain-list"><li>今の混雑、駐車場の空き、バスの空席。</li><li>特定の便に何人乗るかという需要予測。</li><li>実際の歩行・バリアフリー環境と施設の営業時間。</li><li>新しい交通による追加消費や地域所得の効果。</li></ul><p class="footnote">交通・アクセスの照合は2026年9月の指定３日分の運行予定です。旅行当日の運行は各事業者へ確認してください。</p></div></div><div class="panel"><h3>県の公式カタログとの使い分け</h3><p class="description">県の公式カタログは幅広い観光統計や市場分析を確認する入口。このアプリは、地域ごとの問いから交通の条件と検証項目へ進むための入口です。</p><p>${link('https://oita-tourism-data-catalog.com/','おおいた観光データカタログ')}　／　<a href="../oita-mobility/">MDLの交通マップ →</a></p><p class="footnote">MDLが公開資料と共有調査を編集・運営しています。県・市町・交通事業者による公式アプリや推奨施策を示すものではありません。</p></div><div class="section-head"><h3>数字を読むときによくある疑問</h3></div><div class="panel">${[
 ['宿泊客数の数字が資料によって違うのは？','対象施設や集計方法が異なります。県の従業員10人以上施設調査、市の入湯税等の調査、観光庁の宿泊旅行統計は別系列です。名称だけで合算しません。'],
 ['データがない地域は、観光客が少ない？','未取得・非公表はゼロではありません。日出・宇佐などの古い実績を最新の数字として表示しません。'],
 ['年間の観光客数から混雑が分かる？','混雑には場所・時刻・受入容量と住民への影響のデータが必要です。このアプリは、年客数だけで危険度を計算しません。'],
 ['地図の本数は、乗れる人数？','停留所ごとの通常乗車可能な出発数です。座席数や空席ではありません。同じ便が複数の停留所を通るため、乗り場の本数を足して地域全体の便数にしません。'],
 ['データは自動更新される？','この版は整理日を固定した収録データです。自動更新ではありません。元資料の対象年、交通の適用日、出典を各画面で確認できます。'],
 ['交通分担率と利用割合の違いは？','県の観光アンケートは複数回答です。使った交通手段をそれぞれ数える利用割合なので、合計は100％になりません。代表交通手段を１つ選ぶ分担率や、市町別の割合とは区別します。'],
 ['アクセスとアクセシビリティの違いは？','アクセスは目的地までの行き方。アクセシビリティは、時間・徒歩・費用などの条件のもとで目的を果たして帰れるかです。このアプリは直通バスの時刻表から候補を絞り、徒歩・営業・空席など未確認の条件を示します。'],
 ['保存や共有はどうする？','「データを探す」でCSV保存、「課題を考える」で検証項目保存。「この画面を共有」は地域・画面・交通の選択条件を共有します。検索キーワードは共有URLに含めません。'],
 ['ダウンロードしたデータを使える？','数値と一緒に出典・対象年・単位・加工内容を残し、各原典の利用条件に従ってください。異なる系列の合算や、未取得をゼロにする処理は避けてください。']
 ].map(([q,a])=>`<details><summary>${q}</summary><p class="subtle">${a}</p></details>`).join('')}</div><div class="section-head"><div><h3>出典一覧</h3><p>${data.sources.length}件の資料・データ案内。原典の対象と時点へ戻れます。</p></div><a class="button small" href="data/tourism.json" download>収録データを保存</a></div><ul class="source-list">${data.sources.map(s=>`<li>${link(s.url,s.publisher+'｜'+s.title)}<p>${esc(s.period)}<br>${esc(s.locator)}</p><p>${esc(s.note)}</p></li>`).join('')}</ul><details><summary>今回の照合とデータの整理</summary><p class="subtle">調査ブック10シートから177件の指標を整理。由布月次・別府主要実績・GW施設値を原典と照合し、ブック内の88数式を独立計算して確認しました。全資料の全行を再調査したものではありません。</p>${data.revisionNotes.map(n=>'<p class="footnote">'+esc(n.note)+'</p>').join('')}</details>`;
}
function exportBrief(){const areas=data.municipalities.filter(m=>state.area==='all'||m.name===state.area);let t='# 観光・交通の検証メモ\n\n整理日：'+data.researchAsOf+'\n利用目的：'+ROLES[state.role].label+'\n\n';for(const m of areas){const c=CITY_INFO[m.name],r=data.tables['08_混雑と検証'].find(r=>r[0]===m.name);t+=`## ${m.name}\n\n問い：${c.question}\n\n資料の事実：${r[2]}\n資料時点：${r[3]}\n出典：${r[8]}\n\nまだ断定しないこと：${r[4]}\n\n測る項目：\n${c.needs.map(n=>'- [ ] '+n).join('\n')}\n\n施策の仮説：${r[7]}\n\n検証設計（未記入）\n- 責任者：\n- 対象地点・時間帯：\n- 実施前の基準値：\n- 比較する条件・期間：\n- 測定期間・費用：\n- 継続／変更／停止の条件：\n\n`; }t+='\n交通の便数は運行予定。需要・空席・実際の混雑を示しません。追加消費と地域に残る所得は区別し、住民への影響も同時に測ります。\n';download(t,'oita-tourism-verification.md','text/markdown;charset=utf-8');toast('検証項目を保存しました。');}
function wire(){
 $('#area').addEventListener('change',()=>navigate(state.view,{area:$('#area').value},false));$('#role').addEventListener('change',()=>navigate(state.view,{role:$('#role').value},false));
 document.addEventListener('click',e=>{
  const b=e.target.closest('button,a');if(!b)return;
  if(b.dataset.view){e.preventDefault();navigate(b.dataset.view);return;}
  if(b.matches('a[href^="#"]')&&VIEWS.includes(b.hash.slice(1))){e.preventDefault();navigate(b.hash.slice(1));return;}
  if(b.dataset.city){navigate('overview',{area:b.dataset.city});return;}
  if(b.hasAttribute('data-open-modes')){navigate('compare',{comparison:'modes'});return;}
  if(b.dataset.localTo){navigate('access',{origin:b.dataset.localFrom,anchor:b.dataset.localTo});return;}
  if(b.dataset.tripExample){const pairs={beppu:['beppu-station','beppu-jigoku','別府市'],hiji:['hiji-yokoku','hiji-harmony','日出町'],yufu:['yufu-station','yufu-takemoto','由布市']};const [origin,anchor,area]=pairs[b.dataset.tripExample];navigate('access',{origin,anchor,area});return;}
  if(b.dataset.navigate){navigate(b.dataset.navigate,b.dataset.area?{area:b.dataset.area}:{});return;}
  if(b.dataset.record){showRecord(b.dataset.record);return;}
  if(b.dataset.compare){compareMode=b.dataset.compare;state.comparison=compareMode;updateUrl(true);renderCompare();return;}
  if(b.hasAttribute('data-more-stops')){stopLimit+=12;drawTransport();return;}
  if(b.hasAttribute('data-reset-search')){$('#search').value='';$('#category').value='all';$('#year').value='all';page=0;renderData();return;}
  if(b.id==='export-brief'){exportBrief();return;}
  if(b.dataset.example){const examples={yufu:['issues','由布市','government','yufu-station'],hiji:['mobility','日出町','facility','hiji-harmony'],beppu:['mobility','別府市','transport','beppu-jigoku']};const [view,area,role,anchor]=examples[b.dataset.example];navigate(view,{area,role,anchor});}
 });
 ['#search','#category','#year'].forEach(id=>$(id).addEventListener(id==='#search'?'input':'change',()=>{page=0;renderData()}));
 $('#prev-page').addEventListener('click',()=>{page--;renderData()});$('#next-page').addEventListener('click',()=>{page++;renderData();$('#record-count').scrollIntoView({block:'start'})});
 $('#export-csv').addEventListener('click',()=>{download(csvFor(filtered(),data.sources),'oita-tourism-data.csv','text/csv;charset=utf-8');toast(filtered().length+'件を出典付きで保存しました。')});
 $('#share').addEventListener('click',async()=>{const url=stateUrl(location.href,state);try{await navigator.clipboard.writeText(url);toast('この画面のURLをコピーしました。検索語は含まれません。')}catch{$('#detail-body').innerHTML='<h2>この画面を共有</h2><p class="footnote">下のURLをコピーして共有してください。</p><input style="width:100%;margin-top:18px" readonly value="'+esc(url)+'">';$('#detail-dialog').showModal()}});
 $('#close-detail').addEventListener('click',()=>$('#detail-dialog').close());$('#detail-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close()}});
 $('#anchor').addEventListener('change',()=>{state.anchor=$('#anchor').value;stopLimit=12;updateUrl(true);drawTransport(true)});$('#map-day').addEventListener('change',()=>{state.day=Number($('#map-day').value);updateUrl(true);drawTransport()});$('#radius').addEventListener('change',()=>{state.radius=Number($('#radius').value);stopLimit=12;updateUrl(true);drawTransport(true)});$('#active-only').addEventListener('change',()=>{stopLimit=12;drawTransport()});
 window.addEventListener('popstate',()=>{state=readState(location.href,data);render()});
}
async function start(){try{const r=await fetch('data/tourism.json');if(!r.ok)throw Error('観光データを取得できませんでした。ページを再読み込みしてください。');data=await r.json();state=readState(location.href,data);$('#area').innerHTML='<option value="all">大分県・６市町</option>'+data.municipalities.map(m=>`<option>${m.name}</option>`).join('');$('#category').innerHTML='<option value="all">すべて</option>'+[...new Set(data.records.map(r=>r.category))].map(c=>`<option>${esc(c)}</option>`).join('');$('#year').innerHTML='<option value="all">すべて</option>'+[...new Set(data.records.map(r=>r.period.slice(0,4)).filter(x=>/^\d{4}$/.test(x)))].sort().reverse().map(y=>`<option value="${y}">${y}年</option>`).join('');wire();$('#loading').hidden=true;render();}catch(e){$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent=e.message;}}
start();
