export const VIEWS=['overview','compare','access','mobility','issues','data','guide'];
export const ROLES={government:{label:'自治体・観光協会',text:'地域の特徴と住民への影響を見て、対策と必要な調査を考える。'},facility:{label:'宿泊・観光施設',text:'来訪者の移動・滞在を見て、周遊や宿泊につながる接続を考える。'},transport:{label:'交通事業者',text:'観光地周辺の乗り場と運行予定を確認し、追加調査の場所を絞る。'}};
export const CITY_INFO={
 '由布市':{en:'YUFU',color:'#2539d9',question:'昼の集中を、時間と場所でほぐす。',note:'年間の客数と、由布院の昼間の混雑は分けて考えます。',metric:'観光客総数',period:'2025年',focus:'車流入・駐車待ち・朝夕の回遊',needs:['時間帯別の中心部への車流入','駐車待ちと住民の所要時間','周辺地区への立ち寄り・消費']},
 '別府市':{en:'BEPPU',color:'#008d94',question:'観光の移動と、市民の移動を両立する。',note:'泊まる地区と、昼間に訪れる地区の移動を確認します。',metric:'総観光客数',period:'2024年',focus:'宿泊地区と観光地の接続・生活交通',needs:['便別の乗車できなかった人数','住民と観光客の利用時間帯','荷物占有・遅延・地獄エリアの駐車待ち']},
 '日出町':{en:'HIJI',color:'#cc592e',question:'施設への来訪を、町内の滞在へ。',note:'施設の集客と、町全体の消費・混雑は別の指標です。',metric:'ハーモニーランド',period:'2026年4/29〜5/6',focus:'駅・テーマパーク・町内体験の接続',needs:['入退園時刻と駐車場の待ち時間','駅からの接続・帰りの移動','町内での飲食・体験・追加消費']},
 '宇佐市':{en:'USA',color:'#80613b',question:'立ち寄りを、食事や体験につなぐ。',note:'過去の日帰り型という診断を、今の行動データで確かめます。',metric:'アフリカンサファリ',period:'2026年4/29〜5/6',focus:'参拝・体験と安心院・院内への周遊',needs:['地点ごとの到着・退出時刻','飲食・体験の購入と営業時間','特定時期の交通集中と帰路']},
 '大分市':{en:'OITA',color:'#5169a9',question:'宿泊・仕事の前後に、地域を楽しむ。',note:'宿泊統計には業務利用も含まれます。目的を分けて考えます。',metric:'県調査の延べ宿泊客数',period:'2025年',focus:'夜間消費・イベント交通・広域周遊',needs:['仕事・観光など目的別の宿泊','夜間の飲食利用と近隣市町への周遊','イベント終了時の交通と待ち時間']},
 '国東市':{en:'KUNISAKI',color:'#578066',question:'空港からの通過を、立ち寄りへ。',note:'指定施設の集計です。空港利用者や市全域の客数とは異なります。',metric:'市指定施設等観光客数',period:'2024年度',focus:'空港からの立ち寄り・帰路・受入容量',needs:['空港から市内への立ち寄り率','帰路の確保・予約が取れない件数','寺社・体験施設の受入上限']}
};
export function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export const number=(n,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:d,minimumFractionDigits:d}):'未取得';
export function displayValue(r,compact=false){
 if(!r||r.value===null||!Number.isFinite(r.value))return {value:'未取得',unit:''};
 const n=r.value,u=r.unit;
 if(u==='割合')return {value:number(n*100,1),unit:'%'};
 if(compact&&u==='円'&&n>=1e8)return {value:number(n/1e8,1),unit:'億円'};
 if(compact&&['人','人回','人泊'].includes(u)&&n>=1e5)return {value:number(n/1e4,1),unit:'万'+u};
 return {value:number(n),unit:u};
}
export function distance(a,b){const rad=Math.PI/180,dlat=(b.lat-a.lat)*rad,dlon=(b.lon-a.lon)*rad;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function nearbyStops(geo,anchor,radius,day,activeOnly=false){return geo.stops.map((s,i)=>({...s,index:i,distance:distance(anchor,s)})).filter(s=>s.distance<=radius&&(!activeOnly||(typeof s.departures[day]==='number'&&s.departures[day]>0))).sort((a,b)=>a.distance-b.distance||a.feedIndex-b.feedIndex||a.id.localeCompare(b.id));}
export function readState(href,data){const u=new URL(href),q=u.searchParams;const anchor=id=>data.anchors.some(a=>a.id===id);const time=(s,f)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(s??'')?s:f;return {view:VIEWS.includes(u.hash.slice(1))?u.hash.slice(1):'overview',comparison:['lodging','gw','monthly','modes'].includes(q.get('compare'))?q.get('compare'):'lodging',area:data.municipalities.some(m=>m.name===q.get('area'))?q.get('area'):'all',role:Object.hasOwn(ROLES,q.get('role'))?q.get('role'):'government',anchor:anchor(q.get('place'))?q.get('place'):data.anchors[0].id,origin:anchor(q.get('from'))?q.get('from'):'beppu-station',departure:time(q.get('at'),'09:00'),deadline:time(q.get('back'),'18:00'),dwell:[60,120,180,240].includes(Number(q.get('stay')))?Number(q.get('stay')):120,maxMinutes:[30,60,90,120].includes(Number(q.get('limit')))?Number(q.get('limit')):90,day:['0','1','2'].includes(q.get('day'))?Number(q.get('day')):0,radius:[500,1000,2000].includes(Number(q.get('radius')))?Number(q.get('radius')):1000};}
export function stateUrl(href,state){const u=new URL(href);u.search='';if(state.area!=='all')u.searchParams.set('area',state.area);if(state.role!=='government')u.searchParams.set('role',state.role);if(['mobility','access'].includes(state.view)){u.searchParams.set('place',state.anchor);u.searchParams.set('day',state.day);u.searchParams.set('radius',state.radius)}if(state.view==='compare')u.searchParams.set('compare',state.comparison??'lodging');if(state.view==='access')for(const [k,v]of Object.entries({from:state.origin,at:state.departure,back:state.deadline,stay:state.dwell,limit:state.maxMinutes}))u.searchParams.set(k,v);u.hash=state.view;return u.href;}
export function filterRecords(records,{area='all',category='all',year='all',query=''}={}){const q=query.trim().toLocaleLowerCase('ja');return records.filter(r=>(area==='all'||r.area===area)&&(category==='all'||r.category===category)&&(year==='all'||r.period.startsWith(year))&&(!q||[r.area,r.metric,r.series,r.period,r.method,r.note].join(' ').toLocaleLowerCase('ja').includes(q)));}
export function csvFor(records,sources){const headers=['地域','対象期間','指標','値','単位','調査系列','対象・方法','注意事項','確認区分','出典','出典URL','原資料の単位'];const sourceMap=new Map(sources.map(s=>[s.id,s]));const cell=v=>{if(v===null||v===undefined)return '';let s=String(v);if(typeof v==='string'&&/^[\s\u0000-\u001f]*[=+\-@＝＋－＠]/u.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return '\ufeff'+[headers,...records.map(r=>[r.area,r.period,r.metric,r.value,r.unit,r.series,r.method,r.note,r.status,sourceMap.get(r.sourceId)?.title??'',r.sourceUrl??'',r.originalUnit??r.unit])].map(row=>row.map(cell).join(',')).join('\r\n');}
export function lodgingComparison(data){return data.municipalities.map(m=>({area:m.name,record:data.records.find(r=>r.area===m.name&&r.period==='2025年'&&r.sourceId==='P02'&&r.metric.includes('宿泊'))??null}));}
