const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const {loadPyodide}=require('pyodide');
const root=path.resolve(__dirname,'../..');
const dir=path.join(root,'danchi-elevator/demo');
const parse=require(path.join(dir,'journey-input.js')).parse;
const stops=[{id:'stop-a',name:'中央広場',active:true},{id:'stop-b',name:'駅前ロータリー',active:true},{id:'stop-c',name:'ふれあいセンター',active:true}];
const checks=[];
function check(name,fn){fn();checks.push(name);}
check('One-sentence Japanese route and full-width passenger count resolve registered stop IDs',()=>assert.deepEqual(parse('中央広場から駅前ロータリーへ２人でお願いします',{stops}).update,{origin:'stop-a',destination:'stop-b',passengers:2}));
check('Passenger-only input preserves the selected route',()=>assert.deepEqual(parse('ふたり',{stops,selection:{origin:'stop-a',destination:'stop-b'},target:'passengers'}).update,{passengers:2}));
check('Unknown location rejects the entire mixed input without guessing',()=>assert.equal(parse('中央病院から駅前へ2人',{stops}).ok,false));
check('Identical origin and destination are rejected across a single input and an existing selection',()=>{assert.equal(parse('中央広場から中央広場へ1人',{stops}).ok,false);assert.equal(parse('中央広場',{stops,selection:{origin:'stop-a'},target:'destination'}).ok,false);});
check('Out-of-range, fractional, negative and conflicting counts are rejected',()=>{for(const text of ['4人','0人','-1人','1.5人','四人','2人と3人'])assert.equal(parse(text,{stops}).ok,false,text);});
check('Suspended stops and ambiguous aliases are not selectable',()=>{assert.equal(parse('駅前',{stops:stops.map(s=>({...s,active:s.id!=='stop-b'}))}).ok,false);assert.equal(parse('駅前',{stops:[...stops,{id:'other',name:'駅前',active:true}]}).ok,false);});
check('Typed OK never creates a booking command',()=>assert.equal(parse('OK',{stops}).ok,false));
check('Explicit destination correction changes only the destination',()=>assert.deepEqual(parse('目的地はふれあいセンター',{stops,selection:{origin:'stop-a',destination:'stop-b'},target:'passengers'}).update,{destination:'stop-c'}));

(async()=>{
  const py=await loadPyodide();await py.loadPackage('tzdata');
  const bundle=JSON.parse(fs.readFileSync(path.join(dir,'core-bundle.json'),'utf8'));
  for(const[name,source]of Object.entries(bundle.files)){py.FS.mkdirTree('/project/'+name.slice(0,name.lastIndexOf('/')));py.FS.writeFile('/project/'+name,source);}
  py.FS.writeFile('/project/demo_runtime.py',fs.readFileSync(path.join(dir,'demo_runtime.py'),'utf8'));py.FS.writeFile('/project/fixtures/browser-seed.json',JSON.stringify(bundle.database_seed));
  py.runPython("import sys;sys.path.insert(0,'/project');from demo_runtime import dispatch_json");
  function dispatch(actor,route,body){py.globals.set('command',JSON.stringify({actor,path:route,method:body===undefined?'GET':'POST',body}));return JSON.parse(py.runPython("dispatch_json('/tmp/journey-ui.sqlite3',command)"));}
  assert.equal(dispatch(null,'/demo/initialize',{}).status,200);
  const dom=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:'https://example.test/danchi-elevator/demo/?role=user',runScripts:'outside-only',pretendToBeVisual:true});
  const w=dom.window;let actor='rider-a1';
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
  w.HTMLElement.prototype.scrollIntoView=function(){};
  w.fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):undefined;if(url==='/api/session'){actor=body.username;url='/api/me';}if(url==='/api/logout'){actor=null;return{ok:true,status:200,json:async()=>({logged_out:true})};}const result=dispatch(actor,url,url==='/api/me'?undefined:body);return{ok:result.status<400,status:result.status,json:async()=>result.data};};
  for(const file of ['journey-input.js','journey.js','operations.js','driver.js','admin.js','app.js'])w.eval(fs.readFileSync(path.join(dir,file),'utf8'));
  const $=id=>w.document.getElementById(id);
  const settle=async()=>{for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));};
  const chat=async text=>{$('journey-chat-input').value=text;$('journey-chat-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();};
  await settle();
  check('Rider starts with no implied route or passenger count',()=>{assert.equal($('journey-confirm').disabled,true);assert.equal($('summary-origin-name').textContent,'未選択');});
  await chat('中央広場から駅前ロータリーへ2人');
  check('Chat selection updates the original confirmation form but does not save a ride',()=>{assert.equal($('origin').value,'stop-a');assert.equal($('destination').value,'stop-b');assert.equal($('passengers').value,'2');assert.equal(dispatch('rider-a1','/api/snapshot').data.rides.length,1);});
  await chat('未登録の病院から駅前へ3人');
  check('Invalid mixed input leaves all previous form values unchanged',()=>{assert.equal($('origin').value,'stop-a');assert.equal($('destination').value,'stop-b');assert.equal($('passengers').value,'2');});
  await chat('<img src=x onerror=alert(1)>');
  check('Chat renders untrusted text without creating markup',()=>assert.equal($('journey-messages').querySelectorAll('img').length,0));
  $('journey-confirm').click();await settle();
  check('Review uses an actual Core draft and still has no booking side effect',()=>{assert.equal($('confirm-dialog').open,true);assert.match($('confirm-details').textContent,/中央広場/);assert.match($('confirm-details').textContent,/2名/);assert.equal(dispatch('rider-a1','/api/snapshot').data.rides.length,1);});
  $('commit').click();await settle();
  let ride=dispatch('rider-a1','/api/snapshot').data.rides.find(r=>r.status==='requested');
  check('Explicit confirmation saves exactly one Core ride and locks new input',()=>{assert.ok(ride);assert.equal(ride.passengers,2);assert.equal($('journey-chat-input').disabled,true);assert.equal($('journey-confirm').disabled,true);});
  $('rides').querySelector('[data-action=change]').click();await settle();await chat('3人');$('journey-confirm').click();await settle();$('commit').click();await settle();
  ride=dispatch('rider-a1','/api/rides/'+ride.id).data;
  check('Existing change flow still edits the saved reservation through a Core draft',()=>assert.equal(ride.passengers,3));
  $('rides').querySelector('[data-action=cancel]').click();await settle();$('commit').click();await settle();
  check('Cancellation releases the composer for a new request and keeps the cancelled record',()=>{assert.equal(dispatch('rider-a1','/api/rides/'+ride.id).data.status,'cancelled');assert.equal($('journey-chat-input').disabled,false);assert.equal($('summary-origin-name').textContent,'未選択');});
  $('demo-roles').querySelector('[data-demo-role="driver-a1"]').click();await settle();
  check('Switching to a driver hides the rider-only map and chat',()=>assert.equal($('journey-panel').hidden,true));
  dom.window.close();
  const result={status:'PASS',count:checks.length,checks,scope:'Node parser + JSDOM UI with the actual Pyodide Core; live map rendering and IndexedDB are checked separately'};
  fs.writeFileSync(path.join(__dirname,'journey-result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
})().catch(error=>{console.error(error);process.exitCode=1;});
