import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultProfile,validateProfile,prepareGapNetwork,measureSupply,activityCriterion,combineDeficits} from '../oita-mobility/gaps/engine.mjs';
const home={lat:33,lon:131},facility={id:'D',name:'目的地',lat:33,lon:131.02};
function fixture(id='F'){return {id,name:id,tables:{stops:[{stop_id:'A',stop_name:'A',stop_lat:'33',stop_lon:'131'},{stop_id:'M',stop_name:'M',stop_lat:'33',stop_lon:'131.001'},{stop_id:'B',stop_name:'B',stop_lat:'33',stop_lon:'131.02'}],routes:[{route_id:'R',route_type:'3'}],trips:[{trip_id:'O',service_id:'S',route_id:'R'},{trip_id:'I',service_id:'S',route_id:'R'}],calendar:[{service_id:'S',start_date:'20260901',end_date:'20260930',monday:'1',tuesday:'1',wednesday:'1',thursday:'1',friday:'1',saturday:'1',sunday:'1'}],calendar_dates:[],stop_times:[['O','A','09:00:00',1],['O','M','09:02:00',2],['O','B','09:20:00',3],['I','B','11:00:00',1],['I','A','11:20:00',2]].map(([trip_id,stop_id,t,seq])=>({trip_id,stop_id,arrival_time:t,departure_time:t,stop_sequence:String(seq),pickup_type:'0',drop_off_type:'0'}))}};}
const profile=()=>({...defaultProfile('44201',['f.zip']),minimumTrips:2,activityOn:true,destinations:['D'],maxWalk:0,totalWalk:0,walkFactor:1});
test('OR and AND preserve unknown rather than treating it as zero',()=>{const cases=[['fail','unknown','fail','unknown'],['pass','unknown','unknown','pass'],['unknown','unknown','unknown','unknown'],['fail','pass','fail','pass'],['pass','pass','pass','pass'],['fail','fail','fail','fail']];for(const[a,b,any,all]of cases){assert.equal(combineDeficits([a,b],'any'),any);assert.equal(combineDeficits([b,a],'any'),any);assert.equal(combineDeficits([a,b],'all'),all);}assert.throws(()=>combineDeficits([]));});
test('one trip at two nearby stops is counted once and equality satisfies threshold',()=>{const p=profile(),n=prepareGapNetwork([fixture()],p.date);const r=measureSupply(n,home,{...p,distanceM:0,minimumTrips:1});assert.equal(r.departures,1);assert.equal(r.criteria[0].state,'pass');assert.equal(r.criteria[1].state,'pass');});
test('only-terminal stop is not a boarding access point',()=>{const f=fixture();f.tables.trips=f.tables.trips.slice(0,1);f.tables.stop_times=f.tables.stop_times.filter(c=>c.trip_id==='O');const p={...profile(),activityOn:false,frequencyOn:false,distanceM:0};const r=measureSupply(prepareGapNetwork([f],p.date),facility,p);assert.equal(r.status,'fail');assert.notEqual(r.nearest?.name,'B');});
test('expired data is not zero service; nearby expired service prevents a deficit conclusion',()=>{const p=profile(),old=fixture('old');old.tables.feed_info=[{feed_start_date:'20260101',feed_end_date:'20260831'}];let r=measureSupply(prepareGapNetwork([old],p.date),home,p);assert.equal(r.departures,null);assert.equal(r.status,'unknown');const far=fixture('far');for(const s of far.tables.stops)s.stop_lon=String(+s.stop_lon+.1);r=measureSupply(prepareGapNetwork([old,far],p.date),home,p);assert.equal(r.criteria[0].state,'unknown');assert.equal(r.criteria[1].state,'unknown');});
test('valid calendar exception means zero recorded departures',()=>{const f=fixture(),p=profile();f.tables.calendar_dates=[{service_id:'S',date:'20260909',exception_type:'2'}];const c=prepareGapNetwork([f],p.date);assert.equal(measureSupply(c,home,p).departures,0);assert.equal(activityCriterion(c,home,[facility],p).state,'fail');});
test('activity needs a return after the stay, not just an outbound trip',()=>{const f=fixture(),p=profile();assert.equal(activityCriterion(prepareGapNetwork([f],p.date),home,[facility],p).state,'pass');f.tables.stop_times[3].arrival_time=f.tables.stop_times[3].departure_time='09:30:00';f.tables.stop_times[4].arrival_time=f.tables.stop_times[4].departure_time='09:50:00';assert.equal(activityCriterion(prepareGapNetwork([f],p.date),home,[facility],p).state,'fail');});
test('unparseable trip times are not interpreted as a lack of service',()=>{const f=fixture(),p=profile();f.tables.stop_times[0].arrival_time='';const c=prepareGapNetwork([f],p.date);assert.equal(measureSupply(c,home,p).criteria[1].state,'unknown');assert.equal(activityCriterion(c,home,[facility],p).state,'unknown');});
test('previous day 25h departure appears at 01h on analysis day',()=>{const f=fixture(),p={...profile(),serviceStart:'00:00',serviceEnd:'04:00',departure:'01:00',deadline:'04:00',activityFrom:'01:30',activityTo:'02:00',dwell:30};for(const c of f.tables.stop_times)c.arrival_time=c.departure_time=String(+c.departure_time.slice(0,2)+16)+c.departure_time.slice(2);const n=prepareGapNetwork([f],p.date);assert.equal(measureSupply(n,home,p).departures,1);assert.equal(activityCriterion(n,home,[facility],p).state,'pass');});
test('invalid profiles and empty criteria cannot be saved as usable rules',()=>{const p=profile();validateProfile(p);assert.throws(()=>validateProfile({...p,distanceOn:false,frequencyOn:false,activityOn:false}));assert.throws(()=>validateProfile({...p,serviceEnd:p.serviceStart}));assert.throws(()=>validateProfile({...p,destinations:[]}));assert.throws(()=>validateProfile({...p,minimumTrips:1.5}));assert.throws(()=>validateProfile({...p,date:'2026-02-30'}));});
