import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseCSV,csvText,zip,unzip} from '../oita-mobility/lab/io.mjs';
import {seconds,clock,activeServices,importGTFS,validateFeeds,scenarioFeeds,buildNetwork,supply,reachability,compareReach,exportFeed} from '../oita-mobility/lab/gtfs.mjs';
import {analyzeRidership,analyzeOD,forecast,demandSensitivity,economics,economicSensitivity,switchingDemand,num} from '../oita-mobility/lab/models.mjs';
function fixture(){return {id:'f1',name:'合成検証データ（実績ではない）',tables:{agency:[{agency_id:'ag',agency_name:'test',agency_timezone:'Asia/Tokyo'}],routes:[{route_id:'R',route_long_name:'test'}],stops:['A','B','C','D'].map((id,i)=>({stop_id:id,stop_name:id,stop_lat:'33',stop_lon:String(131+i*.02)})),trips:[{trip_id:'T',route_id:'R',service_id:'weekday'}],calendar:[{service_id:'weekday',start_date:'20260101',end_date:'20261231',monday:'1',tuesday:'1',wednesday:'1',thursday:'1',friday:'1',saturday:'0',sunday:'0'}],calendar_dates:[],stop_times:['A','B','C','D'].map((id,i)=>({trip_id:'T',stop_id:id,stop_sequence:String(i+1),arrival_time:clock(32400+i*600),departure_time:clock(32400+i*600),pickup_type:'0',drop_off_type:'0'}))},extra:{},emptyFiles:{}}}
const params={origin:'f1::A',departure:32400,budget:3600,maxTransfers:0,maxWalk:0,walkSpeed:4,transferMinutes:3};
function cash(year,values={}){return {year,q0:0,q1:0,time0:0,time1:0,fare0:0,fare1:0,opex0:0,opex1:0,capital:0,replacement:0,decommission:0,residual:0,external:'',...values}}
const opts={baseYear:2026,rate:.04,vot:60};
test('CSV preserves strings, quoted commas/newlines/BOM; malformed rows rejected',()=>{const r=parseCSV('\uFEFFid,name,count\r\n0007,"A, B\nC",0\r\n');assert.equal(r[0].id,'0007');assert.equal(r[0].name,'A, B\nC');assert.deepEqual(parseCSV(csvText(r)),r);assert.throws(()=>parseCSV('a,a\n1,2'));assert.throws(()=>parseCSV('a,b\n1'));assert.throws(()=>parseCSV('a\n"unclosed'));assert(csvText([{name:'＝HYPERLINK(1)'}],{safe:true}).includes("'＝"));assert.throws(()=>num(''));assert.throws(()=>num('12人'));});
test('ZIP CRC and UTF-8 round trip with root filenames',async()=>{const blob=zip({'stops.txt':'stop_id,stop_name\n01,玖珠\n','NOTICE':'retain'}),entries=await unzip(await blob.arrayBuffer());assert.equal(new TextDecoder().decode(entries['NOTICE']),'retain');const bytes=new Uint8Array(await blob.arrayBuffer());bytes[40]^=1;await assert.rejects(()=>unzip(bytes.buffer));});
test('Calendar exceptions add and remove independently of weekly calendar',()=>{const f=fixture();f.tables.calendar_dates=[{service_id:'weekday',date:'20260908',exception_type:'2'},{service_id:'special',date:'20260908',exception_type:'1'}];assert.deepEqual([...activeServices(f.tables,'2026-09-08')],['special']);f.tables.calendar=[];assert(activeServices(f.tables,'20260908').has('special'));});
test('Time parser preserves 24+ hours and rejects invalid minutes',()=>{assert.equal(seconds('25:10:00'),90600);assert.equal(clock(90600),'25:10:00');assert.equal(seconds('24:61:00'),null);});
test('Edits are isolated and change supply/export data without changing original',()=>{const f=fixture(),edited=scenarioFeeds([f],[{type:'duplicate',feed:'f1',trip:'T',newId:'T2',minutes:10}])[0];assert.equal(f.tables.trips.length,1);assert.equal(edited.tables.trips.length,2);assert.equal(supply(buildNetwork([edited],'20260908')).trips,2);assert.equal(edited.tables.stop_times.find(s=>s.trip_id==='T2').departure_time,'09:10:00');assert.throws(()=>scenarioFeeds([f],[{type:'shift',feed:'f1',trip:'T',minutes:-600}]));});
test('Supply distinguishes first departures from through-stop calls in window',()=>{const f=fixture();f.tables.stop_times.forEach((r,i)=>{r.arrival_time=r.departure_time=clock(7*3600+i*1800)});const r=supply(buildNetwork([f],'20260908'),{start:8*3600,end:9*3600});assert.equal(r.trips,0);assert.equal(r.byStop['f1::C'].departures,1);assert.equal(r.byStop['f1::D'].departures,1);});
test('Interior pickup prohibition blocks boarding but allows passengers already onboard',()=>{const f=fixture();f.tables.stop_times[1].pickup_type='1';const n=buildNetwork([f],'20260908');assert(reachability(n,params).best['f1::D']);const r=reachability(n,{...params,origin:'f1::B'});assert.equal(r.best['f1::D'],undefined);});
test('No-op reach comparison has no artificial gains/losses',()=>{const n=buildNetwork([fixture()],'20260908'),a=reachability(n,params),b=reachability(n,params);assert(compareReach(a,b,n.stops).every(r=>r.change==='変化なし'));});
test('Previous service day 25-hour trip is available after civil midnight',()=>{const f=fixture();f.tables.stop_times.forEach((r,i)=>r.arrival_time=r.departure_time=clock(25*3600+i*600));const n=buildNetwork([f],'20260909'),r=reachability(n,{...params,departure:3600,budget:3600});assert.equal(r.best['f1::D'].arrival,5400);});
function transferFixture(secondsGap=180){const f=fixture();f.tables.trips.push({trip_id:'T2',route_id:'R',service_id:'weekday'});f.tables.stop_times=f.tables.stop_times.slice(0,2);f.tables.stop_times.push({trip_id:'T2',stop_id:'B',stop_sequence:'1',arrival_time:clock(33000+secondsGap),departure_time:clock(33000+secondsGap),pickup_type:'0',drop_off_type:'0'},{trip_id:'T2',stop_id:'D',stop_sequence:'2',arrival_time:'09:40:00',departure_time:'09:40:00',pickup_type:'0',drop_off_type:'0'});f.tables.transfers=[{from_stop_id:'B',to_stop_id:'B',transfer_type:'2',min_transfer_time:'180'}];return f}
test('Transfer minimum 180 seconds: 179 fails, 180 succeeds',()=>{assert(!reachability(buildNetwork([transferFixture(179)],'20260908'),{...params,maxTransfers:1}).best['f1::D']);assert(reachability(buildNetwork([transferFixture(180)],'20260908'),{...params,maxTransfers:1}).best['f1::D']);});
test('Explicit transfer prohibition is honored',()=>{const f=transferFixture();f.tables.transfers[0].transfer_type='3';assert(!reachability(buildNetwork([f],'20260908'),{...params,maxTransfers:1}).best['f1::D']);});
test('Later arrival retains a permissible transfer when earlier arrival is prohibited',()=>{const f=transferFixture(300);f.tables.trips.push({trip_id:'LATER',route_id:'R',service_id:'weekday'});f.tables.stop_times.push({trip_id:'LATER',stop_id:'A',stop_sequence:'1',arrival_time:'09:00:00',departure_time:'09:00:00',pickup_type:'0',drop_off_type:'0'},{trip_id:'LATER',stop_id:'B',stop_sequence:'2',arrival_time:'09:12:00',departure_time:'09:12:00',pickup_type:'0',drop_off_type:'0'});f.tables.transfers=[{from_stop_id:'B',to_stop_id:'B',from_trip_id:'T',to_trip_id:'T2',transfer_type:'3'},{from_stop_id:'B',to_stop_id:'B',from_trip_id:'LATER',to_trip_id:'T2',transfer_type:'2',min_transfer_time:'180'}];assert(reachability(buildNetwork([f],'20260908'),{...params,maxTransfers:1}).best['f1::D']);});
test('Trip deletion clears ancillary references; restricted clone is rejected',()=>{const f=transferFixture();f.tables.transfers[0].from_trip_id='T';f.tables.translations=[{table_name:'trips',record_id:'T',field_name:'trip_headsign',language:'en',translation:'Test'}];const c=scenarioFeeds([f],[{type:'cancel',feed:'f1',trip:'T'}])[0];assert.equal(validateFeeds([c]).errors,0);assert.equal(c.tables.transfers.length,0);assert.equal(c.tables.translations.length,0);assert.throws(()=>scenarioFeeds([f],[{type:'duplicate',feed:'f1',trip:'T',newId:'NEW',minutes:10}]));});
test('Exact frequency expands headways with exclusive end; nonexact excludes',()=>{const f=fixture();f.tables.frequencies=[{trip_id:'T',start_time:'09:00:00',end_time:'10:00:00',headway_secs:'1200',exact_times:'1'}];const n=buildNetwork([f],'20260908');assert.equal(n.trips.length,3);assert.deepEqual(n.trips.map(t=>t.calls[0].departure),[32400,33600,34800]);f.tables.frequencies[0].exact_times='0';assert.equal(buildNetwork([f],'20260908').trips.length,0);});
test('Real Kusu, Yufu date-only and highway feeds pass and round trip',async()=>{for(const file of ['440001_gtfs06_kusukanko__d99bc99a.zip','440001_gtfs11_communitybus__9b537213.zip','440001_gtfs10_highwaybus__5713d7c2.zip']){const bytes=fs.readFileSync(new URL('../oita-mobility/data/gtfs/'+file,import.meta.url)),f=await importGTFS(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),file,'f1');assert.equal(validateFeeds([f]).errors,0);const copy=await importGTFS(await exportFeed(f).arrayBuffer(),file,'f1');assert.equal(f.tables.trips.length,copy.tables.trips.length);assert.equal(f.tables.stop_times.length,copy.tables.stop_times.length);assert.deepEqual(f.tables.stop_times,copy.tables.stop_times);assert.equal(supply(buildNetwork([f],'20260908')).trips,supply(buildNetwork([copy],'20260908')).trips)}});
const meta={source:'合成テスト',from:'2026-09-08',to:'2026-09-08',scope:'T全停車',basis:'observed',complete:'yes',initialEmpty:'yes',finalEmpty:'yes',unit:'legs'};
function counts(){return ['A','B','C','D'].map((id,i)=>({service_date:'2026-09-08',feed_id:'f1',trip_id:'T',stop_sequence:String(i+1),stop_id:id,boardings:String([10,10,0,0][i]),alightings:String([0,0,10,10][i])}))}
test('Ridership joins and validates full-trip segment loads',()=>{const r=analyzeRidership(counts(),[fixture()],meta);assert.equal(r.boardings,20);assert.equal(r.loads[0].peak,20);assert.deepEqual(r.loads[0].series.map(s=>s.load),[10,20,10,0]);assert.equal(r.unmatched.length,0);});
test('Partial, negative and duplicate records cannot imply valid peak loads',()=>{assert.equal(analyzeRidership(counts().slice(0,3),[fixture()],meta).loads[0].peak,null);const c=counts();c[0].alightings='11';assert.equal(analyzeRidership(c,[fixture()],meta).loads[0].peak,null);const dup=counts();dup.push(dup[0]);assert.equal(analyzeRidership(dup,[fixture()],meta).unmatched.length,1);const mismatch=counts();mismatch[0].stop_id='D';assert.equal(analyzeRidership(mismatch,[fixture()],meta).unmatched.length,1);});
test('Observed zero, suppressed and missing OD cells remain distinct',()=>{const rows=[{origin_feed_id:'f1',origin_stop_id:'A',destination_feed_id:'f1',destination_stop_id:'B',count:'0',status:'observed'},{origin_feed_id:'f1',origin_stop_id:'A',destination_feed_id:'f1',destination_stop_id:'C',count:'',status:'suppressed'}],r=analyzeOD(rows,[fixture()],meta);assert.equal(r.cells[0].count,0);assert.equal(r.cells[1].count,null);assert.equal(r.cells.length,2);assert.equal(r.suppressed,1);});
test('Yearly backtesting is rolling and future observations do not leak',()=>{const rows=Array.from({length:8},(_,i)=>({period:String(2018+i),value:100+i*10})),r=forecast(rows);assert.equal(r.scores.trend,0);assert.equal(r.folds[0].trend,130);rows[7].value=100000;assert.equal(forecast(rows).folds[0].trend,130);assert.throws(()=>forecast([{period:'2020',value:1},{period:'2022',value:3}]));});
test('Monthly seasonal baseline and trend handle seasonality, require contiguous data',()=>{const rows=Array.from({length:36},(_,i)=>({period:`${2020+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}`,value:100+i%12})),r=forecast(rows,'monthly',12);assert.equal(r.scores.baseline,0);assert.equal(r.scores.trend,0);assert.equal(r.chosen,'baseline');assert.equal(r.future[0].baseline,100);});
test('Demand range reverses elasticity ordering on cuts; zero supply is explicit',()=>{const r=demandSensitivity({baseline:100,f0:10,f1:5,elasticities:[.1,.7]});assert(Math.abs(r.low-61.5572206672)<1e-8);assert(Math.abs(r.high-93.3032991537)<1e-8);assert.equal(demandSensitivity({baseline:100,f0:0,f1:5}).available,false);assert.equal(demandSensitivity({baseline:100,f0:10,f1:0}).cancelled,true);assert(demandSensitivity({baseline:100,f0:10,f1:10}).values.every(r=>r.demand===100));});
test('Trapezoid benefit values generated demand at half, keeps adverse time',()=>{const r=economics([cash(2026,{q0:300000,q1:360000,time0:20,time1:10,capital:1})],opts);assert.equal(r.pvUser,198000000);assert.equal(economics([cash(2026,{q0:100,q1:100,time0:10,time1:20})],opts).pvUser,-60000);});
test('Year-end discount and zero/negative incremental resource cost',()=>{const r=economics([cash(2026,{capital:100}),cash(2027,{external:104})],opts);assert(Math.abs(r.bc-1)<1e-12);assert(Math.abs(r.npv)<1e-12);assert.equal(economics([cash(2026)],opts).bc,null);const n=economics([cash(2026,{opex0:100,opex1:0,external:-30})],opts);assert.equal(n.npv,70);assert.equal(n.resourceBC,null);});
test('Fare effects cancel at fixed demand; B/C conventions preserve NPV',()=>{const r=economics([cash(2026,{q0:300000,q1:300000,time0:20,time1:20,fare0:100,fare1:150,capital:100,opex0:1000,opex1:1100})],opts);assert.equal(r.pvUser,-15000000);assert.equal(r.pvProvider,14999900);assert.equal(r.npv,-200);assert.equal(r.resourceBenefit-r.resourceCost,r.npv);});
test('Sensitivity recalculates revenues and demand switch point has NPV zero',()=>{const rows=[cash(2026,{capital:100000}),cash(2027,{q0:1000,q1:1100,time0:20,time1:10,fare0:200,fare1:200,opex0:10000,opex1:20000})],r=switchingDemand(rows,opts);assert(r);assert(Math.abs(r.npv)<1e-7);assert.equal(economicSensitivity(rows,opts).length,9);assert(economics(rows,opts).externalUnassessed);});
