import {renderDataUsed} from '../catalog/data-used.mjs?v=2';
import {GAP_VERSION,STATES,defaultProfile,validateProfile} from './engine.mjs';
import {csvText} from '../lab/io.mjs';
import {publicGapProfile} from '../assets/share-state.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=0)=>Number.isFinite(v)?v.toLocaleString('ja-JP',{maximumFractionDigits:d}):'未確認';
const clock=v=>Number.isFinite(v)?`${String(Math.floor(v/3600)).padStart(2,'0')}:${String(Math.floor(v/60)%60).padStart(2,'0')}`:'—';
const colors={fail:'#c53635',pass:'#237b92',unknown:'#788491'};
const kinds={school:'学校・大学・教習所',medical:'病院送迎',welfare:'福祉・介護',commercial:'商業・企業',tourism:'観光・ホテル',community:'地域交通'};
const marks={school:'学',medical:'医',welfare:'福',commercial:'商',tourism:'宿',community:'地'};
const useText={yes:'一般利用の案内あり',conditional:'条件付き・利用者限定',restricted:'利用者限定',unknown:'一般利用は未確認'};
const safeLink=(u,label)=>/^https?:\/\//.test(u??'')?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label);
const STORAGE='fukuoka-gaps-profiles-v1';
const ids={name:'profile-name',date:'date',note:'profile-note',combine:'combine',resolution:'resolution',populatedOnly:'populated-only',distanceOn:'distance-on',distanceM:'distance-m',frequencyOn:'frequency-on',frequencyRadius:'frequency-radius',minimumTrips:'minimum-trips',serviceStart:'service-start',serviceEnd:'service-end',activityOn:'activity-on',destinationRule:'destination-rule',departure:'departure',deadline:'deadline',activityFrom:'activity-from',activityTo:'activity-to',dwell:'dwell',legMinutes:'leg-minutes',maxWalk:'max-walk',totalWalk:'total-walk',walkSpeed:'walk-speed',walkFactor:'walk-factor',transfers:'transfers',activityScope:'activity-scope'};
const numbers=new Set(['resolution','distanceM','frequencyRadius','minimumTrips','dwell','legMinutes','maxWalk','totalWalk','walkSpeed','walkFactor','transfers']);
let catalog=[],boundaries,places=[],resources=[],custom=[],transport,geoSources,cityCode='40206',drafts={},saved={},map,boundaryLayer,gridLayer,stopLayer,resourceLayer,poiLayer,pickLayer;
let cells=[],gridCache=new Map(),layers=new Map(),results=new Map(),worker=null,job=0,loadJob=0,busy=false,dirty=true,applied=null,health=[],excluded=0,activityCount=0,selectedCell=null,pickPoint=null,picking=false,refreshTimer=null;
const city=()=>boundaries?.features.find(f=>f.properties.code===cityCode);
const cityName=()=>city()?.properties.name??'';
const standardFiles=()=>catalog.filter(f=>f.analysisReady&&f.current).map(f=>f.file);
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('データを読み込めません：'+url);return r.json();}
function error(e){const message=e.message??String(e);$('#error').hidden=false;$('#error').textContent=message;$('#status').textContent='確認が必要です：'+message;}
function clearError(){$('#error').hidden=true;}
function guard(fn){return (...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>{if(busy)cancel(false);error(e);});}
function on(s,event,fn){$(s).addEventListener(event,guard(fn));}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function selectedFeeds(){return $$('#feed-list input:checked').map(e=>e.value);}
function readProfile(){const p=defaultProfile(cityCode,selectedFeeds());for(const [k,id]of Object.entries(ids)){const el=$('#'+id);if(el.type==='checkbox')p[k]=el.checked;else if(numbers.has(k)){if(el.value==='')throw Error('数値の空欄を確認してください');p[k]=Number(el.value);}else p[k]=el.value;}p.destinations=[...$('#destination').selectedOptions].map(x=>x.value);p.files=selectedFeeds();return validateProfile(p);}
function fillProfile(p){for(const [k,id]of Object.entries(ids)){const el=$('#'+id);if(el.type==='checkbox')el.checked=p[k];else el.value=p[k];}for(const el of $$('#feed-list input'))el.checked=p.files.includes(el.value);for(const o of $('#destination').options)o.selected=p.destinations.includes(o.value);$('#saved-label').textContent=saved[cityCode]?'この端末に保存済み':'未保存';$('#profile-state').textContent=p.name+' · '+cityName();}
function validateFiles(p){if(p.files.some(x=>!catalog.some(f=>f.file===x)))throw Error('収録外の交通データが設定されています');if(p.destinations.some(x=>!places.some(f=>f.id===x)))throw Error('収録外の目的地が設定されています');if(!boundaries.features.some(f=>f.properties.code===p.cityCode))throw Error('対象外の自治体です');return validateProfile(p);}
function setBusy(v){busy=v;$('#run').disabled=v;$('#cancel').hidden=!v;$('#progress').hidden=!v;if(v)$('#progress').value=0;}
function cancel(keep=true){job++;worker?.terminate();worker=null;setBusy(false);if(keep){$('#status').textContent='計算を中止しました。未計算の区域は灰色です。';refresh();}}
function invalidate(){if(busy)cancel(false);dirty=true;applied=null;results.clear();health=[];excluded=0;activityCount=0;for(const l of layers.values())l.setStyle(cellStyle('unknown'));$('#saved-label').textContent='変更あり';$('#profile-state').textContent='条件を変更しました。「この条件で地図を更新」を押してください。';$('#status').textContent='条件を変更しました。再計算してください。';$('.scope-note').classList.add('stale');refresh();}
function cellStyle(state){return {color:colors[state],weight:.7,fillColor:colors[state],fillOpacity:state==='fail' ? .56 : state==='pass' ? .28 : .2};}
function drawGrid(){gridLayer.clearLayers();layers.clear();for(const f of cells){const l=L.geoJSON(f,{style:cellStyle(results.get(f.id)?.status??'unknown'),onEachFeature:(_,layer)=>layer.on('click',()=>{if(!picking)selectCell(f.id);})}).addTo(gridLayer);layers.set(f.id,l);}refresh();}
async function loadCells(p){const key=cityCode+'-'+p.resolution;const epoch=++loadJob;if(!gridCache.has(key))gridCache.set(key,await json('gaps/data/'+key+'.geojson'));if(epoch!==loadJob)return false;cells=gridCache.get(key).features.filter(f=>!p.populatedOnly||f.properties.populated2020);drawGrid();return true;}
function mapBounds(){const b=map.getBounds();return {south:b.getSouth(),north:b.getNorth(),west:b.getWest(),east:b.getEast()};}
function fitCity(){if(boundaryLayer.getLayers().length)map.fitBounds(boundaryLayer.getBounds(),{padding:[18,18]});}
async function switchCity(code,auto=true,override=null){
  if(busy)cancel(false);try{drafts[cityCode]=readProfile();}catch{}
  cityCode=code;picking=false;pickPoint=null;pickLayer?.clearLayers();$('#resource-position').textContent='位置：未指定';$('#municipality').value=code;const p=override??drafts[code]??saved[code]??defaultProfile(code,standardFiles());validateFiles(p);fillProfile(p);
  selectedCell=null;results.clear();applied=null;dirty=true;health=[];activityCount=0;boundaryLayer.clearLayers();boundaryLayer.addData(city());fitCity();renderResources();renderStops();renderPois();
  if(!await loadCells(p))return;
  if(auto&&!p.activityOn)await run();else $('#status').textContent='条件を確認して「この条件で地図を更新」を押してください。';
}
async function run(){
  if(busy)return;clearError();const p=validateFiles(readProfile());setBusy(true);const myJob=++job;
  try{
    if(!await loadCells(p)||myJob!==job)return;
    applied={profile:structuredClone(p),bounds:p.activityOn&&p.activityScope==='view'?mapBounds():null,startedAt:new Date().toISOString(),finishedAt:null,complete:false};dirty=false;results.clear();health=[];activityCount=0;drawGrid();$('.scope-note').classList.remove('stale');$('#status').textContent='交通データを準備しています…';$('#profile-state').textContent=p.name+' · '+cityName();
    if(!cells.length){setBusy(false);applied.complete=true;applied.finishedAt=new Date().toISOString();$('#status').textContent='この絞り込みに該当する区域はありません。';refresh();return;}
    if(!worker)worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});
    worker.onerror=()=>{if(myJob===job){cancel(false);error(Error('計算を完了できませんでした。範囲を絞って再実行してください。'));}};
    worker.onmessage=({data})=>{
      if(data.id!==job)return;
      if(data.error){cancel(false);error(Error(data.error));refresh();return;}
      if(data.health){health=data.health;excluded=data.excluded;renderHealth();}
      if(data.progress){$('#status').textContent=data.progress;$('#progress').value=data.percent;}
      if(data.batch){for(const r of data.batch){results.set(r.id,r);layers.get(r.id)?.setStyle(cellStyle(r.status));}activityCount=data.activityCount;if(!refreshTimer)refreshTimer=setTimeout(()=>{refreshTimer=null;refresh();},250);}
      if(data.done){setBusy(false);applied.complete=true;applied.finishedAt=new Date().toISOString();activityCount=data.activityCount;$('#status').textContent=fmt(data.total)+'区域の判定が完了しました。'+(p.activityOn?' 往復は'+fmt(activityCount)+'区域を計算。':'');refresh();}
    };
    worker.postMessage({id:myJob,profile:p,files:catalog.filter(f=>p.files.includes(f.file)),cells:cells.map(f=>f.properties),facilities:places.filter(f=>p.destinations.includes(f.id)),activityBounds:applied.bounds});
  }catch(e){if(myJob===job){cancel(false);throw e;}}
}
function updateDataUsed(){const p=applied?.profile;renderDataUsed('#gap-data-used',{kind:'gaps',mode:p&&health.length?'result':'selection',sources:health.length?health:catalog.filter(f=>(p?.files??selectedFeeds()).includes(f.file)),facilityIds:p?.activityOn?p.destinations:[],includeBoundary:true,includePopulation:p?.populatedOnly??$('#populated-only').checked,date:p?.date??$('#date').value,health,complete:applied?.complete??false});}
function statistics(){const out={fail:{count:0,area:0},pass:{count:0,area:0},unknown:{count:0,area:0}};for(const f of cells){const g=out[results.get(f.id)?.status??'unknown'];g.count++;g.area+=f.properties.areaKm2;}return out;}
function refresh(){
  updateDataUsed();
  const stats=statistics();$('#metrics').innerHTML=['fail','pass','unknown'].map(s=>`<div><span>${STATES[s]}</span><b>${dirty?'—':fmt(stats[s].count)}<span class="metric-unit">区域</span></b><small>区域面積 ${dirty?'—':fmt(stats[s].area,2)} km²</small></div>`).join('');
  $('#map-title').textContent=cityName()+' · '+fmt(cells.length)+'区域';
  const p=applied?.profile;$('#result-summary').textContent=p?`${p.date} ／ ${p.name} ／ ${p.combine==='any'?'どれか1つが不足':'すべてが不足'}`:'条件を確認して、地図に反映してください';
  $('#scope-caption').textContent=dirty?'条件を変更しました。「この条件で地図を更新」を押すと、区域数・面積・判定を再計算します。':(p?.populatedOnly?'2020年基準人口のあるメッシュに限定。':'行政界内全域（山林等を含む）。')+'区域内代表点の判定です。赤は収録バスデータで条件に該当する確認候補、灰はデータ不足・未計算。面積は困っている住民数を表しません。'+(p?.activityOn?` 往復を調べた区域：${fmt(activityCount)} / ${fmt(cells.length)}。`:'')+(applied&&!applied.complete&&!busy?' 計算は未完了です。':'');
  if(selectedCell)selectCell(selectedCell,false);
}
function renderHealth(){updateDataUsed();$('#data-health').innerHTML=health.map(h=>`<p>${esc(h.name)}：${h.coverage==='known'?'対象日は有効期間内':h.coverage==='outside'?'対象日は有効期間外':'有効期間を確認できない'}</p>`).join('')+(excluded?`<p>時刻等の理由で算定対象外の便：${fmt(excluded)}件。不足の判定には未確認を残します。</p>`:'');}
function criterionHTML(c){return `<div class="criterion-result"><b>${esc(c.label)} <span class="status-badge ${c.state}">${c.state==='fail'?'不足候補':c.state==='pass'?'条件内':'判定できない'}</span></b>${esc(c.reason)}${c.id==='distance'?`<br>最短 ${c.value===null?'未確認':fmt(c.value)+'m'} ／ 上限 ${fmt(c.threshold)}m`:c.id==='frequency'?`<br>${fmt(c.value)}便 ／ 必要 ${fmt(c.threshold)}便`:''}${c.details?c.details.map(d=>`<p>${esc(d.name)}：${d.state==='pass'?'往復候補あり・帰宅 '+clock(d.homeAt):d.state==='fail'?'設定条件で候補なし':'確認不足'}<br><small>${esc(d.reasons.join(' / ')||d.unknowns.join(' / '))}</small></p>`).join(''):''}</div>`;}
function selectCell(id,move=false){
  const f=cells.find(x=>x.id===id);if(!f)return;selectedCell=id;const p=f.properties,r=results.get(id),state=r?.status??'unknown';
  $('#cell-detail').innerHTML=`<h2>${esc(cityName())} · 区域 ${esc(p.meshCode)}</h2><span class="status-badge ${state}">${STATES[state]}</span><p>区域内代表点 ${p.lat.toFixed(5)}, ${p.lon.toFixed(5)} ／ 面積 ${fmt(p.areaKm2,3)} km²</p><div class="detail-grid"><div><span>最寄りの収録バス停</span><b>${r?.nearest?fmt(r.nearest.meters)+' m':'未確認'}</b><span>${esc(r?.nearest?.name??'未計算・有効データなし')}</span></div><div><span>時間帯内の乗車便数</span><b>${r?fmt(r.departures)+' 便':'未計算'}</b><span>データ内の同一便は1回集計</span></div></div>${r?r.criteria.map(criterionHTML).join(''):'<p>この区域はまだ判定していません。</p>'}<p>2020年基準人口（国交省調整値）：${p.population2020===null?'境界またぎ・収録外等のため未集計':fmt(p.population2020,1)+'人'}。区域全員が交通空白とは限りません。</p>${r?.nearby?.length?`<details><summary>乗車便がある近隣のバス停</summary>${r.nearby.map(s=>`<p>${esc(s.name)}：${fmt(s.meters)}m、乗車時刻 ${fmt(s.departures)}件</p>`).join('')}<p>上の件数は各停留所の時刻数。区域全体の便数は同一データ内で重複を除いています。</p></details>`:''}<a class="button" href="accessibility.html">目的地マップで用事の条件も確認</a>`;
  if(move)map.setView([p.lat,p.lon],Math.max(14,map.getZoom()));
}
function renderStops(){stopLayer.clearLayers();if(!transport)return;const b=boundaryLayer.getBounds().pad(.12),chosen=new Set(catalog.filter(f=>selectedFeeds().includes(f.file)).map(f=>f.sha256));for(const s of transport.stops){if(!chosen.has(transport.feeds[s.feedIndex]?.sha256))continue;const lat=s.lat??s.latitude??s.p?.[0],lon=s.lon??s.lng??s.longitude??s.p?.[1];if(!Number.isFinite(lat)||!Number.isFinite(lon)||!b.contains([lat,lon]))continue;L.circleMarker([lat,lon],{radius:3,color:'#1e576e',weight:1,fillOpacity:.8}).bindPopup(`<b>${esc(s.name)}</b><br>収録されたバス停の位置。日別の運行・乗車条件は判定で確認。`).addTo(stopLayer);}}
function renderPois(){poiLayer.clearLayers();const b=boundaryLayer.getBounds().pad(.05);for(const p of places)if(b.contains([p.lat,p.lon]))L.circleMarker([p.lat,p.lon],{radius:4,color:p.category==='hospital'?'#ac4460':'#286b60',fillOpacity:.8,weight:1}).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.address)}<br>${safeLink(p.sourceUrl,'所在地の出典')}`).addTo(poiLayer);}
function allResources(){return [...resources,...custom];}
function filteredResources(){return allResources().filter(r=>r.city===cityName()&&($('#resource-type').value==='all'||r.category===$('#resource-type').value)&&($('#resource-use').value==='all'||(r.generalUse==='restricted'?'conditional':r.generalUse)===$('#resource-use').value));}
function hasPosition(r){return Number.isFinite(r.lat)&&Number.isFinite(r.lon);}
function resourceHTML(r,actions=true){return `<div class="resource-card" data-resource-card="${esc(r.id)}"><span class="kind" style="--dot:#b27609">${esc(kinds[r.category]??r.category)} · ${r.userAdded?'自治体の登録':'公表資料'}</span><h3>${esc(r.name)}</h3><span class="status-badge ${r.serviceStatus==='suspended'?'unknown':'pass'}">${r.serviceStatus==='suspended'?'休止中':r.userAdded?'登録内容・現況は要確認':'送迎等の公表あり・現況は要確認'}</span><p><b>${esc(useText[r.generalUse]??'一般利用は未確認')}</b><br>${esc(r.eligibleUsers)}</p><p>${esc(r.provider)}</p><details ${actions?'':'open'}><summary>運行条件・台数・確認元を見る</summary><p>台数：${r.vehicleCount===null||r.vehicleCount===undefined?'未確認':fmt(r.vehicleCount)+'台'} ／ ${esc(r.capacityNote??'定員は未確認')}</p><p>${esc(r.operatingPeriod??'運行日・時間は未確認')}<br>${esc(r.reservationNote??'予約条件は未確認')}</p>${r.potential?`<p>活用可能性（登録情報）：${esc(r.potential)}</p>`:'<p>地域での共用・空き時間：未確認</p>'}<p class="small-note">${hasPosition(r)?esc(r.positionNote):'地図位置は未確認。サービスの不存在を意味しません。'}<br>確認日 ${esc(r.checkedAt)} ／ ${safeLink(r.sourceUrl,'サービスの出典')}${r.sourceText?' · '+esc(r.sourceText):''}</p></details>${actions?`<div class="row-actions">${hasPosition(r)?`<button class="button" data-show-resource="${esc(r.id)}">${r.locationType==='administrative_office'?'担当窓口を地図で見る':'施設の位置を見る'}</button>`:''}${r.userAdded?`<button class="button quiet" data-delete-resource="${esc(r.id)}">登録を削除</button>`:''}</div>`:''}</div>`;}
function renderResources(){
  resourceLayer.clearLayers();const list=filteredResources(),located=list.filter(hasPosition);$('#resource-count').textContent=`${cityName()}：公表・登録 ${list.length}サービス ／ 位置あり ${located.length} ／ 休止中 ${list.filter(r=>r.serviceStatus==='suspended').length}。県全体の収録事例 ${resources.length}件。`;
  $('#resource-list').innerHTML=list.length?list.map(r=>resourceHTML(r)).join(''):'<p class="help">この条件の公表事例は未収録です。地域に送迎車がないという意味ではありません。下から調査した資源を登録できます。</p>';
  for(const r of located){const icon=L.divIcon({className:'',html:`<span class="resource-pin ${esc(r.category)}" style="${r.serviceStatus==='suspended'?'background:#777;':''}${r.locationType==='administrative_office'?'border-style:dashed;':''}">${marks[r.category]??'車'}</span>`,iconSize:[26,26],iconAnchor:[13,13]});L.marker([r.lat,r.lon],{icon,title:r.name}).bindPopup(`<b>${esc(r.name)}</b><br>${r.serviceStatus==='suspended'?'<strong>休止中</strong><br>':''}${esc(useText[r.generalUse]??'未確認')}<br>${esc(r.eligibleUsers)}<br>${esc(r.positionNote)}<br>${safeLink(r.sourceUrl,'運行・利用条件の出典')}`,{maxWidth:330}).addTo(resourceLayer);}
  for(const e of $$('[data-show-resource]'))e.addEventListener('click',()=>{const r=list.find(x=>x.id===e.dataset.showResource);$('#show-resources').checked=true;map.addLayer(resourceLayer);map.setView([r.lat,r.lon],15);$('#map-tip').textContent=r.name+'：'+r.positionNote;});
  for(const e of $$('[data-delete-resource]'))e.addEventListener('click',()=>{custom=custom.filter(r=>r.id!==e.dataset.deleteResource);renderResources();});
}
function setTab(name){for(const e of $$('[data-tab]')){const active=e.dataset.tab===name;e.classList.toggle('active',active);e.setAttribute('aria-pressed',String(active));}$('#panel-criteria').hidden=name!=='criteria';$('#panel-resources').hidden=name!=='resources';}
function addResource(event){event.preventDefault();if(!pickPoint)throw Error('地図で施設・乗降拠点を指定してください');if(pickPoint.lat<32||pickPoint.lat>34||pickPoint.lon<130||pickPoint.lon>133)throw Error('福岡県周辺の施設・乗降拠点を指定してください');const optionalNumber=(id,min,max)=>{const v=$(id).value;if(v==='')return null;const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw Error('台数・定員を確認してください');return n;};const name=$('#resource-name').value.trim(),users=$('#resource-users').value.trim(),source=$('#resource-source').value.trim();if(!name||!users||!source)throw Error('名前・利用条件・確認元を入力してください');const r={id:'local-'+crypto.randomUUID(),userAdded:true,city:cityName(),name,provider:$('#resource-operator').value,category:$('#new-resource-type').value,...pickPoint,locationType:'facility',positionNote:'自治体が地図に登録した施設・乗降拠点。車両の現在位置や運行区域ではありません。',serviceStatus:'unknown',eligibleUsers:users,generalUse:$('#new-resource-use').value,operatingPeriod:$('#resource-schedule').value||'未確認',reservationNote:'予約条件は上記の登録内容を確認',potential:$('#resource-potential').value,vehicleCount:optionalNumber('#resource-vehicles',0,10000),capacityNote:$('#resource-capacity').value?optionalNumber('#resource-capacity',1,1000)+'人／台（登録値）':'定員は未確認',sourceUrl:/^https?:\/\//.test(source)?source:null,sourceText:source,checkedAt:$('#resource-date').value};custom.push(r);$('#resource-form').reset();$('#resource-date').value=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});pickPoint=null;pickLayer.clearLayers();$('#resource-position').textContent='位置：未指定';renderResources();$('#map-tip').textContent='資源を登録しました。「設定・登録資源を保存」で別端末へ渡せます。';}
function encode(p){const bytes=new TextEncoder().encode(JSON.stringify(p));return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function decode(s){if(s.length>14000)throw Error('共有条件が大きすぎます');const b=atob(s.replaceAll('-','+').replaceAll('_','/'));return JSON.parse(new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0))));}
async function share(){const p=publicGapProfile(readProfile()),u=new URL(location.href);u.search='';u.hash='conditions='+encode(p);try{await navigator.clipboard.writeText(u.href);$('#profile-state').textContent='条件のURLをコピーしました。条件名・自由記述・追加した資源は含みません。';}catch{window.prompt('このURLをコピーしてください。条件名・自由記述・追加した資源は含みません。',u.href);}}
function saveProfile(){const p=readProfile();const next={...saved,[cityCode]:p};localStorage.setItem(STORAGE,JSON.stringify(next));saved=next;drafts[cityCode]=p;$('#saved-label').textContent='この端末に保存済み';$('#profile-state').textContent=cityName()+'の条件を保存しました';}
function importResource(r){if(!r||typeof r.id!=='string'||typeof r.name!=='string'||r.name.length>100||!Object.keys(kinds).includes(r.category)||!boundaries.features.some(f=>f.properties.name===r.city)||!Number.isFinite(r.lat)||!Number.isFinite(r.lon)||r.lat<32||r.lat>34||r.lon<130||r.lon>133)throw Error('登録資源の名前・地域・位置が不正です');for(const k of ['provider','eligibleUsers','sourceText','operatingPeriod','potential','positionNote','capacityNote','checkedAt'])if(r[k]!=null&&(typeof r[k]!=='string'||r[k].length>1500))throw Error('登録資源の文字数が不正です');if(r.vehicleCount!=null&&(!Number.isInteger(r.vehicleCount)||r.vehicleCount<0||r.vehicleCount>10000))throw Error('登録資源の台数が不正です');return {...r,id:'local-'+crypto.randomUUID(),userAdded:true};}
async function importSettings(file){if(!file)return;if(file.size>3e6)throw Error('設定ファイルは3MB以下で指定してください');const data=JSON.parse(await file.text());if(data.schema!=='fukuoka-gaps-settings/1'||!Array.isArray(data.profiles)||data.profiles.length>60||!Array.isArray(data.resources)||data.resources.length>500)throw Error('この画面の設定ファイルではありません');const next={};for(const p of data.profiles){validateFiles(p);if(next[p.cityCode])throw Error('自治体の条件が重複しています');next[p.cityCode]=p;}const entries=data.resources.map(importResource);if(!data.profiles.length)throw Error('自治体の条件がありません');drafts={...drafts,...next};custom=entries;const selected=next[data.selectedCity]?data.selectedCity:data.profiles[0].cityCode;await switchCity(selected,false,next[selected]);$('#profile-state').textContent='設定・登録資源を読み込みました。結果は再計算してください。';}
function settings(){const p=readProfile();return {schema:'fukuoka-gaps-settings/1',engine:GAP_VERSION,createdAt:new Date().toISOString(),selectedCity:cityCode,profiles:Object.values({...saved,...drafts,[cityCode]:p}),resources:custom};}
function exportMetadata(){return {engine:GAP_VERSION,city:cityName(),analysis:applied,complete:!!applied?.complete,sourceHealth:health,excludedTrips:excluded,activityCells:activityCount,totalCells:cells.length,sources:geoSources,scope:'自治体が確認する交通空白候補。登録・表示した送迎資源は判定の補完には用いていない。対象代表点の判定をメッシュ面に表示。人口絞込は2020年基準人口（国交省調整値）。'};}
function requireResult(){if(dirty||!applied)throw Error('条件を地図に反映してから結果を保存してください');}
function exportGeo(){requireResult();download('fukuoka-gaps-'+cityCode+'.geojson',JSON.stringify({type:'FeatureCollection',metadata:exportMetadata(),features:cells.map(f=>({...f,properties:{...f.properties,assessment:results.get(f.id)??{status:'unknown',reason:'未計算'}}}))}), 'application/geo+json');}
function exportCSV(){requireResult();const p=applied.profile;const rows=cells.map(f=>{const r=results.get(f.id),v=f.properties;return {municipality:v.city,municipality_code:v.cityCode,mesh_code:v.meshCode,latitude:v.lat,longitude:v.lon,status:STATES[r?.status??'unknown'],area_km2:v.areaKm2,population_2020_adjusted:v.population2020??'',population_note:v.populationNote,nearest_stop:r?.nearest?.name??'',nearest_m:r?.nearest?.meters??'',departures:r?.departures??'',reasons:r?.criteria.map(c=>c.label+':'+c.reason).join(' / ')??'未計算',profile_name:p.name,date:p.date,criteria:JSON.stringify(p),transport_sources:health.map(h=>h.name+' / '+h.hash+' / '+h.coverage).join(' | '),geodata_attribution:geoSources.boundary.attribution+' / '+geoSources.population.attribution,boundary_source:geoSources.boundary.url,population_source:geoSources.population.url,geodata_license:geoSources.boundary.license,geodata_terms:geoSources.boundary.licenseUrl,source_notes_url:'https://mobilitydlab.com/fukuoka-mobility/usage.html#sources',engine:GAP_VERSION};});download('fukuoka-gaps-'+cityCode+'.csv','\ufeff'+csvText(rows,{safe:true}),'text/csv;charset=utf-8');}
function reportSVG(){const b=boundaryLayer.getBounds(),west=b.getWest(),east=b.getEast(),south=b.getSouth(),north=b.getNorth(),width=900,height=Math.min(800,Math.max(350,(north-south)/((east-west)*Math.cos((north+south)*Math.PI/360))*900));const xy=p=>[(p[0]-west)/(east-west)*width,height-(p[1]-south)/(north-south)*height];const path=g=>(g.type==='Polygon'?[g.coordinates]:g.coordinates).map(poly=>poly.map(ring=>ring.map((p,i)=>(i?'L':'M')+xy(p).map(x=>x.toFixed(1)).join(',')).join('')+'Z').join('')).join('');return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-5 -5 ${width+10} ${height+10}" aria-label="区域判定図"><rect width="${width}" height="${height}" fill="#f1f6f8"/><path d="${path(city().geometry)}" fill="#fff" stroke="#506c7a" stroke-width="1" fill-rule="evenodd"/>${cells.map(f=>`<path d="${path(f.geometry)}" fill="${colors[results.get(f.id)?.status??'unknown']}" fill-opacity=".6" stroke="#fff" stroke-width=".3" fill-rule="evenodd"/>`).join('')}${allResources().filter(r=>r.city===cityName()&&hasPosition(r)).map(r=>{const [x,y]=xy([r.lon,r.lat]);return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="4" fill="${r.serviceStatus==='suspended'?'#777':'#b27609'}" stroke="white"><title>${esc(r.name)}</title></circle>`;}).join('')}</svg>`;}
function profileTable(p){const rows=[['自治体',cityName()],['条件名',p.name],['分析日',p.date],['区域',p.resolution+'m・'+(p.populatedOnly?'2020年基準人口のあるメッシュ':'行政界内全域')],['不足の組み合わせ',p.combine==='any'?'どれか1つが不足':'すべてが不足'],['停留所距離',p.distanceOn?p.distanceM+'m超':'使用しない'],['乗車便数',p.frequencyOn?`${p.frequencyRadius}m内・${p.serviceStart}〜${p.serviceEnd}で${p.minimumTrips}便未満`:'使用しない'],['往復条件',p.activityOn?`${p.departure}発、${p.activityFrom}〜${p.activityTo}に用事開始、滞在${p.dwell}分、${p.deadline}まで帰宅`:'使用しない'],['設定の根拠',p.note||'未記入']];return '<table>'+rows.map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')+'</table>';}
function sourceHTML(){return `<h2>出典・データの基準日</h2><ul><li>${safeLink(geoSources.boundary.url,'国土数値情報 行政区域・2026年')}：福岡県60市町村。政令市の区を統合、表示用に20m簡略化。</li><li>${safeLink(geoSources.population.url,'500mメッシュ人口')}：2020年基準人口（国交省調整値）。市町村境界をまたぐ人口・収録外は未集計。</li><li>交通は公開GTFSの収録分。西鉄バス・JR等を含む全交通の網羅ではありません。入力条件と収録分だけの候補です。</li><li>施設・送迎・背景地図の出典は${safeLink('usage.html#sources','利用条件')}、個別データは${safeLink('data-catalog.html','DATA CATALOG')}に記載。</li></ul>`;}
function exportReport(){requireResult();const p=applied.profile,s=statistics(),candidates=cells.filter(f=>results.get(f.id)?.status==='fail');const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(cityName())} 交通空白候補と輸送資源</title><style>body{font:16px/1.8 sans-serif;color:#173b50;max-width:1100px;margin:30px auto;padding:20px}h1{font-size:28px}h2{font-size:21px;margin-top:30px}h3{font-size:17px}svg{width:100%;max-height:740px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{border:1px solid #cddbe3;padding:9px;text-align:left;vertical-align:top}th{background:#edf3f8}p,li{overflow-wrap:anywhere}.note{padding:18px;background:#edf3f8}.status-badge{font-weight:bold}.resource-card{border-bottom:1px solid #ccd9e2;padding:14px 0;break-inside:avoid}.small-note{font-size:13px}a{color:#215ec7}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}@media print{body{margin:0;max-width:none}h2{break-after:avoid}}</style><h1>${esc(cityName())} 交通空白候補と地域の輸送資源</h1><p>${esc(p.name)} ／ ${esc(p.date)} ／ 保存日 ${esc(new Date().toISOString())}</p><div class="note">赤：設定条件に該当する交通空白候補。青緑：空白条件に非該当。灰：データ不足・未計算。金色：輸送資源の施設等。区域内代表点の結果であり、正式指定や住民全員の状態ではありません。${applied.complete?'計算処理完了。':'計算は未完了です。'}往復判定済み ${activityCount} / ${cells.length}区域（往復条件${p.activityOn?'使用':'不使用'}）。</div><h2>区域別の判定</h2>${reportSVG()}<table><tr><th>区分</th><th>区域数</th><th>区域面積</th></tr>${['fail','pass','unknown'].map(k=>`<tr><td>${STATES[k]}</td><td>${fmt(s[k].count)}</td><td>${fmt(s[k].area,2)} km²</td></tr>`).join('')}</table><p>面積は困っている人数ではありません。2020年基準人口による絞り込み：${p.populatedOnly?'あり':'なし'}。メッシュ内の居住位置は特定していません。輸送資源の表示は判定を変えません。</p><h2>判定条件</h2>${profileTable(p)}<h2>該当理由を確認する区域</h2><p>${candidates.length}区域のうち先頭50区域。全区域と全条件は別途CSV・GeoJSONに保存できます。</p><table><tr><th>メッシュ</th><th>最寄停留所まで</th><th>便数</th><th>理由</th></tr>${candidates.slice(0,50).map(f=>{const r=results.get(f.id);return `<tr><td>${esc(f.properties.meshCode)}</td><td>${fmt(r.nearest?.meters)}m</td><td>${fmt(r.departures)}</td><td>${esc(r.criteria.map(c=>c.label+'：'+c.reason).join(' / '))}</td></tr>`;}).join('')}</table><h2>輸送資源の公表事例・登録内容</h2>${allResources().filter(r=>r.city===cityName()).map(r=>resourceHTML(r,false)).join('')||'<p>未収録。資源の不存在を意味しません。</p>'}<h2>使用交通データ</h2>${health.map(h=>`<p>${safeLink(h.source,h.name)} ／ ${esc(h.coverage)}<br><small>SHA-256 ${esc(h.hash)}</small></p>`).join('')}<h2>次の確認</h2><p>交通担当部署が候補区域の住民と運行者に、実際の居住位置・時間・道路・予約・利用対象・既存送迎の活用可能性を確認します。条件変更による色の変化と、実際の運行改善を区別して比較してください。</p>${sourceHTML()}<details><summary>全設定・計算範囲・データ版</summary><pre>${esc(JSON.stringify(exportMetadata(),null,2))}</pre></details></html>`;download('fukuoka-gaps-'+cityCode+'-report.html',html,'text/html;charset=utf-8');}
async function init(){
  [catalog,boundaries,places,resources,transport,geoSources]=await Promise.all([json('data/gtfs/catalog.json'),json('gaps/data/municipalities.geojson'),Promise.all([json('access/destinations.json'),json('access/shopping.json')]).then(a=>a.flat()),json('gaps/resources.json'),json('data/map-data.json'),json('gaps/data/sources.json')]);
  $('#municipality').innerHTML=boundaries.features.map(f=>`<option value="${f.properties.code}">${esc(f.properties.name)}</option>`).join('');
  $('#feed-list').innerHTML=catalog.filter(f=>f.analysisReady).map(f=>`<div class="feed-row"><label><input type="checkbox" value="${esc(f.file)}">${esc(f.name)}</label><small>${safeLink(f.catalog,'公開データの出典')}</small></div>`).join('');
  const ordered=[...places].sort((a,b)=>a.city.localeCompare(b.city,'ja')||a.name.localeCompare(b.name,'ja'));$('#destination').innerHTML=ordered.map(f=>`<option value="${esc(f.id)}">${esc(f.city+' · '+f.name)}</option>`).join('');
  try{const parsed=JSON.parse(localStorage.getItem(STORAGE)??'{}');for(const [code,p]of Object.entries(parsed)){try{if(code!==p.cityCode)continue;validateFiles(p);saved[code]=p;}catch{}}}catch{}
  let shared=null;try{const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('conditions')){shared=validateFiles(decode(hash.get('conditions')));cityCode=shared.cityCode;}}catch(e){error(Error('共有条件を読み込めないため初期条件を表示します。'+e.message));}
  map=L.map('map',{preferCanvas:true}).setView([33.6,130.55],10);L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',{maxZoom:18,attribution:'<a href="https://maps.gsi.go.jp/development/ichiran.html">国土地理院</a>'}).addTo(map);
  boundaryLayer=L.geoJSON(null,{style:{color:'#173b50',weight:2,fillOpacity:0,interactive:false}}).addTo(map);gridLayer=L.layerGroup().addTo(map);stopLayer=L.layerGroup();resourceLayer=L.layerGroup().addTo(map);poiLayer=L.layerGroup();pickLayer=L.layerGroup().addTo(map);
  map.on('click',e=>{if(!picking)return;pickPoint={lat:e.latlng.lat,lon:e.latlng.lng};picking=false;pickLayer.clearLayers();L.circleMarker(e.latlng,{radius:7,color:'#173b50',fillOpacity:1}).addTo(pickLayer);$('#resource-position').textContent=`登録位置：${pickPoint.lat.toFixed(5)}, ${pickPoint.lon.toFixed(5)}`;$('#map-tip').textContent='施設・乗降拠点を指定しました。資源の情報を入力して登録してください。';});
  for(const [id,layer]of [['show-gaps',gridLayer],['show-stops',stopLayer],['show-resources',resourceLayer],['show-pois',poiLayer]])on('#'+id,'change',()=>$( '#'+id).checked?map.addLayer(layer):map.removeLayer(layer));
  for(const e of $$('[data-tab]'))e.addEventListener('click',()=>setTab(e.dataset.tab));
  for(const id of [...Object.values(ids),'destination'])on('#'+id,'change',invalidate);on('#feed-list','change',()=>{invalidate();renderStops();});
  on('#municipality','change',e=>switchCity(e.target.value));on('#fit-city','click',fitCity);on('#run','click',run);on('#cancel','click',()=>cancel());on('#save-profile','click',saveProfile);on('#reset-profile','click',async()=>{const p=defaultProfile(cityCode,standardFiles());fillProfile(p);drafts[cityCode]=p;invalidate();await loadCells(p);});
  on('#resource-type','change',renderResources);on('#resource-use','change',renderResources);on('#resource-form','submit',addResource);on('#pick-resource','click',()=>{picking=true;$('#map-tip').textContent='地図上の施設・乗降拠点を押してください。';$('#map').scrollIntoView({block:'center',behavior:'smooth'});});$('#resource-date').value=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
  on('#share','click',share);on('#export-csv','click',exportCSV);on('#export-geo','click',exportGeo);on('#export-report','click',exportReport);on('#export-settings','click',()=>download('fukuoka-gaps-settings.json',JSON.stringify(settings(),null,2),'application/json'));on('#import-settings','change',async e=>{try{await importSettings(e.target.files[0]);}finally{e.target.value='';}});
  $('#sources').innerHTML=sourceHTML();await switchCity(cityCode,true,shared);if(location.hash==='#resources')setTab('resources');document.documentElement.dataset.atlasReady='true';document.dispatchEvent(new Event('atlas:ready'));
}
guard(init)();
