import { labels, statusLabels, filterProjects, escapeHTML, metricValue } from './model.js';
const $=s=>document.querySelector(s);
const metrics=Object.keys(labels), quick=['pbl','fieldwork','resident_participation','student_participation','actual_operation','social_implementation','continuity'];
let data, currentEntry, view='list', lastTrigger;
const esc=escapeHTML;
const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'||u.protocol==='http:'?u.href:'#';}catch{return '#';}};
function badge(m){const s=m?.status||'unverified';return `<span class="tag ${esc(s)}">${esc(statusLabels[s]||s)}</span>`;}
function state(){return {query:$('#search').value,prefecture:$('#prefecture').value,keys:[...document.querySelectorAll('[name="metric"]:checked')].map(x=>x.value),mode:$('#status-mode').value};}
function updateURL(){const s=state(),u=new URL(location.href);for(const k of ['q','pref','metrics','state'])u.searchParams.delete(k);if(s.query)u.searchParams.set('q',s.query);if(s.prefecture)u.searchParams.set('pref',s.prefecture);if(s.keys.length){u.searchParams.set('metrics',s.keys.join(','));u.searchParams.set('state',s.mode);}history.replaceState(null,'',u);}
function projectSummary(p){const a=(p.confirmed_activities||[]).find(x=>x.status==='confirmed')||(p.confirmed_activities||[])[0];return {text:typeof a==='string'?a:a?.text||'採択を確認。個別の実施内容は公開資料の確認範囲をご覧ください。',label:typeof a==='object'&&a?.status?statusLabels[a.status]:'確認資料の記述'};}
function render(){if(!data)return;const s=state(),rows=filterProjects(data.projects,s);$('#status-mode').disabled=!s.keys.length;$('#result-count').innerHTML=`<strong>${rows.length}</strong> / ${data.projects.length} PROJECTS`;$('#view-list').setAttribute('aria-pressed',String(view==='list'));$('#view-table').setAttribute('aria-pressed',String(view==='table'));if(!rows.length){$('#results').innerHTML='<div class="empty"><p>この条件に合う確認記録はありません。</p><p>実施していないことを意味しません。条件を減らすか「計画も含める」でお探しください。</p></div>';updateURL();return;}
if(view==='list')$('#results').innerHTML=rows.map(p=>`<article class="project-row"><span class="project-number">${esc(String(p.official_order).padStart(2,'0'))}</span><div class="project-region"><strong>${esc(p.prefectures.join('・'))}</strong><span class="long-region">${esc(p.region)}</span></div><div class="project-content"><button type="button" class="project-title" data-project="${esc(p.id)}">${esc(p.project_name)}</button><p class="project-operator">${esc(p.operator)}</p><div class="project-tags">${quick.filter(k=>['confirmed','planned'].includes(p.metrics[k]?.status)).map(k=>`<span class="tag ${p.metrics[k].status}">${esc(labels[k])} / ${statusLabels[p.metrics[k].status]}</span>`).join('')}</div></div><p class="project-summary"><small class="summary-state">${esc(projectSummary(p).label)}</small>${esc(projectSummary(p).text)}<span class="source-count">個別一次資料 ${(p.individual_sources||[]).filter(x=>x.primary!==false).length}件 / 確認 ${esc(p.checked_at)}</span></p><button type="button" class="open-project" data-project="${esc(p.id)}" aria-label="${esc(p.project_name)}の詳細">↗</button></article>`).join('');
else{$('#results').innerHTML=`<div class="table-wrap" tabindex="0" role="region" aria-label="全比較項目の表。横にスクロールできます"><table class="compare-table"><caption class="sr-only">検索結果 ${rows.length}事業の比較</caption><thead><tr><th scope="col">事業・実施主体</th>${metrics.map(k=>`<th scope="col">${labels[k]}</th>`).join('')}</tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.prefectures.join('・'))}<br><button class="project-title" data-project="${esc(p.id)}">${esc(p.project_name)}</button><p class="project-operator">${esc(p.operator)}</p></td>${metrics.map(k=>`<td>${badge(p.metrics[k])}${['activity_count','participants'].includes(k)?`<div>${esc(metricValue(p.metrics[k]))}</div>`:''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
updateURL();}
function sourceLinks(p,m){return (m.source_ids||[]).map(id=>{const src=p.individual_sources.find(x=>x.id===id);return src?`<a href="${esc(safeURL(src.url))}" target="_blank" rel="noopener">${esc(id.replace(p.id+'-',''))} ↗</a>`:'';}).join('');}
function openProject(id,trigger){const p=data.projects.find(x=>x.id===id);if(!p)return;lastTrigger=trigger||lastTrigger;const unknown=metrics.filter(k=>(p.metrics[k]?.status||'unverified')==='unverified');
$('#detail-content').innerHTML=`<p class="detail-meta">${esc(p.id.toUpperCase())} / ${esc(p.prefectures.join('・'))} / ${esc(p.fiscal_year)}年度</p><h2 id="detail-title">${esc(p.project_name)}</h2><p class="detail-subtitle">実施主体：${esc(p.operator)}<br>対象地域：${esc(p.region)}<br>資料確認日：${esc(p.checked_at)}</p><section class="detail-section"><h3>確認できた活動</h3>${p.confirmed_activities.length?`<ul>${p.confirmed_activities.map(a=>{if(typeof a==='string')return `<li>${esc(a)}</li>`;return `<li>${badge(a)} ${esc(a.text||'')}<span class="source-links">${sourceLinks(p,a)}</span></li>`;}).join('')}</ul>`:'<p>個別の活動を記述できる一次資料は、今回の閲覧範囲では確認できませんでした。</p>'}</section><section class="detail-section"><h3>社会実装プロセス・比較項目</h3>${p.implementation_process?.length?`<p class="research-note">資料に記された工程を整理（実施／計画は下表の判定をご覧ください）</p><ul class="process-list">${p.implementation_process.map(x=>`<li>${esc(typeof x==='string'?x:x.label||x.text||JSON.stringify(x))}</li>`).join('')}</ul>`:''}<dl class="detail-grid">${metrics.map(k=>{const m=p.metrics[k]||{status:'unverified'};return `<dt>${labels[k]}</dt><dd>${badge(m)}<span class="metric-value">${esc(metricValue(m))}</span><p class="metric-note">${esc(m.note||'')}</p><span class="source-links">${sourceLinks(p,m)}</span></dd>`;}).join('')}</dl></section><section class="detail-section"><h3>未確認項目</h3><div class="unverified-box">${unknown.length?esc(unknown.map(k=>labels[k]).join(' / ')):'上記の比較項目に未確認の判定はありません。'}<p>未確認は、実施していないという判定ではありません。資料の公開範囲や確認日に左右されます。</p></div></section><section class="detail-section"><h3>一次資料・確認範囲</h3><ul class="source-list"><li><a href="${esc(safeURL(p.official_source.url))}" target="_blank" rel="noopener">国土交通省 正式採択一覧 ↗</a><small>${esc(p.official_source.publisher)} / ${esc(p.official_source.published_at)} / ${esc(p.official_source.page)}ページ・採択の事実を確認</small></li>${(p.individual_sources||[]).map(src=>`<li><a href="${esc(safeURL(src.url))}" target="_blank" rel="noopener">[${esc(src.id.replace(p.id+'-',''))}] ${esc(src.title)} ↗</a><small>${esc(src.publisher||'')} / ${esc(src.stage||src.locator||'')} / 確認 ${esc(src.checked_at||p.checked_at)}</small><p>${esc(src.note||'')}</p></li>`).join('')}</ul><p class="research-note">${esc(p.research_scope_note||'公開一次資料を対象にした確認です。非公開資料の内容や主催者への照会結果は含みません。')}</p>${(p.notes||[]).length?`<ul>${p.notes.map(n=>`<li>${esc(typeof n==='string'?n:JSON.stringify(n))}</li>`).join('')}</ul>`:''}</section>`;
if(!$('#project-detail').open)$('#project-detail').showModal();$('#project-detail').scrollTop=0;$('#close-detail').focus();const u=new URL(location.href);u.hash=p.id;history.replaceState(null,'',u);}
$('#close-detail').addEventListener('click',()=>$('#project-detail').close());$('#project-detail').addEventListener('close',()=>{const u=new URL(location.href);u.hash='';u.searchParams.delete('project');history.replaceState(null,'',u);lastTrigger?.focus();});
$('#filters').addEventListener('submit',e=>e.preventDefault());$('#filters').addEventListener('input',render);$('#filters').addEventListener('change',render);$('#filters').addEventListener('reset',()=>setTimeout(render,0));$('#view-list').addEventListener('click',()=>{view='list';render();});$('#view-table').addEventListener('click',()=>{view='table';render();});$('#results').addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)openProject(b.dataset.project,b);});
async function load(){try{const mres=await fetch('./data/manifest.json');if(!mres.ok)throw Error('manifest');const manifest=await mres.json();const y=new URL(location.href).searchParams.get('year')||String(manifest.default_year),entry=manifest.datasets.find(d=>String(d.fiscal_year)===y)||manifest.datasets[0];const res=await fetch(entry.path);if(!res.ok)throw Error('data');data=await res.json();currentEntry=entry;$('#dataset-count').textContent=data.population.count;$('#dataset-title').textContent='FIELD ARCHIVE / '+entry.label;$('#data-download').href=entry.path;document.title=data.population.count+' PROJECTS｜'+entry.label+' | MDL';$('#year').replaceChildren(...manifest.datasets.map(d=>new Option(d.label,String(d.fiscal_year),false,d===entry)));$('#year').addEventListener('change',()=>{const u=new URL(location.href);u.searchParams.set('year',$('#year').value);location.assign(u.href);});$('#metric-filters').innerHTML=metrics.filter(k=>!['activity_count','participants'].includes(k)).map(k=>`<label><input type="checkbox" name="metric" value="${k}">${labels[k]}</label>`).join('');const prefs=[...new Set(data.projects.flatMap(p=>p.prefectures))];for(const p of prefs)$('#prefecture').add(new Option(p,p));$('#checked-date').textContent=`確認日 ${data.checked_at}`;const individual=data.projects.filter(p=>p.source_coverage?.same_year_project_source_reviewed).length;const researched=data.projects.filter(p=>p.research_log?.length).length;$('#coverage').innerHTML=`<div><strong>${data.projects.length} / ${data.population.count}</strong><span>正式採択との照合</span></div><div><strong>${researched} / ${data.population.count}</strong><span>個別の資料探索を記録</span></div><div><strong>${individual} / ${data.population.count}</strong><span>当年度・同一事業の資料を確認</span></div><div><strong>${data.projects.length-individual}</strong><span>関連・他年度資料まで／当年度未確認</span></div>`;if(data.coding_definitions)$('#definitions').innerHTML=Object.entries(data.coding_definitions).map(([k,v])=>`<dt>${esc(labels[k]||k)}</dt><dd>${esc(v)}</dd>`).join('');const u=new URL(location.href);$('#search').value=u.searchParams.get('q')||'';$('#prefecture').value=u.searchParams.get('pref')||'';$('#status-mode').value=['confirmed','documented','unverified'].includes(u.searchParams.get('state'))?u.searchParams.get('state'):'confirmed';for(const key of (u.searchParams.get('metrics')||'').split(',')){const el=document.querySelector(`[name="metric"][value="${CSS.escape(key)}"]`);if(el)el.checked=true;}render();const linkedProject=u.searchParams.get('project')||(location.hash.startsWith('#r7-')?location.hash.slice(1):'');if(linkedProject)openProject(linkedProject);}catch(err){$('#load-error').hidden=false;$('#result-count').textContent='読込エラー';$('#coverage').textContent='データの読込状況を確認できませんでした。';console.error('Project data load failed',err);}}
load();
