import {kinds,statuses,verificationLabels,escapeHTML as esc,safeURL,norm,displayValue,filterCases,caseClaims,usedIn,sourceFilter,gapCounts} from './atlas-model.js?v=collections-20260921';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let data,caseMap,sourceMap,claimMap,uses,dataset='traffic',view='list',page=1,sourcePage=1,qualityPage=1,lastCaseTrigger,lastSourceTrigger;
const PAGE=12, SOURCE_PAGE=12, QUALITY_PAGE=10;
const trainingFields=['activity_count','participants','lecture','pbl','fieldwork','resident_participation','student_participation','demonstration','actual_operation','social_implementation','continuity'];
const trainingLabels=['活動・開催回数','参加人数','講義','PBL','フィールドワーク','住民参加','学生参加','実証','実運行','社会実装','継続'];
function kind(f){return '<span class="kind '+esc((f.kind||'ANALYSIS').toLowerCase())+'" title="'+esc(kinds[f.kind]||'')+'">'+esc(f.kind||'ANALYSIS')+'</span>';}
function status(f){return '<span class="status '+esc(f.status||'NOT_CONFIRMED')+'">'+esc(statuses[f.status]||'未確認')+'</span>';}
function verify(f){return ['USER_REPORTED','NEEDS_VERIFICATION'].includes(f.verification_status)?'<span class="verification '+(f.verification_status==='USER_REPORTED'?'reported':'')+'">'+esc(verificationLabels[f.verification_status])+'</span>':'';}
function sourceButton(f,label='SOURCE ↗'){return '<button type="button" class="source-button" data-claim="'+esc(f.id)+'" aria-label="'+esc(f.label||'項目')+'の出典">'+label+'</button>';}
function link(url,label){const u=safeURL(url);return u?'<a href="'+esc(u)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>':'<span>原典リンク未確認</span>';}
function datum(f){return '<div class="field-state">'+kind(f)+status(f)+verify(f)+'</div><div class="field-value">'+esc(displayValue(f))+'</div><p class="field-note">'+esc(f.note||'')+'</p>'+(f.as_of?'<small class="as-of">確認基準日 AS OF '+esc(f.as_of)+' / '+(f.temporal_context==='PAST_REPORT'?'値は過去の報告期間のもの':'現在状況の確認範囲')+'</small>':'')+sourceButton(f);}
function filterState(){return {query:$('#search').value,dataset,gap:$('#gap-filter').value,issue:$('#issue-filter').value,prefecture:$('#region-filter').value,activity:$('#activity-filter').value,status:$('#status-filter').value,needs:$('#needs-filter').checked};}
function syncURL(){const u=new URL(location.href),s=filterState();for(const [k,v] of Object.entries({q:s.query,dataset:s.dataset,gap:s.gap,issue:s.issue,pref:s.prefecture,activity:s.activity,state:s.status,needs:s.needs?'1':'',view:view==='table'?'table':''})){if(v)u.searchParams.set(k,v);else u.searchParams.delete(k);}history.replaceState(null,'',u);}
function pager(el,current,count,size,group){const total=Math.ceil(count/size);$(el).innerHTML=total>1?'<button data-page-group="'+group+'" data-page="'+(current-1)+'" '+(current===1?'disabled':'')+' aria-label="前のページ">← 前へ</button><span>'+current+' / '+total+'ページ</span><button data-page-group="'+group+'" data-page="'+(current+1)+'" '+(current===total?'disabled':'')+' aria-label="次のページ">次へ →</button>':'';}
function summary(c){return c.fields.problem||c.fields.activity_0||c.fields.identity;}
function officialCaseLink(c,className='case-title',label=c.name){return '<a class="'+className+'" href="'+esc(safeURL(c.official_url))+'" target="_blank" rel="noopener noreferrer">'+esc(label)+'</a>';}
function rowsHTML(rows){return rows.map(c=>{const f=summary(c);return '<article class="case-row'+(c.is_mdl_project?' mdl-case-row':'')+'"><span class="case-number">'+String(c.order).padStart(2,'0')+'</span><div class="case-region"><strong>'+esc(c.region)+'</strong><span>'+(c.dataset==='traffic'?'交通空白の解消事例':'人材育成の採択事業')+'</span>'+(c.is_mdl_project?'<a class="mdl-badge" href="#mdl-practice">MDL伴走事業 ↗</a>':'')+'</div><div class="case-main">'+officialCaseLink(c)+'<p class="case-operator">'+esc(c.operator)+'</p><div class="case-tags">'+(c.gaps.length?c.gaps.map(g=>'<span class="gap-tag">'+esc(g.gap_id)+' GAP</span>').join(''):trainingFields.slice(2).filter(k=>['IMPLEMENTED','PLANNED'].includes(c.fields[k]?.status)).slice(0,4).map(k=>'<span class="gap-tag">'+esc(c.fields[k].label)+' / '+esc(statuses[c.fields[k].status])+'</span>').join(''))+'</div><div class="row-foot">'+officialCaseLink(c,'official-case-link',c.official_link_label+' ↗')+'<button class="text-button" data-case="'+c.id+'">MDLの整理・出典</button></div><p class="small">'+(c.gaps.length?'分類：MDL ANALYSIS':'活動区分：MDL ANALYSIS')+'</p></div><div class="case-summary">'+kind(f)+verify(f)+'<p>'+esc(displayValue(f))+'</p><div class="row-foot">'+sourceButton(f)+'<span class="small">確認 '+esc(f.last_verified)+'</span></div></div><a class="open-case" href="'+esc(safeURL(c.official_url))+'" target="_blank" rel="noopener noreferrer" aria-label="'+esc(c.name+'：'+c.official_link_label)+'">↗</a></article>';}).join('');}
function tableHTML(rows){const traffic=dataset==='traffic',keys=traffic?['period','results','fare','operating_time','total_cost','current_operation']:trainingFields,labels=traffic?['集計期間','利用実績','料金（報告当時）','時間（報告当時）','総事業費','現在の継続']:trainingLabels;
return '<div class="table-wrap" tabindex="0" role="region" aria-label="項目別比較表。横にスクロールできます"><table><caption class="sr-only">表示中の事例の項目別比較。各セルに出典。</caption><thead><tr><th scope="col">地域・事例</th>'+labels.map(x=>'<th scope="col">'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(c=>'<tr><td><span class="small">'+esc(c.region)+'</span><br>'+officialCaseLink(c)+'<p>'+officialCaseLink(c,'official-case-link',c.official_link_label+' ↗')+'</p><button class="text-button" data-case="'+c.id+'">MDLの整理・出典</button></td>'+keys.map(k=>{const f=c.fields[k];return '<td>'+(f?kind(f)+' '+status(f)+verify(f)+'<div class="cell-value">'+esc(displayValue(f))+'</div>'+sourceButton(f):'<span class="small">未確認</span><button class="source-button" data-case="'+c.id+'">整理・出典 ↗</button>')+'</td>';}).join('')+'</tr>').join('')+'</tbody></table></div><p class="chart-caption">Source: 各セルのSOURCEに記載<br>Analysis: Mobility Design Lab / 単位・期間・定義をそろえたランキングではありません。<br>Last verified: 各セルの確認日を参照</p>';}
function renderCases(){if(!data)return;const rows=filterCases(data.cases,filterState());page=Math.min(page,Math.max(1,Math.ceil(rows.length/PAGE)));$$('[data-dataset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dataset===dataset)));$('#view-list').setAttribute('aria-pressed',String(view==='list'));$('#view-table').setAttribute('aria-pressed',String(view==='table'));const collection=data.collections.find(c=>c.id===dataset),traffic=dataset==='traffic';$('#collection-title').textContent=traffic?'交通空白を解消する、37の実践。':'地域交通を担う、61の人材育成事業。';$('#collection-description').textContent=traffic?'国交省公式サイトが紹介する交通サービスの事例。事例名から公式紹介を開きます。':'2025年5月15日採択のモビリティ人材育成事業。事例名から国交省の個別紹介、または採択一覧（PDF）を開きます。';$('#collection-official').href=collection.official_url;$('#collection-official').textContent=traffic?'国交省の事例紹介サイト ↗':'国交省の人材育成紹介サイト ↗';$('#gap-filter-label').hidden=!traffic;$('#issue-filter-label').hidden=!traffic;$('#activity-filters').hidden=traffic;$('#result-count').innerHTML='<strong>'+rows.length+'</strong> / '+collection.count+(traffic?' 交通空白事例':' 人材育成事業');const shown=rows.slice((page-1)*PAGE,page*PAGE);$('#results').innerHTML=rows.length?(view==='list'?rowsHTML(shown):tableHTML(shown)):'<div class="empty"><h3>この条件に一致する確認記録はありません。</h3><p>未実施を意味しません。条件を減らすか、未確認を含めて探してください。</p></div>';pager('#pagination',page,rows.length,PAGE,'cases');syncURL();}
function renderOverview(){const oita=caseMap.get('r7-058');$('#traffic-count-source').innerHTML=sourceButton(claimMap.get('total-traffic'));$('#training-count-source').innerHTML=sourceButton(claimMap.get('total-training'));$('#mdl-metrics').innerHTML=['activity_count','participants'].map((key,i)=>{const f=oita.fields[key];return '<article class="mdl-metric"><div class="metric-number">'+f.value+'<small>'+(i?'人以上':'活動')+'</small></div><p class="metric-en">'+(i?'PARTICIPATIONS / 延べ参加人数':'ACTIVITIES / 活動項目')+'</p><div class="metric-source">'+sourceButton(f)+'</div></article>';}).join('');$('#mdl-operation-metrics').innerHTML=['operating_days','actual_users','total_rides'].map((key,i)=>{const f=oita.fields[key];return '<article><p>'+['実運行','実利用者','延べ乗車'][i]+'</p><strong>'+f.value+'<small>'+esc(f.unit)+'</small></strong>'+sourceButton(f)+'</article>';}).join('');
$('#social-grid').innerHTML=data.social_issues.filter(f=>f.value!==null).map(f=>'<article class="social-stat"><div>'+kind(f)+'<h3>'+esc(f.label)+'</h3><p>'+esc(f.note)+'</p></div><div><div class="social-number">'+esc(f.value)+'<small>'+esc(f.unit)+'</small></div><p>統計対象 AS OF '+esc(f.as_of)+'</p>'+sourceButton(f)+'</div></article>').join('');
$('#issue-links').innerHTML=data.social_issues.map(f=>'<button class="issue-pill" data-issue="'+esc(f.label)+'">#'+esc(f.label)+' ↗</button>').join('');
$('#gap-grid').innerHTML=gapCounts(data.cases.filter(c=>c.dataset==='traffic'),data.gaps).map((g,i)=>'<button class="gap-card" data-gap="'+g.id+'" aria-label="'+g.label+'の事例を探す"><span class="gap-index">0'+(i+1)+'<span class="gap-count">'+g.count+'<small>事例</small></span></span><span class="gap-en">'+g.name+'</span><h3>'+g.label+'</h3><p>'+g.question+'</p><span class="arrow">↗</span></button>').join('');
$('#update-log').innerHTML=data.update_log.map(l=>'<article class="log-entry"><time>'+esc(l.date.replaceAll('-','.'))+'</time><div><h3>'+esc(l.title)+'</h3><p>'+esc(l.description)+'</p></div></article>').join('');
$('#methodology-content').innerHTML=['verification_note','classification_method','social_implementation','source_boundaries','numeric_policy','graph_policy','review_rule'].map(k=>'<p>'+esc(data.methodology[k])+'</p>').join('')+'<div class="detail-section"><h3>Evidence Level</h3>'+Object.entries(data.methodology.evidence_levels).map(([k,v])=>'<p><span class="level">'+k+'</span> '+esc(v)+'</p>').join('')+'</div>';}
function renderGraph(){if(!data)return;const c=caseMap.get($('#graph-case').value);if(!c)return;$('#graph-content').innerHTML='<p class="small">'+esc(c.region)+' / '+esc(c.name)+' <button class="text-button" data-case="'+c.id+'">CASE DETAIL ↗</button></p><div class="graph-grid">'+c.graph.nodes.map((n,i)=>'<article class="graph-node"><p class="eyebrow">0'+(i+1)+' / '+esc(n.stage)+'</p><h3>'+esc(n.label)+'</h3><div class="node-text">'+kind(n)+'<p>'+esc(n.text)+'</p></div>'+(n.note?'<p class="node-note">'+esc(n.note)+'</p>':'')+'<div class="row-foot">'+(n.field_refs.length?n.field_refs.map((id,j)=>claimMap.has(id)?sourceButton(claimMap.get(id),j?'根拠 '+(j+1)+' ↗':'SOURCE ↗'):'').join(''):'<button class="source-button" data-source="mdl-framework">分類・仮説の定義 ↗</button>')+'</div>'+(c.graph.edges[i]?'<button class="graph-edge '+c.graph.edges[i].relation_type+'" data-edge="'+c.graph.edges[i].id+'">↓ '+esc(c.graph.edges[i].label)+' / 関係の根拠</button>':'')+'</article>').join('')+'</div><p class="chart-caption">Source: 各ノードのSOURCEに記載<br>Analysis: Mobility Design Lab / 未確認の関係は確認済みの因果として扱いません。<br>Last verified: 各項目の確認日を参照</p>';}
function accessLabel(s){return {PUBLIC:'公開',INTERNAL_ORIGINAL:'原典非公開・既存照合記録',PUBLIC_SUMMARY_OF_INTERNAL:'公開要約（原典は非公開）',INTERNAL_DECLARATION:'MDL活動実績報告',LOCAL_RESEARCH:'MDLの整理表'}[s.access]||'非公開・要確認';}
function renderSources(){if(!data)return;const rows=data.sources.filter(s=>sourceFilter(s,{query:$('#source-query').value,category:$('#source-category').value,dataset:$('#source-dataset').value,level:$('#source-level').value}));sourcePage=Math.min(sourcePage,Math.max(1,Math.ceil(rows.length/SOURCE_PAGE)));$('#source-count').textContent=rows.length+' / '+data.sources.length+'資料';$('#source-results').innerHTML=rows.slice((sourcePage-1)*SOURCE_PAGE,sourcePage*SOURCE_PAGE).map(s=>'<article class="source-row"><span class="level">'+s.evidence_level+'</span><div><button class="source-name" data-source="'+esc(s.id)+'">'+esc(s.title)+'</button><p>'+esc(s.publisher)+' / '+esc(s.categories.join('・'))+'</p></div><div class="source-meta">'+esc(accessLabel(s))+'<br>確認 '+esc(s.last_verified||'未確認')+'</div><button class="used-button" data-source="'+esc(s.id)+'">USED IN<br>'+uses.get(s.id).length+'項目 ↗</button></article>').join('')||'<p class="empty">該当する資料はありません。</p>';pager('#source-pagination',sourcePage,rows.length,SOURCE_PAGE,'sources');}
function qualityRows(){return data.quality_issues.filter(q=>norm([q.case_id,caseMap.get(q.case_id)?.name,caseMap.get(q.case_id)?.region,claimMap.get(q.field_id)?.label,q.reason].join(' ')).includes(norm($('#quality-query').value)));}
function renderQuality(){if(!data)return;const fields=data.cases.flatMap(c=>Object.values(c.fields));const unknown=fields.filter(f=>f.value===null).length,linkUnresolved=data.sources.filter(s=>s.url&&s.link_status!=='REACHABLE').length;
$('#quality-summary').innerHTML=[[fields.length,'出典・確認状態を持つ項目'],[unknown,'値が未確認の項目（0に変換しない）'],[linkUnresolved,'リンク到達・再確認が必要な資料']].map(([n,l])=>'<div class="quality-stat"><strong>'+n.toLocaleString('ja-JP')+'</strong><p>'+l+'</p></div>').join('');
const rows=qualityRows();qualityPage=Math.min(qualityPage,Math.max(1,Math.ceil(rows.length/QUALITY_PAGE)));$('#quality-results').innerHTML='<p class="small">'+rows.length+'件の確認事項。根拠不足を隠さず、次の確認を記録します。</p>'+rows.slice((qualityPage-1)*QUALITY_PAGE,qualityPage*QUALITY_PAGE).map(q=>{const c=caseMap.get(q.case_id),f=claimMap.get(q.field_id);return '<article class="quality-row"><span class="verification">NEEDS VERIFICATION</span><div><b>'+esc(c?c.region:'参照資料')+'</b><p>'+esc(f?.label||q.field_id||'リンク確認')+'</p>'+(c?'<button class="text-button" data-case="'+c.id+'">'+esc(c.id)+' ↗</button>':'')+'</div><div class="quality-reason">'+esc(q.reason)+'<p>次の確認：'+esc(q.next_action)+'</p></div>'+(f?sourceButton(f):q.source_id?'<button class="source-button" data-source="'+q.source_id+'">SOURCE ↗</button>':'')+'</article>';}).join('');pager('#quality-pagination',qualityPage,rows.length,QUALITY_PAGE,'quality');}
function showDialog(id){const d=$('#'+id);if(!d.open)d.showModal();d.scrollTop=0;d.querySelector('[data-close]').focus();document.body.style.overflow='hidden';}
function showCase(id,trigger,claimId){const c=caseMap.get(id);if(!c)return;if($('#source-drawer').open)$('#source-drawer').close();lastCaseTrigger=trigger?.isConnected?trigger:lastCaseTrigger;
$('#case-content').innerHTML='<p class="detail-meta">'+esc(c.id.toUpperCase())+' / '+esc(c.region)+' / '+c.fiscal_year+'年度</p><h2 id="case-title">'+esc(c.name)+'</h2><p class="detail-meta">実施主体：'+esc(c.operator)+'</p><p class="small">'+esc(c.note)+'</p>'+((c.notes||[]).length?'<p class="small">'+esc(c.notes.join(' '))+'</p>':'')+'<div class="row-foot">'+officialCaseLink(c,'button',c.official_link_label+' ↗')+'<a class="small" href="?project='+c.id+'">この事例へのリンク ↗</a><button class="text-button" data-graph-case="'+c.id+'">EVIDENCE GRAPHでたどる ↗</button></div><section class="detail-section"><h3>FACT / CALCULATION / ANALYSIS</h3><dl class="field-grid">'+Object.values(c.fields).map(f=>'<dt id="'+esc(f.id)+'">'+esc(f.label)+'</dt><dd>'+datum(f)+'</dd>').join('')+'</dl></section>'+
(c.gaps.length?'<section class="detail-section"><h3>MDL CLASSIFICATION / GAPの根拠</h3>'+c.gaps.map(g=>'<div id="'+esc(g.id)+'" class="gap-evidence">'+kind(g)+'<h3>'+esc(g.gap_id)+' GAP / '+esc(g.label)+'</h3><p><b>SOURCE FACT</b><br>'+esc(g.source_fact)+'</p><p>'+esc(g.note)+'</p>'+sourceButton(g)+'</div>').join('')+'</section>':'')+
(c.tags.length?'<section class="detail-section"><h3>社会課題タグの根拠</h3>'+c.tags.map(t=>'<p id="'+esc(t.id)+'"><span class="gap-tag">#'+esc(t.label)+'</span> <span class="tag-type">'+esc(t.tag_type)+'</span> '+sourceButton(t)+'</p>').join('')+'</section>':'')+
(c.activities?'<section class="detail-section"><h3>大分の35活動・原表の掲載順</h3><p class="small">活動項目と人数の原票は別です。日付の空欄・年度不整合は補正していません。</p><ol class="activity-list">'+c.activities.map(a=>'<li id="'+esc(a.evidence.id)+'"><b>'+String(a.number).padStart(2,'0')+' '+esc(a.title)+'</b><small>'+esc(a.dateDisplay)+' / '+esc(a.place)+'</small><p>'+esc(a.description)+'</p><small>'+esc(a.dateNote)+'</small>'+sourceButton(a.evidence)+'</li>').join('')+'</ol></section>':'')+
'<section class="detail-section"><h3>関係の根拠 / EVIDENCE GRAPH</h3>'+c.graph.edges.map(e=>'<article id="'+esc(e.id)+'" class="gap-evidence">'+kind(e)+'<h4>'+esc(c.graph.nodes.find(n=>n.id===e.from_id).label)+' → '+esc(c.graph.nodes.find(n=>n.id===e.to_id).label)+'</h4><p>'+esc(e.label)+' / '+esc(e.note)+'</p>'+sourceButton(e)+'</article>').join('')+'</section><section class="detail-section"><h3>SOURCES & EVIDENCE</h3>'+['A','B','C','D'].map(level=>{const ss=c.sources.map(id=>sourceMap.get(id)).filter(s=>s&&s.evidence_level===level);return ss.length?'<h4>'+esc(data.methodology.evidence_levels[level])+'</h4>'+ss.map(s=>'<div class="source-detail"><span class="level">'+s.evidence_level+'</span><p><button class="source-name text-button" data-source="'+esc(s.id)+'">'+esc(s.title)+' ↗</button></p><p class="small">'+esc(s.publisher)+' / '+esc(accessLabel(s))+'</p></div>').join(''):'';}).join('')+'</section>';
showDialog('case-dialog');const u=new URL(location.href);u.searchParams.set('project',id);u.searchParams.delete('source');u.searchParams.delete('claim');history.replaceState(null,'',u);if(claimId)document.getElementById(claimId)?.scrollIntoView({block:'start'});}
function sourceCard(s){const used=uses.get(s.id)||[],url=safeURL(s.url);return '<section class="source-detail"><div class="field-state"><span class="level">'+s.evidence_level+'</span><span class="small">'+esc(data.methodology.evidence_levels[s.evidence_level])+'</span></div><h3>'+esc(s.title)+'</h3><dl><dt>発行主体</dt><dd>'+esc(s.publisher)+'</dd><dt>公開日</dt><dd>'+esc(s.published_at||'資料に明記なし・未確認')+'</dd><dt>対象期間</dt><dd>'+esc(s.period||'未確認')+'</dd><dt>参照ページ・節</dt><dd>'+esc(s.locator||'個別の該当箇所は確認記録・項目注記参照')+'</dd><dt>URL</dt><dd>'+(url?link(s.url,s.access==='PUBLIC_SUMMARY_OF_INTERNAL'?'公開要約を見る（原典非公開）':'原典・資料を見る'):'原典非公開／URLなし')+'</dd><dt>公開範囲</dt><dd>'+esc(accessLabel(s))+'</dd><dt>最終確認日</dt><dd>'+esc(s.last_verified||'未確認')+'<br>'+esc(verificationLabels[s.verification_status]||s.verification_status)+'</dd><dt>リンク確認</dt><dd>'+esc(s.link_status==='REACHABLE'?'到達確認（内容の再検証とは別）':s.url?'要再確認・到達未確認':'原典非公開のため対象外')+(s.last_link_checked?' / '+esc(s.last_link_checked):'')+'</dd></dl>'+(s.note?'<p class="small">'+esc(s.note)+'</p>':'')+'<details><summary>USED IN / '+used.length+'項目</summary><ul class="used-list">'+used.map(u=>'<li>'+(u.case_id?'<button data-used-case="'+u.case_id+'" data-used-claim="'+esc(u.claim_id)+'">'+esc(u.case_name)+'</button>':'<span>全体像</span>')+'<small>'+esc(u.label)+' / '+esc(u.claim_id)+'</small></li>').join('')+'</ul></details></section>';}
function showSource({sourceId,claimId,edgeId},trigger){lastSourceTrigger=trigger?.isConnected?trigger:lastSourceTrigger;const f=claimMap.get(claimId||edgeId);const ids=sourceId?[sourceId]:f?.source_ids||[];const ss=[...new Set(ids)].map(id=>sourceMap.get(id)).filter(Boolean);
$('#source-content').innerHTML='<p class="detail-meta">'+(f?esc(f.id):esc(sourceId))+'</p><h2 id="source-title">'+esc(f?.label||ss[0]?.title||'根拠の確認状況')+'</h2>'+(f?'<div class="evidence-callout">'+kind(f)+(f.status?status(f):'')+verify(f)+(f.value!==undefined?'<div class="field-value">'+esc(displayValue(f))+'</div>':'')+'<p>'+esc(f.note||'')+'</p><p class="small">確認日 '+esc(f.last_verified||'未確認')+' / '+esc(verificationLabels[f.verification_status]||f.verification_status)+'</p>'+(f.period?'<p class="small">対象期間：'+esc(f.period)+'</p>':'')+(f.locator?'<p class="small">項目の参照箇所：'+esc(f.locator)+'</p>':'')+(f.source_fact?'<p class="small">読み取りの根拠：'+esc(f.source_fact)+'</p>':'')+'</div>':'')+(f?.formula?'<div class="formula"><b>CALCULATION</b><br>'+esc(f.formula)+'</div>':'')+(f?.inputs?'<ul class="used-list">'+f.inputs.map(i=>'<li>'+esc(i.scope||'計算入力')+'：'+esc(i.value)+(i.claim_id?'<button class="text-button" data-claim="'+esc(i.claim_id)+'">入力値のSOURCE ↗</button>':i.source_id?'<button class="text-button" data-source="'+esc(i.source_id)+'">入力値のSOURCE ↗</button>':'')+'</li>').join('')+'</ul>':'')+(f?.field_refs?.length?'<p class="small">この関係に接続する項目</p><ul class="used-list">'+f.field_refs.map(id=>claimMap.has(id)?'<li><button data-claim="'+esc(id)+'">'+esc(claimMap.get(id).label)+'の根拠 ↗</button></li>':'').join('')+'</ul>':'')+(ss.length?ss.map(sourceCard).join(''):'<p class="evidence-callout">NEEDS VERIFICATION<br>この項目を直接裏付ける原典は特定されていません。実施なし・0を意味しません。</p>');
showDialog('source-drawer');const u=new URL(location.href);u.searchParams.delete('source');u.searchParams.delete('claim');if(sourceId)u.searchParams.set('source',sourceId);else if(f)u.searchParams.set('claim',f.id);history.replaceState(null,'',u);}
function downloadCSV(){if(!data)return;const rows=qualityRows(),cell=v=>'"'+String(v??'').replaceAll('"','""')+'"',lines=[['case_id','地域','項目','確認内容','次の確認','担当','最終確認日'],...rows.map(q=>[q.case_id,caseMap.get(q.case_id)?.region,claimMap.get(q.field_id)?.label,q.reason,q.next_action,q.owner,q.checked_at])];const blob=new Blob(['\ufeff'+lines.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mobility-atlas-needs-verification-20260921.csv';a.click();URL.revokeObjectURL(url);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!data)return;
if(b.hasAttribute('data-close'))$('#'+b.dataset.close).close();
else if(b.dataset.claim)showSource({claimId:b.dataset.claim},b);
else if(b.dataset.source)showSource({sourceId:b.dataset.source},b);
else if(b.dataset.edge)showSource({edgeId:b.dataset.edge},b);
else if(b.dataset.case)showCase(b.dataset.case,b);
else if(b.dataset.usedCase)showCase(b.dataset.usedCase,null,b.dataset.usedClaim);
else if(b.dataset.graphCase){$('#case-dialog').close();$('#graph-case').value=b.dataset.graphCase;renderGraph();$('#graph').scrollIntoView();}
else if(b.hasAttribute('data-dataset')){dataset=b.dataset.dataset;if(b.hasAttribute('data-explore'))$('#filters').reset();if(dataset==='traffic'){$('#activity-filter').value='';$('#status-filter').value='';}if(dataset==='training'){$('#gap-filter').value='';$('#issue-filter').value='';}page=1;renderCases();if(b.hasAttribute('data-explore'))$('#explore').scrollIntoView();}
else if(b.dataset.gap){dataset='traffic';$('#activity-filter').value='';$('#status-filter').value='';$('#gap-filter').value=b.dataset.gap;page=1;renderCases();$('#explore').scrollIntoView();}
else if(b.dataset.issue){const f=data.social_issues.find(x=>x.label===b.dataset.issue);if(f?.case_ids?.length===0){showSource({claimId:f.id},b);return;}dataset='traffic';$('#activity-filter').value='';$('#status-filter').value='';$('#issue-filter').value=b.dataset.issue;page=1;renderCases();$('#explore').scrollIntoView();}
else if(b.dataset.pageGroup){const n=Number(b.dataset.page);if(b.dataset.pageGroup==='cases'){page=n;renderCases();$('#result-count').scrollIntoView();}else if(b.dataset.pageGroup==='sources'){sourcePage=n;renderSources();$('#source-count').scrollIntoView();}else{qualityPage=n;renderQuality();$('#quality-results').scrollIntoView();}}
});
for(const id of ['case-dialog','source-drawer'])$('#'+id).addEventListener('close',()=>{const u=new URL(location.href);if(id==='case-dialog'){u.searchParams.delete('project');if(/^#(?:r7|gap)-\d+$/.test(u.hash))u.hash='';}else{u.searchParams.delete('source');u.searchParams.delete('claim');}history.replaceState(null,'',u);if(!$$('dialog[open]').length)document.body.style.overflow='';(id==='case-dialog'?lastCaseTrigger:lastSourceTrigger)?.isConnected&&(id==='case-dialog'?lastCaseTrigger:lastSourceTrigger).focus();});
$('#filters').addEventListener('submit',e=>e.preventDefault());$('#filters').addEventListener('input',()=>{page=1;renderCases();});$('#filters').addEventListener('change',()=>{page=1;if($('#activity-filter').value||$('#status-filter').value){dataset='training';$('#gap-filter').value='';$('#issue-filter').value='';}renderCases();});$('#filters').addEventListener('reset',()=>{page=1;setTimeout(renderCases,0);});
$('#view-list').addEventListener('click',()=>{view='list';renderCases();});$('#view-table').addEventListener('click',()=>{view='table';renderCases();});
$('#source-filters').addEventListener('submit',e=>e.preventDefault());$('#source-filters').addEventListener('input',()=>{sourcePage=1;renderSources();});$('#source-filters').addEventListener('change',()=>{sourcePage=1;renderSources();});$('#quality-query').addEventListener('input',()=>{qualityPage=1;renderQuality();});$('#quality-export').addEventListener('click',downloadCSV);$('#graph-case').addEventListener('change',renderGraph);$('#reload-data').addEventListener('click',()=>location.reload());
async function load(){try{const res=await fetch('data/atlas.json',{cache:'no-cache'});if(!res.ok)throw Error('data '+res.status);data=await res.json();caseMap=new Map(data.cases.map(c=>[c.id,c]));sourceMap=new Map(data.sources.map(s=>[s.id,s]));claimMap=new Map([...data.cases.flatMap(caseClaims),...data.headline_metrics,...data.social_issues].map(f=>[f.id,f]));uses=new Map(data.sources.map(s=>[s.id,usedIn(data,s.id)]));
for(const g of data.gaps)$('#gap-filter').add(new Option(g.label+' / '+g.name,g.id));for(const f of data.social_issues)$('#issue-filter').add(new Option(f.label,f.label));
const prefs=[...new Set(data.cases.map(c=>c.region.match(/北海道|東京都|京都府|大阪府|.{2,3}県/)?.[0]).filter(Boolean))];for(const p of prefs)$('#region-filter').add(new Option(p,p));trainingFields.slice(2).forEach((k,i)=>$('#activity-filter').add(new Option(trainingLabels[i+2],k)));for(const cat of ['国','自治体','事業主体','大学','統計','計画','仕様書','報告書','Webページ','二次資料','分析'])$('#source-category').add(new Option(cat,cat));for(const c of data.cases)$('#graph-case').add(new Option(c.region+' / '+c.name,c.id));
const u=new URL(location.href);dataset=['traffic','training'].includes(u.searchParams.get('dataset'))?u.searchParams.get('dataset'):'traffic';view=u.searchParams.get('view')==='table'?'table':'list';for(const [param,id] of [['q','search'],['gap','gap-filter'],['issue','issue-filter'],['pref','region-filter'],['activity','activity-filter'],['state','status-filter']])$('#'+id).value=u.searchParams.get(param)||'';$('#needs-filter').checked=u.searchParams.get('needs')==='1';const legacyMetrics=(u.searchParams.get('metrics')||'').split(',')[0];if(legacyMetrics&&trainingFields.includes(legacyMetrics)){$('#activity-filter').value=legacyMetrics;dataset='training';$('#status-filter').value=u.searchParams.get('state')==='unverified'?'NOT_CONFIRMED':u.searchParams.get('state')==='documented'?'':'IMPLEMENTED';}
$('#graph-case').value=caseMap.has(u.searchParams.get('project'))?u.searchParams.get('project'):'gap-006';renderOverview();renderCases();renderGraph();renderSources();renderQuality();const project=u.searchParams.get('project')||(location.hash.startsWith('#r7-')?location.hash.slice(1):'');if(project)showCase(project);if(u.searchParams.get('source'))showSource({sourceId:u.searchParams.get('source')});else if(u.searchParams.get('claim'))showSource({claimId:u.searchParams.get('claim')});
}catch(error){$('#load-error').hidden=false;console.error('Atlas load failed',error);}}
load();

