'use client';
import {useState} from 'react';
import {ChevronDown,Plus,Check,Clock3,CalendarDays} from 'lucide-react';
import {TASK_GROUPS,groupKey,taskSummary,dependencyIds} from '@/lib/hierarchy';
import {candidateRows} from '@/lib/candidates';
import {RecordItem,STATUS,dateLabel,todayJST,taskLabel} from '@/lib/model';
type Props={records:RecordItem[];onOpen:(record:RecordItem)=>void;onAdd?:(groupKey:string)=>void;filter?:'all'|'due'};
export default function TaskTree({records,onOpen,onAdd,filter='all'}:Props){
 const [expanded,setExpanded]=useState<Set<string>>(()=>new Set());
 const tasks=records.filter(r=>r.kind==='task'&&!r.archived);
 const groups=[...TASK_GROUPS,...(tasks.some(r=>groupKey(r)==='unclassified')?[{id:'unclassified',title:'未分類',color:'#fff',children:[{id:'unclassified',title:'分類を確認'}]}]:[])];
 const toggle=(id:string)=>setExpanded(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
 const today=todayJST();
 function Title({record}:{record:RecordItem}){const keys=/((?:役割分担|活動方針|成果指標|参加候補|発起人|事務局|披露目|規約|会費|契約|総会|発足|実証|参画))/g;return <><span className="tree-task-number">{taskLabel(record)}</span>{record.title.split(keys).map((part,i)=>i%2?<strong key={i}>{part}</strong>:part)}</>}
 function Due({task,label='期限'}:{task?:RecordItem;label?:string}){return <span className={`tree-due ${task?.dueDate&&task.dueDate<today&&task.status!=='done'?'overdue':''}`}><small>{label}</small><b>{task?.dueDate?dateLabel(task.dueDate):'未定'}</b>{task?.dueDate&&task.dueCertainty!=='confirmed'&&<em>仮</em>}{label==='期限'&&task&&<span className="tree-status-label">{STATUS[task.status as keyof typeof STATUS]}</span>}</span>}
 function goal(id:string){if(id==='establish')return records.find(r=>r.id==='M-09'&&!r.archived);if(id==='vehicle')return records.find(r=>r.id==='M-07'&&!r.archived);return undefined}
 return <section className="task-tree" aria-label="大項目からタスクを見る"><div className="tree-toolbar"><p>項目を押すと、その下に作業が開きます。</p>{expanded.size>0&&<button onClick={()=>setExpanded(new Set())}>すべて閉じる</button>}</div>{groups.map((g,index)=>{
 const children=tasks.filter(r=>g.children.some(s=>s.id===groupKey(r)));const summary=taskSummary(children),target=goal(g.id),isOpen=expanded.has(g.id);
 return <section className="tree-group" key={g.id} style={{'--group-color':g.color} as React.CSSProperties}><button className="tree-group-row" onClick={()=>toggle(g.id)} aria-expanded={isOpen} aria-controls={`tree-${g.id}`}><span className="tree-number">{index+1}</span><span className="tree-group-main"><h2>{g.title}</h2><span className="tree-progress"><b>{summary.done}</b> / {summary.total} 件完了 {summary.undated>0&&<small>期限未定 {summary.undated}</small>}</span></span><Due task={target||summary.next} label={target?(g.id==='vehicle'?'披露目・仮の節目':'発足目標'):'次の期限'}/><ChevronDown className={isOpen?'rotated':''} size={21}/></button>
 {isOpen&&<div className="tree-branches" id={`tree-${g.id}`}>{target&&<button className="tree-milestone" onClick={()=>onOpen(target)}><CalendarDays size={15}/>{dateLabel(target.dueDate)} {target.title}<span>{target.dueCertainty==='confirmed'?'目標日':'仮・要確認'}</span></button>}{g.children.map(sub=>{const items=children.filter(r=>groupKey(r)===sub.id).sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));const ss=taskSummary(items),subOpen=true;return <div className="tree-subgroup" key={sub.id}><div className="tree-sub-row"><span className="tree-sub-main"><h3>{sub.title}</h3><small>{ss.done} / {ss.total} 件完了 {ss.undated>0?`・期限未定 ${ss.undated}`:''}</small></span><Due task={ss.next} label="次の期限"/></div>{subOpen&&<div className="tree-leaves" id={`tree-${sub.id}`}>{items.length?items.map(r=>{const waiting=dependencyIds(r,records).length;return <button className={`tree-task ${r.status==='done'?'is-done':''}`} key={r.id} onClick={()=>onOpen(r)}><span className={`tree-state state-${r.status}`}>{r.status==='done'?<Check size={16}/>:waiting||r.status==='waiting'?<Clock3 size={15}/>:<span/>}</span><span className="tree-task-main"><b><Title record={r}/>{candidateRows(r.note||'').length>0&&<small className="candidate-count">候補 {candidateRows(r.note).length}件</small>}</b><span>{r.owner||'担当未定'}{r.ownerCertainty==='tentative'?'（案）':''}{waiting?` · 前の作業 ${waiting}件待ち`:''}</span></span><Due task={r}/></button>}):<p className="tree-empty">タスクはまだありません。</p>}{onAdd&&<button className="tree-add" onClick={()=>onAdd(sub.id)}><Plus size={15}/>ここにタスクを追加</button>}</div>}</div>})}</div>}</section>})}<p className="tree-footnote">期限と進捗はタスクから自動集計。状況未確認は、未着手とは区別しています。</p></section>
}
