import {seconds} from '../lab/gtfs.mjs';
import {validateOptions} from '../access/engine.mjs';
import {csvText,download} from '../lab/io.mjs';
import {GAP_TYPES,PURPOSES,STATES,normalizeCategory,populationSummary,aggregateDemand,VERSION} from './model.mjs';
import {$,esc,fmt,time,json,link,mapAt,feedChooser,chosenFeeds,setFeeds,nearbyFeeds,guard,error,dateInputs,localRead,DEMAND_KEY} from './shared.mjs';
let boundaries,facilities=[],catalog=[],resources=[],transport,map,gridLayer,resourceLayer,targetLayer,cells=[],results=new Map(),worker,job=0,epoch=0,applied=null,complete=false,explicitFeeds=false,layers=new Map();
const currentCity=()=>boundaries.features.find(f=>f.properties.code===$('#city').value);
function cancel(){job++;worker?.terminate();worker=null;$('#run').disabled=false;$('#cancel').hidden=true;complete=false;$('#to-lab').disabled=true;$('#export').disabled=true;}
function invalidate(){cancel();results.clear();applied=null;$('#progress').textContent='条件を変更しました。再計算してください。';$('#city-result').innerHTML='';paint();renderMetrics();}
function options(){const at=seconds($('#activity-time').value+':00');const o={departure:seconds($('#departure').value+':00'),activityFrom:at,activityTo:at,dwell:Number($('#dwell').value),deadline:seconds($('#deadline').value+':00'),legMinutes:Number($('#leg-minutes').value),maxTransfers:Number($('#transfers').value),maxWalk:Number($('#max-walk').value),totalWalk:Number($('#total-walk').value),walkSpeed:$('#profile').value==='slow'?2.5:4,walkFactor:1.3,wheelchair:$('#profile').value==='wheelchair',reservation:$('#reservation').value,budget:null};validateOptions(o);return o;}
function fillFacilities(){const code=$('#city').value,category=$('#category').value;const matching=facilities.filter(f=>normalizeCategory(f.category)===category).sort((a,b)=>Number(b.municipalityCode===code)-Number(a.municipalityCode===code)||a.name.localeCompare(b.name,'ja'));$('#facility').innerHTML=matching.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}（${esc(f.city)}）</option>`).join('');if(!matching.length)$('#facility').innerHTML='<option value="">この種類の施設は未収録です</option>';}
function autoFeeds(){if(explicitFeeds)return;const bounds=L.geoJSON(currentCity()).getBounds();const indices=new Set(transport.stops.filter(s=>bounds.contains([s.lat,s.lon])).map(s=>s.feedIndex)),hashes=new Set([...indices].map(i=>transport.feeds[i].sha256));const f=facilities.find(f=>f.id===$('#facility').value);const near=f?nearbyFeeds(catalog,transport,[f]):[];setFeeds(catalog.filter(f=>hashes.has(f.sha256)||near.some(x=>x.file===f.file)));}
function cellDetail(p){const r=results.get(p.id);return `<b>${esc(p.city)} · ${esc(p.meshCode)}</b><p>${STATES[r?.state??'unknown'].label}</p><p>2020年基準人口 ${p.population2020===null?'未集計':fmt(p.population2020)+'人'}</p>${r?.homeAt?`<p>帰宅候補 ${time(r.homeAt)}</p>`:''}${r?.reasons?.length?`<p>${esc(r.reasons.join(' / '))}</p>`:''}<small>約1km区域内の代表点。住民全員の判定ではありません。</small>`;}
function paint(){for(const [id,l]of layers){const state=results.get(id)?.state??'unknown';l.setStyle({fillColor:STATES[state].color,fillOpacity:state==='unknown'?.13:.5,color:state==='unknown'?'#999':STATES[state].color,weight:.7});}}
function renderMetrics(){const s=populationSummary(cells,results);$('#city-metrics').innerHTML=`<div><span>往復候補の人口割合</span><b>${applied?fmt(s.rate,1):'—'}<small> %</small></b></div><div><span>候補がない区域の人口</span><b>${applied?fmt(s.notFoundPopulation):'—'}<small> 人</small></b></div><div><span>判定保留の区域人口</span><b>${applied?fmt(s.unknownPopulation):'—'}<small> 人</small></b></div>`;if(applied)$('#city-result').innerHTML=`<p class="note">${complete?'計算完了':'計算中・暫定値'}。人口を取得できた対象区域 ${fmt(s.knownPopulation)}人を分母に集計（2020年基準・調整値）。人口未集計 ${s.missingPopulationCells}区域は人口割合から除外。判定保留の人口も分母に含みます。</p><p class="note">往復候補あり ${s.counts.candidate}区域 ／ 収録条件では見つからない ${s.counts.not_found}区域 ／ 未計算・保留 ${s.counts.unknown}区域。施設の受付・費用・実際の歩行経路は未確認です。</p>`;}
function renderResources(){resourceLayer.clearLayers();const rows=resources.filter(r=>r.city===currentCity().properties.name);for(const r of rows)L.circleMarker([r.lat,r.lon],{radius:7,weight:2,color:'#745211',fillColor:'#e7ff38',fillOpacity:1}).addTo(resourceLayer).bindPopup(`<b>${esc(r.name)}</b><p>${esc(r.eligibleUsers)}</p><p>${esc(r.reservationNote??'予約条件は要確認')}</p><p>${link(r.sourceUrl,'公表資料')}</p><small>公表事例。一般利用・共用の合意は未確認。</small>`);$('#resource-list').innerHTML=rows.map(r=>`<article class="resource-card"><span class="tag">公表情報を確認 / 共用は未確認</span><h3>${esc(r.name)}</h3><p><b>対象：</b>${esc(r.eligibleUsers)}</p><p><b>予約：</b>${esc(r.reservationNote??'要確認')}</p><p>確認日：${esc(r.checkedAt)}</p>${link(r.sourceUrl,'出典を見る')}</article>`).join('')||'<p>この市町村の送迎事例は未収録です。資源が存在しないことを意味しません。</p>';}
async function loadCity(){const e=++epoch;invalidate();explicitFeeds=false;$('#run').disabled=true;fillFacilities();autoFeeds();map.fitBounds(L.geoJSON(currentCity()).getBounds(),{padding:[15,15]});renderResources();$('#map-scope').textContent=currentCity().properties.name+' / 約1kmメッシュ';const data=await json('gaps/data/'+$('#city').value+'-1000.geojson');if(e!==epoch)return;cells=data.features.filter(f=>f.properties.populated2020);gridLayer.clearLayers();layers.clear();L.geoJSON({type:'FeatureCollection',features:cells},{style:{color:'#aaa',weight:.7,fillColor:'#75808c',fillOpacity:.13},onEachFeature:(f,l)=>{layers.set(f.properties.id,l);l.bindPopup(()=>cellDetail(f.properties));}}).addTo(gridLayer);renderMetrics();$('#run').disabled=false;$('#progress').textContent=cells.length+'区域を計算できます。条件を確認してください。';}
function drawTarget(){targetLayer.clearLayers();const f=facilities.find(p=>p.id===$('#facility').value);if(f)L.circleMarker([f.lat,f.lon],{radius:9,weight:2,color:'#111',fillColor:'#72d7ff',fillOpacity:1}).addTo(targetLayer).bindPopup(esc(f.name));}
function run(e){e.preventDefault();cancel();$('#error').hidden=true;const o=options(),facility=facilities.find(f=>f.id===$('#facility').value),files=chosenFeeds(catalog);if(!facility)throw Error('今回調べる目的地を選んでください');if(!files.length)throw Error('使う時刻表を選んでください');if(!cells.length)throw Error('対象区域がありません');results.clear();complete=false;applied={schema:'oita-atlas-baseline/2',version:VERSION,cityCode:$('#city').value,cityName:currentCity().properties.name,facility,date:$('#date').value,options:o,files,profile:$('#profile').value,created:new Date().toISOString()};const id=++job;worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});$('#run').disabled=true;$('#cancel').hidden=false;drawTarget();paint();renderMetrics();$('#map-scope').textContent=applied.cityName+' → '+facility.name+' / '+applied.date;
 worker.onmessage=({data:d})=>{if(d.id!==job)return;if(d.error){cancel();error(d.error);return;}if(d.progress)$('#progress').textContent=d.progress;if(d.batch){for(const item of d.batch){results.set(item.id,item.result);const l=layers.get(item.id);if(l)l.setStyle({fillColor:STATES[item.result.state].color,color:STATES[item.result.state].color,fillOpacity:.48});}renderMetrics();}if(d.done){complete=true;applied.evidence=d.evidence;$('#run').disabled=false;$('#cancel').hidden=true;$('#to-lab').disabled=false;$('#export').disabled=false;$('#progress').textContent='計算が完了しました。条件と出典を添えて保存できます。';renderMetrics();}};worker.onerror=()=>{cancel();error('計算を続けられませんでした。条件を確認してください。');};worker.postMessage({id,mode:'city',date:applied.date,options:o,files,cases:cells.map(f=>({id:f.properties.id,home:{name:f.properties.city+'の区域代表点',lat:f.properties.lat,lon:f.properties.lon},facility}))});}
function demandRows(){const raw=localRead(DEMAND_KEY,[]);return Array.isArray(raw)?raw:[];}
function renderDemand(){const records=demandRows(),groups=aggregateDemand(records);$('#demand-summary').innerHTML=groups.length?`<div style="overflow:auto"><table><thead><tr><th>出発エリア</th><th>目的</th><th>希望時間帯</th><th>記録区分</th><th>件数</th></tr></thead><tbody>${groups.slice(0,100).map(r=>`<tr><td>${esc(boundaries.features.find(f=>f.properties.code===r.cityCode)?.properties.name??r.cityCode)}</td><td>${esc(PURPOSES[r.category])}</td><td>${esc(r.hour)}</td><td>${r.kind==='search'?'検索：'+STATES[r.state].label:r.kind==='reported_unmet'?'本人申告：移動できなかった':'本人申告：移動できた'}</td><td>${fmt(r.count)}</td></tr>`).join('')}</tbody></table></div>`:'<p>まだ記録はありません。PEOPLEの検索結果から、任意で記録できます。</p>';}
async function start(){dateInputs();[boundaries,facilities,catalog,resources,transport]=await Promise.all([json('gaps/data/municipalities.geojson'),json('access/destinations.json'),json('data/gtfs/catalog.json'),json('gaps/resources.json'),json('data/map-data.json')]);map=mapAt('city-map');gridLayer=L.layerGroup().addTo(map);resourceLayer=L.layerGroup().addTo(map);targetLayer=L.layerGroup().addTo(map);$('#city').innerHTML=boundaries.features.map(f=>`<option value="${f.properties.code}">${esc(f.properties.name)}</option>`).join('');$('#city').value='44201';$('#feeds').innerHTML=feedChooser(catalog);$('#gap-types').innerHTML=GAP_TYPES.map(([id,name,desc],i)=>`<div><b>${String(i+1).padStart(2,'0')} ${name}</b><span>${desc}</span></div>`).join('');
 $('#city').onchange=guard(loadCity);$('#category').onchange=()=>{fillFacilities();invalidate();autoFeeds();drawTarget();};$('#facility').onchange=()=>{invalidate();autoFeeds();drawTarget();};for(const id of ['date','departure','activity-time','dwell','deadline','transfers','max-walk','total-walk','leg-minutes','reservation'])$('#'+id).addEventListener('input',invalidate);$('#profile').onchange=()=>{$('#max-walk').value=$('#profile').value==='slow'?250:500;$('#total-walk').value=$('#profile').value==='slow'?1000:2000;invalidate();};$('#feeds').onchange=()=>{explicitFeeds=true;invalidate();};$('#city-form').onsubmit=guard(run);$('#cancel').onclick=()=>{cancel();$('#progress').textContent='計算を中止しました。未計算区域は灰色で残しています。';renderMetrics();};$('#show-resources').onchange=e=>e.target.checked?resourceLayer.addTo(map):map.removeLayer(resourceLayer);
 $('#to-lab').onclick=guard(()=>{if(!complete)throw Error('計算を完了してください');const baseline={...applied,cells:cells.map(f=>f.properties),results:Object.fromEntries([...results].map(([id,r])=>[id,{state:r.state,homeAt:r.homeAt??null}])),summary:populationSummary(cells,results)};try{sessionStorage.setItem('oita-atlas-baseline-v2',JSON.stringify(baseline));}catch{throw Error('このブラウザでは比較条件を引き継げません。保存設定を確認してください。');}location.href='policy.html';});
 $('#export').onclick=guard(()=>{if(!complete)throw Error('計算を完了してください');download('oita-accessibility-'+applied.cityCode+'.csv','\ufeff'+csvText(cells.map(f=>{const r=results.get(f.properties.id);return {municipality:applied.cityName,mesh:f.properties.meshCode,population_2020:f.properties.population2020??'',status:STATES[r.state].label,facility:applied.facility.name,date:applied.date,departure:time(applied.options.departure),activity:time(applied.options.activityFrom),dwell:applied.options.dwell,deadline:time(applied.options.deadline),return_candidate:time(r.homeAt),conditions:JSON.stringify(applied.options),unconfirmed:r.unknowns.join(' / '),gtfs_hashes:applied.files.map(f=>f.sha256).join(' | '),population_source:'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-mesh500r6.html',data_scope:'公開データ・2020年基準人口・代表点。実利用者ではない。',source_notes:'https://mobilitydlab.com/oita-mobility/usage.html',engine:VERSION};}),{safe:true}),'text/csv;charset=utf-8');});
 $('#demand-export').onclick=guard(()=>{const rows=aggregateDemand(demandRows(),{threshold:5});if(!rows.length)throw Error('同一条件の記録が5件以上ある集計はありません。少数の記録は外部共有用CSVから除外します。');download('oita-mobility-demand-aggregated.csv','\ufeff'+csvText(rows.map(r=>({...r,meaning:'任意記録の件数。実人数ではない。少数集計を除外。'})),{safe:true}),'text/csv;charset=utf-8');});$('#demand-clear').onclick=()=>{if(confirm('この端末に保存した移動の記録をすべて削除しますか？')){localStorage.removeItem(DEMAND_KEY);renderDemand();}};await loadCity();drawTarget();renderDemand();document.documentElement.dataset.atlasReady='true';}
guard(start)();
