import {setupArea} from './area.mjs';
import {distance,seconds} from '../lab/gtfs.mjs';
import {validateOptions} from '../access/engine.mjs';
import {download,csvText} from '../lab/io.mjs';
import {PURPOSES,STATES,normalizeCategory,classify,diagnosis,demandRecord,cityAt,validPoint,localDay,opportunitySummary,pointInGeometry} from './model.mjs';
import {$,esc,fmt,time,json,link,mapAt,nearbyFeeds,feedChooser,chosenFeeds,setFeeds,error,guard,dateInputs,localRead,localWrite,DEMAND_KEY} from './shared.mjs';
const oldAnchors=['map','ridership','od','forecast','cost','bc','sources','start'];
if(oldAnchors.includes(location.hash.slice(1))&&location.hash!=='#start')location.replace('analysis.html'+location.search+location.hash);
let facilities=[],catalog=[],transport,boundaries,resources=[],map,placesLayer,homeLayer,destLayer,routeLayer,resourceLayer,home=null,target=null,picking=null,explicitFeeds=false,worker=null,job=0,currentResult=null,currentRequest=null,originOptions=[],savedKinds=new Set(),selectedArea=null;
const label=f=>f.city?`${f.name}（${f.city}）`:f.name;
function clearError(){$('#error').hidden=true;}
function cancel(){job++;worker?.terminate();worker=null;$('#search-button').disabled=false;$('#opportunity-run').disabled=false;$('#cancel').hidden=true;$('#progress').textContent='';}
function invalidate(){cancel();currentResult=null;currentRequest=null;savedKinds.clear();routeLayer?.clearLayers();$('#result').innerHTML='<div class="empty-result"><span>YOUR JOURNEY</span><h2>条件を選んで、往復を確認。</h2><p>結果には、使った時刻表と確認が必要な条件も表示します。</p></div>';$('#opportunity-results').innerHTML='<p>現在の出発条件で「生活機会を調べる」を押してください。</p>';}
function chooseFeeds(){if(explicitFeeds)return;const pts=[home,target].filter(Boolean);setFeeds(nearbyFeeds(catalog,transport,pts));}
function drawPoints(){homeLayer.clearLayers();destLayer.clearLayers();if(home)L.circleMarker([home.lat,home.lon],{radius:9,color:'#111',weight:2,fillColor:'#ff4fc3',fillOpacity:1}).addTo(homeLayer).bindPopup('出発地');if(target)L.circleMarker([target.lat,target.lon],{radius:9,color:'#111',weight:2,fillColor:'#72d7ff',fillOpacity:1}).addTo(destLayer).bindPopup(esc(target.name));}
function setHome(p,text){if(!validPoint(p))throw Error('大分県内または近隣の出発地を選んでください');invalidate();home={...p,name:text??p.name};$('#origin').value=text??label(p);drawPoints();chooseFeeds();if(target)map.fitBounds([[home.lat,home.lon],[target.lat,target.lon]],{padding:[35,35],maxZoom:14});else map.setView([home.lat,home.lon],13);}
function setTarget(p){invalidate();target={...p};$('#destination').value=label(p);drawPoints();chooseFeeds();if(home)map.fitBounds([[home.lat,home.lon],[target.lat,target.lon]],{padding:[35,35],maxZoom:14});else map.setView([target.lat,target.lon],13);map.closePopup();}
function resolveInput(value,list){return list.find(p=>label(p)===value)??(list.filter(p=>p.name===value).length===1?list.find(p=>p.name===value):null);}
function options(){const o={departure:seconds($('#departure').value+':00'),activityFrom:seconds($('#activity-time').value+':00'),activityTo:seconds($('#activity-time').value+':00'),dwell:Number($('#dwell').value),deadline:seconds($('#deadline').value+':00'),legMinutes:Number($('#leg-minutes').value),maxTransfers:Number($('#transfers').value),maxWalk:Number($('#max-walk').value),totalWalk:Number($('#total-walk').value),walkSpeed:$('#profile').value==='slow'?2.5:4,walkFactor:1.3,wheelchair:$('#profile').value==='wheelchair',reservation:$('#reservation').value,budget:null};validateOptions(o);return o;}
function resolvePlaces(needTarget=true){if(!home){const p=resolveInput($('#origin').value,originOptions);if(p)setHome(p);}if(needTarget&&!target){const p=resolveInput($('#destination').value,facilities);if(p)setTarget(p);}if(!home)throw Error('出発地を候補から選ぶか、地図・現在地で指定してください');if(needTarget&&!target)throw Error('目的地を候補から選ぶか、地図から指定してください');}
function startJob(request,onDone){cancel();clearError();const id=++job;worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});$('#search-button').disabled=true;$('#opportunity-run').disabled=true;$('#cancel').hidden=false;$('#progress').textContent='時刻表を準備しています…';worker.onmessage=({data:d})=>{if(d.id!==job)return;if(d.error){cancel();error(d.error);return;}if(d.progress)$('#progress').textContent=d.progress;if(d.done){$('#search-button').disabled=false;$('#opportunity-run').disabled=false;$('#cancel').hidden=true;$('#progress').textContent='計算が完了しました。';onDone(d);}};worker.onerror=()=>{cancel();error('計算を続けられませんでした。条件や時刻表を減らしてお試しください。');};worker.postMessage({id,...request});}
function pathHTML(path){return path.filter(l=>l.mode==='bus'||l.meters>5).map(l=>l.mode==='bus'?`<li><b>${time(l.departure)} → ${time(l.arrival)}　${esc(l.routeName)}</b>${esc(l.from.name)} → ${esc(l.to.name)}<br><small>乗る前の待ち ${fmt(l.wait/60)}分</small></li>`:`<li><b>${time(l.departure)} → ${time(l.arrival)}　徒歩 約${fmt(l.meters)}m</b><small>${esc(l.from.name??'地点')} → ${esc(l.to.name??'地点')}</small></li>`).join('');}
function renderResult(r,request){currentResult=r;currentRequest=request;savedKinds.clear();const s=classify(r),hasRoute=!!(r.outbound&&r.inbound);let status=STATES[s].label;if(hasRoute&&s==='candidate')status=r.unknowns?.length?'往復候補あり・利用条件を確認':'時刻表上の往復候補が見つかりました';
 const city=cityAt(request.home,boundaries.features);const hasCity=!!city;const tags=diagnosis(r).map(x=>({time:'時間の制約',destination:'目的地へのアクセス',return:'帰りの便・帰宅期限',use:'本人の利用条件'})[x]).filter(Boolean);
 $('#result').innerHTML=`<article class="journey-card"><span class="result-state ${s}">${status}</span><h2>${esc(request.home.name??'出発地')} → ${esc(r.facilityName)}</h2>${hasRoute?`<div class="route-time">${time(r.outbound.path[0]?.departure)} → ${time(r.outbound.arrival)}<small>行き 約${fmt((r.outbound.arrival-request.options.departure)/60)}分</small></div><p class="result-metrics"><span>往復の徒歩 約${fmt(r.walk)}m</span><span>運賃：未確認</span></p><p><b>用事 ${time(r.begin)}〜${time(r.end)}</b>（${request.options.dwell}分）<br><b>帰宅候補 ${time(r.homeAt)}</b> ／ ${time(request.options.deadline)}までに帰宅</p><details open><summary>行き・用事・帰りの時刻を見る</summary><ol class="timeline">${pathHTML(r.outbound.path)}<li class="activity"><b>${time(r.begin)}〜${time(r.end)}　${esc(r.facilityName)}</b>用事・滞在${request.options.dwell}分</li>${pathHTML(r.inbound.path)}</ol></details>`:`<p>${esc(r.reasons.join(' / '))}</p>${tags.length?`<p><b>確認する課題：</b>${esc(tags.join('・'))}</p>`:''}<p class="note">未収録の交通や、別の時刻・目的地は未評価です。「公共交通で行けない」とは断定できません。</p>`}<details class="evidence"><summary>この判定の根拠・まだ確認が必要なこと</summary><ul>${r.unknowns.map(x=>`<li>${esc(x)}</li>`).join('')}<li>当日の運休・遅延・満席</li><li>運賃と最終帰宅便は未確定。表示は指定した出発・帰宅期限内の候補です。</li>${r.searchIncomplete?'<li>探索に上限があり、候補を網羅していません。</li>':''}</ul><p>使用日：${esc(request.date)} ／ 2026年9月8日取得の公開時刻表</p><ul>${r.dataEvidence.feeds.map(f=>`<li>${esc(f.name)}：${f.coverage==='known'?'有効期間内':f.coverage==='outside'?'有効期間外':'期間未確認'}</li>`).join('')}</ul>${link(r.facility.sourceUrl??r.facility.url,'施設位置の出典')}<p><a href="data-catalog.html">全データと利用条件を確認 →</a></p></details><div class="save-demand"><h3>この移動を、改善につなげる</h3><p>${hasCity?esc(city.name)+'・目的の種類・希望時間帯・判定・記録区分・記録月をこの端末に保存します。':'出発地の市町村を確定できないため記録は保存しません。'}住所・施設名・正確な時刻は記録せず、自動送信しません。</p><div class="button-row"><button class="quiet" data-save="search" ${hasCity?'':'disabled'}>検索結果を記録</button><button class="quiet" data-save="reported_unmet" ${hasCity?'':'disabled'}>実際には行けなかった</button><button class="quiet" data-save="reported_met" ${hasCity?'':'disabled'}>実際に移動できた</button></div><p id="save-status" role="status"></p><a href="atlas.html#demand">記録の集計を見る →</a></div></article>`;
 routeLayer.clearLayers();if(hasRoute){for(const l of [...r.outbound.path,...r.inbound.path])L.polyline([[l.from.lat,l.from.lon],[l.to.lat,l.to.lon]],{color:l.mode==='walk'?'#936740':'#111',weight:l.mode==='walk'?3:4,dashArray:l.mode==='walk'?'4 6':null,opacity:.7}).addTo(routeLayer).bindPopup('起終点を結ぶ概略線。道路・走行経路ではありません。');}$('#result').scrollIntoView({behavior:'smooth',block:'start'});
}
function areaFacilities(){return !selectedArea||$('#other-cities').checked?facilities:facilities.filter(f=>String(f.municipalityCode)===selectedArea.properties.code||f.city===selectedArea.properties.name);}
function renderAreaFacilities(){const pool=areaFacilities();$('#destination-list').innerHTML=pool.map(p=>`<option value="${esc(label(p))}"></option>`).join('');placesLayer.clearLayers();for(const p of pool)L.circleMarker([p.lat,p.lon],{radius:4,color:'#1b606e',weight:1,fillColor:'#72d7ff',fillOpacity:.8}).addTo(placesLayer).bindPopup(`<b>${esc(p.name)}</b><p>${esc(p.city)} · ${esc(PURPOSES[normalizeCategory(p.category)])}</p><button class="quiet" data-target="${esc(p.id)}">ここへ行く →</button>`);$('#facility-count').textContent=pool.length;$('#facility-scope').textContent=$('#other-cities').checked?'県内の収録施設':'この地域の収録施設';}
function chooseArea(area,position){selectedArea=area;$('#selected-area-label').textContent=area.properties.name+' / 大分県';home=null;target=null;picking=null;explicitFeeds=false;$('#origin').value='';$('#destination').value='';$('#other-cities').checked=false;invalidate();for(const id of ['people-work','opportunity-section','next-steps'])$('#'+id).hidden=false;drawPoints();const bounds=L.geoJSON(area).getBounds();map.invalidateSize();map.fitBounds(bounds,{padding:[20,20],animate:false});const origins=originOptions.filter(p=>bounds.contains([p.lat,p.lon])&&pointInGeometry(p,area.geometry));$('#origin-list').innerHTML=origins.map(p=>`<option value="${esc(label(p))}"></option>`).join('');renderAreaFacilities();setFeeds(nearbyFeeds(catalog,transport,origins));document.querySelectorAll('a[href^="atlas.html"]').forEach(a=>{const hash=a.hash;a.setAttribute('href','atlas.html?city='+area.properties.code+hash);});$('#map-note').textContent=area.properties.name+'を表示しています。地図から出発地点を選ぶこともできます。';if(position)setHome(position);}
function resourcePopup(r){return `<b>${esc(r.name)}</b><p>${esc(r.eligibleUsers)}</p><p>${esc(r.reservationNote??'予約・運行条件は未確認')}</p><small>公表事例。一般利用・共同利用は未確認。</small><p>${link(r.sourceUrl,'公表資料')}</p>`;}
async function start(){dateInputs();[facilities,catalog,transport,boundaries,resources]=await Promise.all([json('access/destinations.json'),json('data/gtfs/catalog.json'),json('data/map-data.json'),json('gaps/data/municipalities.geojson'),json('gaps/resources.json')]);map=mapAt('people-map');placesLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);homeLayer=L.layerGroup().addTo(map);destLayer=L.layerGroup().addTo(map);resourceLayer=L.layerGroup();
 for(const p of facilities)L.circleMarker([p.lat,p.lon],{radius:4,color:'#1b606e',weight:1,fillColor:'#72d7ff',fillOpacity:.8}).addTo(placesLayer).bindPopup(`<b>${esc(p.name)}</b><p>${esc(p.city)} · ${esc(PURPOSES[normalizeCategory(p.category)])}</p><button class="quiet" data-target="${esc(p.id)}">ここへ行く →</button>`);
 for(const r of resources.filter(validPoint))L.circleMarker([r.lat,r.lon],{radius:7,color:'#73520c',weight:2,fillColor:'#e7ff38',fillOpacity:1}).addTo(resourceLayer).bindPopup(resourcePopup(r));
 $('#facility-count').textContent=facilities.length;$('#resource-count').textContent=resources.length;$('#feed-count').textContent=catalog.length;$('#feeds').innerHTML=feedChooser(catalog);
 const seen=new Set();const stops=transport.stops.filter(s=>{const k=s.name+'|'+s.lat.toFixed(3)+'|'+s.lon.toFixed(3);if(seen.has(k))return false;seen.add(k);return true;}).map(s=>({...s,name:s.name+'［バス停 '+transport.feeds[s.feedIndex].name.replace('GTFSデータ','')+'］'}));originOptions=[...facilities,...stops];$('#origin-list').innerHTML=originOptions.map(p=>`<option value="${esc(label(p))}"></option>`).join('');$('#destination-list').innerHTML=facilities.map(p=>`<option value="${esc(label(p))}"></option>`).join('');
 $('#origin').addEventListener('input',()=>{home=null;invalidate();drawPoints();});$('#origin').addEventListener('change',guard(()=>{const p=resolveInput($('#origin').value,originOptions);if(p)setHome(p);}));$('#destination').addEventListener('input',()=>{target=null;invalidate();drawPoints();});$('#destination').addEventListener('change',guard(()=>{const p=resolveInput($('#destination').value,facilities);if(p)setTarget(p);}));
 for(const id of ['date','departure','activity-time','dwell','deadline','transfers','max-walk','total-walk','leg-minutes','reservation'])$('#'+id).addEventListener('input',invalidate);
 $('#profile').onchange=()=>{$('#max-walk').value=$('#profile').value==='slow'?250:500;$('#total-walk').value=$('#profile').value==='slow'?1000:2000;invalidate();};$('#feeds').onchange=()=>{explicitFeeds=true;invalidate();};
 $('#pick-origin').onclick=()=>{picking='origin';$('#map-note').textContent='出発地にしたい地点を地図で押してください。';$('#people-map').scrollIntoView({block:'center',behavior:'smooth'});};$('#pick-destination').onclick=()=>{picking='destination';$('#map-note').textContent='目的地にしたい地点を地図で押してください。';$('#people-map').scrollIntoView({block:'center',behavior:'smooth'});};
 map.on('click',guard(e=>{if(!picking)return;const p={lat:e.latlng.lat,lon:e.latlng.lng,name:picking==='origin'?'地図で指定した出発地':'地図で指定した目的地',id:'map-destination',category:'other'};if(!validPoint(p))throw Error('大分県の周辺で選んでください');if(picking==='origin')setHome(p);else setTarget(p);picking=null;$('#map-note').textContent='地点を設定しました。往復の条件を確認して検索してください。';}));
 $('#current-location').onclick=()=>{clearError();if(!navigator.geolocation){error('現在地に対応していません。地図から選んでください。');return;}$('#progress').textContent='現在地を確認しています…';navigator.geolocation.getCurrentPosition(guard(pos=>{setHome({lat:pos.coords.latitude,lon:pos.coords.longitude,name:'現在地'});$('#progress').textContent='現在地を設定しました。';}),()=>{error('現在地を取得できません。地図または施設名から選んでください。');$('#progress').textContent='';},{timeout:10000,maximumAge:60000});};
 $('#now').onclick=()=>{const d=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d);$('#date').value=localDay(d);$('#departure').value=parts;const v=Math.min(23*60+59,Number(parts.slice(0,2))*60+Number(parts.slice(3))+60);$('#activity-time').value=String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0');$('#deadline').value='23:59';invalidate();};$('#tomorrow').onclick=()=>{$('#date').value=localDay(new Date(Date.now()+86400000));invalidate();};
 $('#fit').onclick=()=>map.setView([33.25,131.4],9);$('#show-resources').onchange=e=>e.target.checked?resourceLayer.addTo(map):map.removeLayer(resourceLayer);$('#cancel').onclick=()=>{cancel();$('#progress').textContent='計算を中止しました。';};
 $('#purpose-chips').addEventListener('click',e=>{const b=e.target.closest('[data-purpose]');if(!b)return;invalidate();const matches=areaFacilities().filter(p=>normalizeCategory(p.category)===b.dataset.purpose).sort((a,b)=>home?distance(home,a)-distance(home,b):a.name.localeCompare(b.name,'ja'));$('#destination-list').innerHTML=matches.map(p=>`<option value="${esc(label(p))}"></option>`).join('');$('#result').innerHTML=`<div class="journey-card"><span class="eyebrow">${esc(PURPOSES[b.dataset.purpose])}</span><h2>${home?'出発地の近くから':'収録している施設から'}選ぶ</h2><p class="note">近くの施設は、通える施設とは限りません。</p><div class="button-row">${matches.slice(0,8).map(p=>`<button class="quiet" data-target="${esc(p.id)}">${esc(p.name)}</button>`).join('')}</div><a href="accessibility.html?category=${encodeURIComponent(b.dataset.purpose)}">全施設を一覧・地図で探す ↗</a></div>`;$('#destination').focus();});
 document.addEventListener('click',guard(e=>{const p=e.target.closest('[data-target]');if(p){const f=facilities.find(f=>f.id===p.dataset.target);if(f)setTarget(f);}const save=e.target.closest('[data-save]');if(save&&currentResult&&currentRequest){const kind=save.dataset.save;if(savedKinds.has(kind))return;if(kind.startsWith('reported_')&&[...savedKinds].some(k=>k.startsWith('reported_')))throw Error('この検索についての実移動の申告は、すでに記録しています。');const area=cityAt(currentRequest.home,boundaries.features);if(!area)throw Error('出発地の市町村を確定できません');const record=demandRecord({cityCode:area.code,category:currentResult.facility.category,hour:currentRequest.options.activityFrom,state:classify(currentResult),kind});const existing=localRead(DEMAND_KEY,[]);localWrite(DEMAND_KEY,[...existing,record].slice(-5000));savedKinds.add(kind);save.disabled=true;$('#save-status').textContent='この端末に記録しました。実人数としては集計しません。';}}));
 $('#journey-form').addEventListener('submit',guard(e=>{e.preventDefault();resolvePlaces();const o=options(),files=chosenFeeds(catalog);const request={mode:'journey',home:{...home},facilities:[{...target}],date:$('#date').value,options:o,files};startJob(request,d=>renderResult(d.results[0].result,request));}));
 $('#opportunity-run').onclick=guard(()=>{resolvePlaces(false);const o=options(),files=chosenFeeds(catalog);if(!files.length)throw Error('使う時刻表を確認してください');const request={mode:'opportunities',home:{...home},facilities,date:$('#date').value,options:o,files};startJob(request,d=>{const cats=Object.entries(PURPOSES).filter(([k])=>k!=='other');$('#opportunity-results').innerHTML=`<table><thead><tr><th>生活機会</th><th>30分以内</th><th>60分以内</th><th>収録施設</th></tr></thead><tbody>${cats.map(([k,name])=>{const rows=d.results.filter(r=>normalizeCategory(r.category)===k);return `<tr><th>${name}</th><td><b>${opportunitySummary(rows,30).label}</b>${opportunitySummary(rows,30).unknown?'<small> ／ '+opportunitySummary(rows,30).unknown+'施設は判定保留</small>':''}</td><td><b>${opportunitySummary(rows,60).label}</b>${opportunitySummary(rows,60).unknown?'<small> ／ '+opportunitySummary(rows,60).unknown+'施設は判定保留</small>':''}</td><td>${rows.length}</td></tr>`;}).join('')}</tbody></table><p class="note">${esc(request.date)} ${time(o.departure)}出発。徒歩・待ち時間・最大${o.maxTransfers}回の乗換を含む行きの候補。帰り・受付・運賃は未評価。0件は施設や交通の不存在を意味しません。</p><details class="evidence"><summary>使用時刻表と候補施設</summary><p>${d.evidence.feeds.map(f=>esc(f.name)+'（'+esc(f.coverage==='known'?'有効期間内':f.coverage==='outside'?'有効期間外・計算対象外':'有効期間不明・計算対象外')+'）').join(' / ')}</p><ul>${d.results.filter(r=>r.minutes!==null).sort((a,b)=>a.minutes-b.minutes).map(r=>`<li><button class="quiet" data-target="${esc(r.id)}">${esc(r.name)}：約${fmt(r.minutes)}分 → 往復を確認</button></li>`).join('')||'<li>収録条件内の候補は見つかりませんでした。</li>'}</ul></details>`;$('#opportunity-results').scrollIntoView({behavior:'smooth',block:'center'});});});
 setupArea(boundaries,chooseArea);$('#current-location').onclick=()=>$('#area-current').click();$('#other-cities').onchange=()=>{invalidate();if(target&&!$('#other-cities').checked&&!areaFacilities().some(f=>f.id===target.id)){target=null;$('#destination').value='';drawPoints();}renderAreaFacilities();};
 document.documentElement.dataset.atlasReady='true';
}
guard(start)();
