import {seconds} from '../lab/gtfs.mjs';
import {download,csvText} from '../lab/io.mjs';
import {VERSION,populationSummary,comparePopulation,policyCost} from './model.mjs';
import {$,esc,fmt,time,guard,error} from './shared.mjs';
const strategies=[['bus','バスの増便・時刻変更','収録時刻表から再計算'],['demand','デマンド交通','改善人口の仮定で比較'],['taxi','タクシー補助','改善人口の仮定で比較'],['rideshare','公共ライドシェア','改善人口の仮定で比較'],['shared','施設送迎の地域開放','改善人口の仮定で比較'],['elevator','横のエレベーター','改善人口の仮定で比較'],['epalette','e-Paletteの活用','改善人口の仮定で比較'],['service','施設の時間変更・配達','改善人口の仮定で比較']];
let baseline=null,strategy='bus',trips=[],worker=null,job=0,rows=[];
try{baseline=JSON.parse(sessionStorage.getItem('oita-atlas-baseline-v2')??'null');if(baseline?.schema!=='oita-atlas-baseline/2'||!baseline.cells?.length||!baseline.files?.length)baseline=null;}catch{baseline=null;}
function stop(){job++;worker?.terminate();worker=null;$('#simulate').disabled=!baseline;$('#cancel').hidden=true;}
function startWorker(request,done){stop();$('#error').hidden=true;const id=++job;worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});$('#simulate').disabled=true;$('#cancel').hidden=false;worker.onmessage=({data:d})=>{if(d.id!==job)return;if(d.error){stop();error(d.error);return;}if(d.progress)$('#progress').textContent=d.progress;if(d.done){$('#simulate').disabled=!baseline;$('#cancel').hidden=true;$('#progress').textContent='計算が完了しました。';done(d);}};worker.onerror=()=>{stop();error('計算を続けられませんでした。');};worker.postMessage({id,...request});}
function selectStrategy(id){stop();strategy=id;document.querySelectorAll('[data-strategy]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.strategy===id)));$('#timetable-fields').hidden=id!=='bus';$('#assumption-fields').hidden=id==='bus';$('#trip').required=id==='bus';$('#new-time').required=id==='bus';$('#after-population').required=id!=='bus';$('#assumption-source').required=id!=='bus';$('#scenario-name').value=id==='bus'?'帰りの便を1便追加':strategies.find(s=>s[0]===id)[1];$('#progress').textContent='';if(id==='bus'&&baseline&&!trips.length)loadTrips();}
function fillTrips(){const q=$('#trip-filter').value.trim().toLowerCase(),shown=trips.filter(t=>[t.route,t.from,t.to,time(t.departure)].join(' ').toLowerCase().includes(q));$('#trip').innerHTML=shown.slice(0,2000).map(t=>`<option value="${esc(t.feed+'|'+t.id)}">${time(t.departure)} ${esc(t.route)}｜${esc(t.from)} → ${esc(t.to)}</option>`).join('')||'<option value="">該当する便がありません</option>';$('#trip-count').textContent=shown.length+'便'+(shown.length>2000?'（先頭2,000便。路線・停留所名で絞れます）':'');}
function loadTrips(){startWorker({mode:'trips',files:baseline.files,date:baseline.date},d=>{trips=d.trips.sort((a,b)=>a.route.localeCompare(b.route,'ja')||a.departure-b.departure);fillTrips();});}
function summaryHTML(){const s=populationSummary(baseline.cells,baseline.results);$('#baseline').innerHTML=`<span class="eyebrow">BASELINE / ${esc(baseline.cityName)}</span><h2>${esc(baseline.facility.name)}へ行って、帰れる？</h2><p>${esc(baseline.date)} ／ ${time(baseline.options.departure)}出発 → ${time(baseline.options.activityFrom)}から用事${baseline.options.dwell}分 → ${time(baseline.options.deadline)}までに帰宅</p><p><b>時刻表上の往復候補：${fmt(s.rate,1)}% ／ ${fmt(s.candidatePopulation)}人</b><br>対象の人口既知区域：${fmt(s.knownPopulation)}人（2020年基準・調整値）／ 判定保留：${fmt(s.unknownPopulation)}人</p><p class="note">同じ地域・目的地・日時・徒歩・乗換条件で比較します。実利用者・実際の移動成立を示すものではありません。</p><a href="atlas.html">比較の基準を変更する →</a>`;}
function showRows(){$('#comparison').innerHTML=rows.map(r=>`<article class="result-card"><span class="eyebrow">${r.method==='timetable'?'時刻表による再計算':'利用者が入力した仮定'}</span><h3>${esc(r.name)}</h3><p>${esc(r.detail)}</p><div class="compare-numbers">${fmt(r.beforeRate,1)}% → ${fmt(r.afterRate,1)}%<br><small>時刻表上の往復候補がある区域の人口割合${r.method==='assumption'?'（変更後は入力値）':''}</small></div><p>改善候補人口：<b>${fmt(r.net)}人</b> ${r.method==='timetable'?`（新たに候補あり ${fmt(r.gained)}人 − 候補がなくなる ${fmt(r.lost)}人）`:'（入力した人口と基準値の差）'}</p><p>${r.costBasis==='public'?'年間公的負担の追加額':'年間総追加費用'}：<b>${r.cost===null?'未入力':fmt(r.cost)+'円'}</b><br>改善候補人口1人あたり：<b>${r.unitCost===null?'算定できません':fmt(r.unitCost)+'円／人・年'}</b></p><p class="note">${r.cost===null?'費用が未入力のため費用対効果は算定していません。':r.net<=0?'改善人口の純増がないため、1人あたり費用は算定していません。':''} ${r.method==='timetable'?`判定保留を含む${fmt(r.uncertain)}人は改善人数の比較から除外。`:'配車・道路・容量・利用資格による到達可能性は自動計算していません。'} 実際の需要・車両・運転者・定員・予約運用の成立は要確認。</p><details><summary>根拠・条件</summary><p>費用：${esc(r.costSource||'未確認')}</p><p>${esc(r.assumptionSource||'収録GTFSの指定便を変更し、全対象区域の往復を再計算。施設の受付等は未確認。')}</p><p>${esc(baseline.cityName)}・${esc(baseline.date)}・${esc(baseline.facility.name)}。人口と日時・徒歩条件は基準と同じです。</p></details></article>`).join('');$('#export').disabled=!rows.length;}
function simulate(e){e.preventDefault();if(!baseline)throw Error('ATLASで基準の計算を行ってください');const raw=$('#annual-cost').value,cost=raw===''?null:Number(raw);if(cost!==null&&(!Number.isFinite(cost)||cost<0))throw Error('追加費用を0以上で入力してください');const base=populationSummary(baseline.cells,baseline.results),common={name:$('#scenario-name').value.trim().slice(0,100),strategy,cost,costBasis:$('#cost-basis').value,costSource:$('#cost-source').value.trim().slice(0,300),beforeRate:base.rate};
 if(strategy!=='bus'){stop();const after=Number($('#after-population').value),source=$('#assumption-source').value.trim();if(!source)throw Error('改善人口の仮定・別計算の根拠を記入してください');if(!Number.isFinite(after)||after<0||after>base.knownPopulation)throw Error('改善後の人口は0〜対象区域の人口の範囲で入力してください');const net=after-base.candidatePopulation;rows.push({...common,method:'assumption',detail:'変更後の到達人口を仮定した費用比較',afterRate:base.knownPopulation?after/base.knownPopulation*100:null,afterPopulation:after,net,gained:null,lost:null,uncertain:null,unitCost:policyCost({cost,gained:net}),assumptionSource:source.slice(0,1000)});showRows();return;}
 const trip=trips.find(t=>t.feed+'|'+t.id===$('#trip').value);if(!trip)throw Error('複製・変更する便を選んでください');const at=seconds($('#new-time').value+':00');if(at===null)throw Error('始発の新しい時刻を入力してください');const type=$('#edit-type').value;const edit={type,feed:trip.feed,trip:trip.id,minutes:(at-trip.departure)/60,newId:'mdl-v2-'+Date.now()};const detail=`${trip.route}：始発 ${time(trip.departure)} → ${time(at)}（${type==='duplicate'?'1便追加':'時刻変更'}）`;
 startWorker({mode:'city',date:baseline.date,options:baseline.options,files:baseline.files,edits:[edit],cases:baseline.cells.map(p=>({id:p.id,home:{name:p.city+'の区域代表点',lat:p.lat,lon:p.lon},facility:baseline.facility}))},d=>{const after=Object.fromEntries(d.results.map(v=>[v.id,v.result]));const s=populationSummary(baseline.cells,after),change=comparePopulation(baseline.cells,baseline.results,after);rows.push({...common,method:'timetable',detail,afterRate:s.rate,afterPopulation:s.candidatePopulation,...change,unitCost:policyCost({cost,gained:change.net}),edits:[edit],assumptionSource:''});showRows();$('#comparison').scrollIntoView({block:'start',behavior:'smooth'});});
}
function fulfillment(){const n=$('#needed').value,f=$('#fulfilled').value;if(n===''||f===''){$('#fulfillment').textContent='未測定';return;}const a=Number(n),b=Number(f);$('#fulfillment').textContent=!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0||b>a?'件数を確認':a===0?'対象なし（0件）':fmt(b/a*100,1)+'%';}
function start(){$('#strategies').innerHTML=strategies.map(([id,name,sub])=>`<button class="strategy" type="button" data-strategy="${id}" aria-pressed="${id===strategy}"><strong>${esc(name)}</strong><span>${esc(sub)}</span></button>`).join('');$('#strategies').onclick=guard(e=>{const b=e.target.closest('[data-strategy]');if(b)selectStrategy(b.dataset.strategy);});$('#trip').closest('label').insertAdjacentHTML('beforebegin','<label>路線・停留所名で絞る<input type="search" id="trip-filter" placeholder="例：病院、三重町、玖珠"></label>');$('#trip').insertAdjacentHTML('afterend','<small id="trip-count" class="note"></small>');$('#trip-filter').oninput=fillTrips;$('#policy-form').onsubmit=guard(simulate);$('#cancel').onclick=()=>{stop();$('#progress').textContent='計算を中止しました。';};
 $('#export').onclick=guard(()=>download('oita-policy-comparison.csv','\ufeff'+csvText(rows.map(r=>({scenario:r.name,method:r.method,strategy:r.strategy,municipality:baseline.cityName,facility:baseline.facility.name,date:baseline.date,before_rate:r.beforeRate,after_rate:r.afterRate,net_population_gain:r.net,new_candidate_population:r.gained??'',lost_candidate_population:r.lost??'',unknown_excluded_population:r.uncertain??'',annual_additional_cost:r.cost??'',cost_basis:r.costBasis,cost_per_net_candidate_person_year:r.unitCost??'',cost_source:r.costSource,assumption_source:r.assumptionSource,change:r.detail,conditions:JSON.stringify(baseline.options),gtfs_hashes:baseline.files.map(f=>f.sha256).join(' | '),population_basis:'2020年基準人口・代表点。実利用者ではない',engine:VERSION})),{safe:true}),'text/csv;charset=utf-8'));$('#needed').oninput=fulfillment;$('#fulfilled').oninput=fulfillment;if(baseline){summaryHTML();$('#simulate').disabled=false;loadTrips();}document.documentElement.dataset.atlasReady='true';}
guard(start)();
