"""Build the public concept site from the agreed Ver.0.3 proposal.

All organizational roles are proposals, not announcements of participation.
"""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'oita-consortium'
OUT.mkdir(exist_ok=True)
(OUT / 'guide').mkdir(exist_ok=True)
BASE = 'https://mobilitydlab.com/oita-consortium/'
PDF = 'oita-consortium-concept-v03.pdf'

def header(guide=False):
    pre = '../' if guide else './'
    menu = [('私たちが目指すもの', pre+'#vision'), ('共創のかたち', pre+'#co-create'), ('参加するには', pre+'#join'), ('構想説明書', pre+'guide/')]
    nav = ''.join(f'<a href="{url}"'+(' aria-current="page"' if guide and title=='構想説明書' else '')+f'>{title}</a>' for title,url in menu)
    return f'''<a class="skip" href="#main">本文へ移動</a><header class="site-head"><a class="brand" href="{pre}"><span class="brand-mark" aria-hidden="true">O.</span><span>大分未来モビリティ・<br>コンソーシアム<small>OITA MIRAI MOBILITY CONSORTIUM</small></span></a><nav class="desktop-nav" aria-label="メインメニュー">{nav}</nav><details class="mobile-menu"><summary>MENU</summary><nav aria-label="モバイルメニュー">{nav}</nav></details></header>'''

def head(title, guide=False):
    pre = '../' if guide else './'
    return f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fff0e2"><title>{title}｜大分未来モビリティ・コンソーシアム</title><meta name="description" content="大分の未来に、成長投資を。人・企業・大学・地域をつなぎ、新しい仕事と産業を生み出す大分未来モビリティ・コンソーシアムの構想。設立に向けた協議案 Ver.0.3。"><link rel="canonical" href="{BASE+('guide/' if guide else '')}"><link rel="stylesheet" href="{pre}site.css?v=20260926.1"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='20' fill='%23ef761e'/%3E%3Ccircle cx='18' cy='20' r='9' fill='none' stroke='%2329241f' stroke-width='4'/%3E%3Ccircle cx='31' cy='28' r='3' fill='%2329241f'/%3E%3C/svg%3E"><meta property="og:title" content="{title}｜大分未来モビリティ・コンソーシアム"><meta property="og:description" content="人と課題をつなぎ、事業を生み、大分に所得・雇用・地域資産を残す。設立に向けた協議案。"><meta property="og:type" content="website"><script src="{pre}site.js?v=20260926.1" defer></script></head><body{' class="home-page"' if not guide else ''}>'''

def footer(guide=False):
    pre = '../' if guide else './'
    return f'''<footer class="site-foot"><strong>大分未来モビリティ・コンソーシアム</strong><p>設立に向けた構想・協議案 Ver.0.3 ／ 2026年9月26日<br>本サイトは構想を説明するものです。記載する組織の参画・役割は協議案であり、合意・確定を示しません。</p><nav><a href="{pre}guide/">構想説明書</a><a href="{pre}guide/{PDF}">PDFを読む</a><a href="https://mobilitydlab.com/">制作：モビリティデザインラボ ↗</a></nav></footer></body></html>'''

def architecture():
    return '''<div class="architecture" role="group" aria-label="課題から継続事業までの全体構造"><p>大分県・発起人・参加メンバー<br>課題・政策・人材・技術・アイデアを持ち寄る</p><div class="arch-node featured"><span class="micro">CONNECT / 任意団体</span><b>大分未来モビリティ・<br>コンソーシアム</b><small>共同事務局｜<strong>トヨタカローラ大分 × MDL</strong><br>運営分の契約・口座・会計｜<strong>MDL</strong></small></div><div class="arch-arrow">↓ 仲間をつなぎ、企画を具体化</div><div class="arch-node"><span class="micro">PROJECT / 案件ごと</span><b>個別プロジェクト</b><small>実施・契約・会計｜<strong>各実施主体</strong><br>最も適した企業・団体が、責任と役割を決めて実行。</small></div><div class="arch-arrow">↓ 成果を確認して、事業として育てる</div><div class="arch-node"><span class="micro">CONTINUE / 既存企業・団体等</span><b>継続事業へ</b><small>続ける・広げる。必要になった時点で新法人・SPC等を検討。</small></div></div>'''

PAGES = [
('structure','OVERVIEW','全体像は、<br>この3層。','コンソーシアムが人と課題をつなぎ、各実施主体が事業を動かし、既存企業・団体等が継続事業として育てます。','1・8・14',
 architecture()+'''<p class="note">当面は法人格を持たない任意団体として始めます。新しい事業会社をつくること自体は目的にしません。</p>'''),
('participation','PARTICIPATION','参加の入口は、<br>3つ。','関わり方は一つではありません。最初の形をつくる、継続して参加する、案件ごとに取り組む。力を生かせる形でつながります。','2',
'''<div class="stack"><article class="role-card"><span class="role-no">01</span><div><h3>発起人</h3><p class="promise">最初の形を、一緒につくる。</p><p>設立趣旨に賛同し、基本方針・年間活動・運営の重要事項などについて意見を出すメンバーです。</p><p class="examples">想定：おおいたプラット、トヨタカローラ大分、MDL、大分県の関係部署など。参画は協議・確認を経て決定します。</p></div></article><article class="role-card"><span class="role-no">02</span><div><h3>参加メンバー</h3><p class="promise">関心のあるテーマで、継続的に。</p><p>市町村・企業・大学・交通事業者・地域団体など。課題、人材、技術、場所、情報、ネットワークを持ち寄り、力を生かせる活動に参加します。</p></div></article><article class="role-card"><span class="role-no">03</span><div><h3>プロジェクトパートナー</h3><p class="promise">この案件なら、一緒にやりたい。</p><p>特定のプロジェクトに必要な企業・団体が、案件ごとに参加。県外企業、大企業、スタートアップなども参加しやすくします。</p></div></article></div>'''),
('entry','JOIN & SUPPORT','参加しやすく。<br>負担は、明確に。','原則として組織で参加し、担当者が異動しても引き継げる仕組みにします。会費は、必要な運営費を整理して決めます。','3・10',
'''<ol class="inline-flow" aria-label="参加手続き"><li><b>01</b>趣旨を確認</li><li><b>02</b>参加申込</li><li><b>03</b>事務局確認</li><li><b>04</b>参加</li></ol><div class="mini-grid"><article class="mini"><h3>組織として参加</h3><p>企業・行政・大学等は原則として個人ではなく組織で参加。担当者が異動した場合は、後任へ引き継げます。</p></article><article class="mini"><h3>退会は、申し出る</h3><p>退会を希望する場合は、事務局へ申し出ます。すべての活動への参加を一律に求めません。</p></article></div><div class="decision-box"><h3>会費だけに頼らない運営へ</h3><p>会費、企業協賛、行政等からの委託・補助、イベント・活動収入など、複数の財源を組み合わせることを検討します。</p><div class="chip-row"><span class="chip">会費</span><span class="chip">企業協賛</span><span class="chip">委託・補助</span><span class="chip">活動収入</span></div></div><p class="note"><strong>会費額は未決定です。</strong>年間運営費を整理したうえで、設立準備期間中に決定します。個別プロジェクトの費用は会費と分けます。申込方法・受付開始時期も準備期間中に整えます。</p>'''),
('operations','OPERATING TEAM','運営は、<br>4つの機能で。','共有する場、方向を決める場、日々の推進、契約とお金の管理。それぞれの役割を明確にします。','4',
'''<div class="operating-grid"><article class="operating-card"><span class="big-num">01</span><h3>全体会</h3><div class="owner">みんなで共有する</div><p>参加メンバーが活動状況、地域の課題、アイデア、プロジェクト、成果を共有します。</p><span class="emphasis">年 <strong>2〜4</strong> 回程度</span></article><article class="operating-card"><span class="big-num">02</span><h3>運営会</h3><div class="owner">基本的な方向を決める</div><p>発起人を中心に構成。年間活動計画、参加方法、基本ルール、全体予算、重要な外部連携等を話し合います。</p></article><article class="operating-card office"><span class="big-num">03</span><h3>共同事務局</h3><div class="owner">トヨタカローラ大分<br>× MDL</div><p>連絡・調整、会議・活動の企画運営、課題整理、仲間の接続、プロジェクトづくり、人材育成、情報発信、成果整理を担います。</p></article><article class="operating-card office"><span class="big-num">04</span><h3>会計事務局</h3><div class="owner">MDL</div><p>運営に必要な契約、請求、入金、支払い、口座管理、収支管理、会計記録を担当。通常事業と分けて管理し、運営会へ定期報告します。</p></article></div><p class="note">共同事務局はトヨタカローラ大分＋MDL。会計事務局は、そのうちMDLが担う管理機能です。</p>'''),
('roles','ROLES & DECISIONS','強みを持ち寄り、<br>決める場をそろえる。','大分県・おおいたプラット・トヨタカローラ大分・MDLが、それぞれの強みを生かす役割分担を想定します。','5・6',
'''<div class="split-row"><h3>大分県</h3><div><strong>政策と地域課題をつなぐ</strong><p>重点政策、県庁内の関係部署、市町村、地域課題との接続への協力を想定。</p></div></div><div class="split-row"><h3>おおいたプラット</h3><div><strong>地域企業と地域実装をつなぐ</strong><p>地域経済・デジタル等の強みを生かす。発起人としての参加に加え、テーマに応じた案件参加を想定。</p></div></div><div class="split-row"><h3>トヨタカローラ大分<br>（TCO）</h3><div><strong>モビリティを社会実装へ</strong><p>地域・企業・トヨタグループをつなぎ、社会実装を進める。MDLと共同で事務局を運営。</p></div></div><div class="split-row"><h3>MDL</h3><div><strong>設計し、動かす</strong><p>組織とプロジェクトを設計・推進。共同事務局に加え、運営分の契約・口座・会計を担当。</p></div></div><div class="decision-box"><h3>日常と重要事項を分けて判断</h3><div class="decision-row"><b>日常の運営</b><span>TCO＋MDLが相談して進める。</span></div><div class="decision-row"><b>重要な事項</b><span>規約変更、年間計画、全体予算、参加制度の大きな変更、事務局変更、全体として行う重要事業は運営会で確認。</span></div></div><p class="note">基本は話し合いによる合意。合意が難しい場合の決め方は正式規約で定めます。記載する各組織の役割は協議案です。</p>'''),
('projects','PROJECT DESIGN','アイデアを、<br>動くプロジェクトへ。','地域・企業の課題、実現したいこと、新しいアイデア、技術・サービスを持ち寄り、実行できる形にします。','7・8',
'''<ol class="journey"><li><b>01</b><div><h3>課題・アイデアを持ち寄る</h3><p>誰が何に困っているか。何を実現したいかを共有。</p></div></li><li><b>02</b><div><h3>必要な仲間をつなぐ</h3><p>企業・大学・行政・地域などの力を組み合わせる。</p></div></li><li><b>03</b><div><h3>具体的な取組みにする</h3><p>目的、対象、方法を整理して、企画にする。</p></div></li><li><b>04</b><div><h3>実施主体を決める</h3><p>最も適した企業・団体を選び、役割と負担を定める。</p></div></li><li><b>05</b><div><h3>プロジェクトとして試す</h3><p>各実施主体が、合意した条件で実行。</p></div></li><li><b>06</b><div><h3>成果を確認する</h3><p>何が変わったか、継続できるかを確かめる。</p></div></li><li><b>07</b><div><h3>継続事業へ育てる</h3><p>既存企業・団体等が、事業として続け、広げる。</p></div></li></ol><div class="checklist"><h3>案件ごとに、最初に決めること</h3><ul><li>実施主体・責任者</li><li>役割分担</li><li>契約主体</li><li>費用負担</li><li>収入の受け取り先</li><li>成果の確認方法</li></ul></div>'''),
('money','TWO ACCOUNTS','お金の流れは、<br>2つに分ける。','コンソーシアム運営のお金と、個別事業のお金。それぞれの契約・管理主体を明確にします。','9',
'''<article class="fund-card"><div class="fund-head"><span class="fund-letter">A</span><h3>コンソーシアム運営<br>のお金</h3></div><div class="manager"><span>契約・口座・会計</span>MDL</div><p>会費、協賛金、全体活動費、事務局費、広報費、人材育成費など。</p><p>専用の管理区分を設け、MDLの通常事業と分けて収支を管理。運営会へ定期的に報告します。</p><div class="fund-route">運営資金 → MDLが管理 → 全体の活動へ</div></article><article class="fund-card"><div class="fund-head"><span class="fund-letter">B</span><h3>個別プロジェクト<br>のお金</h3></div><div class="manager"><span>実施・契約・会計</span>各実施主体</div><p>車両・運行、デジタルサービス、観光商品、イベント、実証事業など。</p><p>事業を実施する企業・団体が、原則として直接契約し、費用と収入を管理します。</p><div class="fund-route">案件の資金 → 各実施主体が管理 → 事業へ</div></article><p class="note"><strong>すべてのお金をMDL経由にはしません。</strong>共通の活動と各事業の収支を区別し、費用負担を案件ごとに決めます。</p>'''),
('rules','TRUST & COMMUNICATION','安心して話し、<br>成果を伝える。','情報の共有範囲と名称の使い方を整理し、協力しやすい場をつくります。','11・12',
'''<article class="rules-card"><h3>名称・ロゴは、事務局で確認</h3><p>コンソーシアムから生まれた取組みを、共通の名前で発信できるようにします。</p><div class="brand-example">大分未来モビリティ・コンソーシアム<br><strong>PROJECT</strong></div><p>対外的に名称やロゴを使用する場合は、事務局で確認。どのような取組みが生まれたかを蓄積していきます。</p></article><article class="rules-card"><h3>情報は、共有できる範囲で</h3><div class="mini-grid"><div><p><strong>全体会で共有</strong><br>基本的に、参加者に共有可能な情報を扱います。</p></div><div><p><strong>必要な人だけに共有</strong><br>企業秘密、個人情報、未発表技術等は、必要なメンバーに限定します。</p></div></div></article><p class="keyline">必要に応じて、案件単位で秘密保持契約等を結ぶ。</p><p class="note">名称・ロゴの使用と情報共有の確認方法は、設立準備の中で具体化します。</p>'''),
('outcomes','LOCAL VALUE','成果は、<br>大分に残す。','新しい事業や取引を生み、地域の暮らしを支え、所得・雇用・地域資産を増やすことを目指します。','13 / LVOS',
'''<div class="value-cards"><article class="value-card"><span>INCOME</span><b>所得</b><p>地域企業の売上・利益、働く人の所得につながったか。</p></article><article class="value-card"><span>JOBS</span><b>雇用</b><p>新しい仕事、若者が挑戦できる機会が生まれたか。</p></article><article class="value-card"><span>ASSETS</span><b>地域資産</b><p>人材、データ、知識、顧客、事業、ネットワークが残ったか。</p></article></div><div class="value-flow" aria-label="LVOSの価値循環"><div>移動・接続<small>機会をつくる</small></div><div>行動・事業<small>参加・消費・就労</small></div><div>地域に残す<small>所得・雇用・資産</small></div><div>次へつなぐ<small>学習・再投資</small></div></div><table class="measurement"><caption class="guide-section-title">成果を確かめる視点</caption><thead><tr><th scope="col">見るもの</th><th scope="col">確認すること</th></tr></thead><tbody><tr><th scope="row">暮らし</th><td>必要な移動や、学び・仕事・社会参加の機会につながったか。</td></tr><tr><th scope="row">地域経済</th><td>新しい取引・事業が生まれ、売上や所得に結びついたか。</td></tr><tr><th scope="row">継続性</th><td>次の事業に使える人材・データ・知識・関係が残ったか。</td></tr></tbody></table><p class="note">LVOS（地域に価値を残す考え方）を参照。売上と県内に残る付加価値は区別し、事業の寄与を確認します。会員数・会議回数だけで測らず、案件ごとに成果の測り方を決めます。上記は目標・評価の視点であり、達成実績ではありません。</p>'''),
('future','FUTURE ORGANIZATION','法人化は、<br>必要になったときに。','まずは任意団体として始め、既存の企業・団体の力を生かします。活動に応じて、最も適した組織の形を選びます。','14',
'''<h3 class="guide-section-title">組織の形を見直すきっかけ</h3><ol class="triggers"><li><b>01</b><span>常勤職員が必要になる</span></li><li><b>02</b><span>コンソーシアム自身が継続事業を持つ</span></li><li><b>03</b><span>大きな資産を保有する</span></li><li><b>04</b><span>コンソーシアム名義での契約が増える</span></li><li><b>05</b><span>会計をMDLから独立させる必要が高まる</span></li></ol><div class="future-options"><div><b>任意団体を継続</b><p>現在の形が適していれば、継続する。</p></div><div><b>一般社団法人等へ</b><p>団体自身に必要な機能を持たせる。</p></div><div><b>既存法人と役割を統合</b><p>既にある企業・団体と役割を統合する。</p></div><div><b>個別事業のみ法人化</b><p>必要な事業だけ別会社・SPC等にする。</p></div></div><p class="note">SPCは、特定の事業を行うための会社等を指します。新法人を増やすことを目標にせず、その時点の必要性から判断します。</p>'''),
('next','NEXT STEP','最初の形を、<br>一緒につくる。','この説明書は設立のための協議資料です。関係者と役割・費用・基本ルールを確認し、具体的な活動につなげます。','設立準備 / 全項目の確認',
'''<ol class="next-list"><li><b>01</b><div><h3>趣旨と関わり方を確認</h3><p>発起人・参加メンバー・案件ごとのパートナー。それぞれに合う参加方法と、想定する役割を確認します。</p></div></li><li><b>02</b><div><h3>運営費と財源を整理</h3><p>年間の活動内容と必要経費を整理し、会費・協賛等の組合せと具体的な金額を決めます。</p></div></li><li><b>03</b><div><h3>正式規約と実務を整える</h3><p>合意が難しい場合の決め方、参加の受付方法、運営分の契約・会計の手順を具体化します。</p></div></li><li><b>04</b><div><h3>最初のプロジェクトへ</h3><p>課題・アイデアを集め、実施主体・役割・費用負担・成果の確認方法を定めて取り組みます。</p></div></li></ol><p class="closing-line">参加しやすく。運営は明確に。<br>プロジェクトは動きやすく。<br>成果は大分に残す。</p><p class="subnote">主資料：規約・参加方法・運営方法 基本案 Ver.0.3（2026年9月26日提示）。成果の考え方は添付「LVOS大分.txt」を参照。<br>この説明書は正式規約・参加合意・個別事業の契約書ではありません。参加団体、会費、年間予算、正式な議決方法は設立準備中に協議します。</p><div class="actions"><a class="button" href="https://mobilitydlab.com/oita-consortium/">構想のホームページへ <span>↗</span></a></div>''')
]

guide = head('構想説明書｜基本案 Ver.0.3',True)+header(True)+'<main id="main" class="wrap">'
guide += f'''<section class="guide-cover sheet" id="cover"><div><p class="kicker">CONCEPT & OPERATING GUIDE</p><span class="status">基本案 Ver.0.3｜協議用</span><h1><small>大分未来モビリティ・<br>コンソーシアム</small>構想説明書</h1><p class="statement">参加しやすく。運営は明確に。<br>プロジェクトは動きやすく。<br>成果は大分に残す。</p><p class="hero-summary">行政・企業・大学・地域などをつなぎ、新しい取組みを生み出す共通の場へ。規約・参加方法・運営方法の基本的な考え方をまとめました。</p><div class="actions web-only"><a class="button" href="{PDF}">PDF・12ページを読む <span>↓</span></a><a class="text-link" href="#structure">まずは全体像を見る →</a></div></div><div class="cover-card"><div class="cover-number">4</div><h2>この構想の、基本前提。</h2><ul><li><span>1</span><span>法人を新設せず、任意団体で始める</span></li><li><span>2</span><span>TCO＋MDLが、共同で事務局を運営</span></li><li><span>3</span><span>運営分の契約・口座・会計はMDL</span></li><li><span>4</span><span>個別事業は、各実施主体が担う</span></li></ul></div><div class="page-foot"><span>OITA MIRAI MOBILITY CONSORTIUM / Ver.0.3 / 2026.09.26</span><b>01 / 12</b></div></section><p class="reader-intro">知りたいことから、読むページを選べます。</p><nav class="reader-nav" aria-label="説明書の読む順番"><a href="#structure">全体像を知る<b>P02</b></a><a href="#participation">参加方法を知る<b>P03–04</b></a><a href="#operations">運営・お金を知る<b>P05–09</b></a><a href="#outcomes">成果・将来を知る<b>P10–12</b></a></nav>'''
for i,(id_,en,title,lead,sec,body) in enumerate(PAGES,2):
    next_id,next_title = (PAGES[i-1][0],PAGES[i-1][2].replace('<br>','')) if i<12 else ('cover','説明書の先頭')
    guide += f'''<section class="chapter sheet" id="{id_}"><header class="chapter-head"><div class="chapter-kicker"><span class="page-no"><small>P</small>{i:02}</span><span class="kicker">{en}</span></div><h2>{title}</h2><p class="lead">{lead}</p><span class="source-sections">基本案の対応項目：{sec}</span></header><div class="chapter-body">{body}</div><nav class="chapter-nav" aria-label="P{i:02}のページ案内"><a href="#cover">↑ 読むページを選ぶ</a><a href="#{next_id}">次へ：{next_title} →</a></nav><div class="page-foot"><span>大分未来モビリティ・コンソーシアム / 基本案 Ver.0.3｜協議用</span><b>{i:02} / 12</b></div></section>'''
guide += '</main>'+footer(True)
(OUT/'guide/index.html').write_text(guide)

home = head('大分の未来に、成長投資を。')+header()+'''<main id="main">
<section class="photo-hero wrap" aria-labelledby="hero-title"><div class="hero-topline"><span class="kicker">OITA MIRAI MOBILITY CONSORTIUM</span><span class="status">設立に向けた構想・協議中</span></div><div class="hero-display"><h1 id="hero-title">大分の未来に、<br><span>成長投資を。</span></h1><div class="hero-side"><p>このまちで、<br>挑戦したくなる未来へ。</p><a class="round-link" href="#vision" aria-label="私たちが目指すものへ">↓</a></div></div><div class="photo-mosaic"><figure class="photo-main"><img src="assets/beppu.webp" width="1600" height="900" alt="田ノ浦ビーチから望む別府湾と別府市。2021年の風景" fetchpriority="high"><figcaption>このまちの可能性を、ひらく。<small>田ノ浦ビーチから望む別府湾</small></figcaption></figure><figure class="photo-sub"><img src="../assets/home-evidence/fujimigaoka-boarding.jpg" width="1108" height="1477" alt="富士見が丘で実証車両に乗り込む住民をスタッフが見守る" loading="eager"><figcaption>「行ける」が、可能性を広げる。</figcaption></figure><div class="orange-tile"><span>PEOPLE. IDEAS. MOBILITY.</span><p>つながる。<br>動きだす。<br>大分に残る。</p><a href="guide/">構想を読む <b>↗</b></a></div></div><p class="photo-context">写真：大分の風景と、富士見が丘での既存実証。コンソーシアム設立後の実績を示すものではありません。</p></section>
<section class="manifesto wrap" id="vision"><div><p class="kicker">01 / OUR VISION</p><h2>人が動く。<br>可能性が、<br><span>動きだす。</span></h2></div><div class="manifesto-copy"><p class="large-copy">若者が大分で挑戦したくなる<br>仕事と産業をつくりたい。</p><p>人口減少に向き合い、地域の課題と、企業・大学・地域が持つ人材・技術・アイデアをつなぐ。その接点から、具体的な取組みを生み出していきます。</p><p>モビリティを、車や交通の枠を越えて、人と場所、仕事、学び、観光、商いをつなぐ力へ。大分の成長を支えるインフラとして考えます。</p><div class="vision-words"><span>所得</span><span>雇用</span><span>地域資産</span></div><p class="subnote">この3つを、大分に残すことを目指します。</p></div></section>
<section class="field-section" id="co-create"><div class="wrap"><header class="section-head"><div><p class="kicker">02 / CO-CREATE</p><h2>一つの課題から、<br>一緒につくる。</h2></div><p>暮らし、観光、学び、産業。<br>それぞれの現場から、できることを持ち寄る。</p></header><div class="field-grid"><figure class="field-large"><img src="../assets/home-evidence/fujimigaoka-resident-briefing.jpg" width="1108" height="1477" loading="lazy" alt="住民説明会でタブレットと資料を使って地域の人に説明する様子"><figcaption><span>LISTEN / 地域の声</span><h3>まずは、<br>話を聞くことから。</h3><p>日々の困りごとと、実現したいこと。<br>現場から、課題を見つける。</p></figcaption></figure><div class="field-stack"><figure><img src="../assets/home-evidence/fujimigaoka-dialogue.jpg" width="1477" height="1108" loading="lazy" alt="地域の店舗前で住民とスタッフが話し合う"><figcaption><span>CONNECT / 仲間をつなぐ</span><h3>違う強みが、出会う。</h3><p>企業・行政・大学・地域の知恵をつなぐ。</p></figcaption></figure><figure><img src="assets/park.webp" width="1000" height="666" loading="lazy" alt="くじゅう周辺に広がる緑の風景。2023年撮影"><figcaption><span>GROW / 地域に残す</span><h3>このまちの価値を、次へ。</h3><p>人材も、事業も、地域の資産として育てる。</p></figcaption></figure></div></div><div class="co-create-bar"><span>課題を持ち寄る</span><b>→</b><span>仲間をつなぐ</span><b>→</b><span>事業を生み出す</span></div><div class="landscape-strip"><figure><img src="assets/opam.webp" width="1000" height="750" loading="lazy" alt="大分県立美術館OPAMの外観。2015年撮影"><figcaption>大分県立美術館 OPAM｜文化と出会う場所。</figcaption></figure><figure><img src="assets/airport.webp" width="1000" height="360" loading="lazy" alt="大分空港の旅客ターミナルとエプロン。2018年撮影"><figcaption>大分空港｜地域と、その先をつなぐ。</figcaption></figure></div><p class="photo-context">風景・施設の写真は大分の地域資源の紹介です。施設の参画や共同事業の決定を示すものではありません。</p></div></section>
<section class="join-section wrap" id="join"><header class="section-head"><div><p class="kicker">03 / JOIN THE POSSIBILITY</p><h2>あなたの「やりたい」を、<br>大分の次の一歩に。</h2></div><p>関わり方は、3つ。<br>すべての活動に参加する必要はありません。</p></header><div class="join-rows"><a href="guide/#participation"><span class="join-number">01</span><div><span class="join-en">FOUNDING PARTNER</span><h3>発起人として</h3><p>最初の形を、一緒につくる。</p></div><span class="join-arrow">↗</span></a><a href="guide/#participation"><span class="join-number">02</span><div><span class="join-en">MEMBER</span><h3>参加メンバーとして</h3><p>関心のあるテーマに、力を持ち寄る。</p></div><span class="join-arrow">↗</span></a><a href="guide/#participation"><span class="join-number">03</span><div><span class="join-en">PROJECT PARTNER</span><h3>プロジェクトで</h3><p>この案件なら。一緒に試すところから。</p></div><span class="join-arrow">↗</span></a></div><p class="subnote">参加方法・受付開始時期・会費は設立準備期間中に協議します。</p></section>
<section class="guide-home wrap" id="guide"><div class="guide-promo"><div><p class="kicker">CONCEPT GUIDE / Ver.0.3</p><h2>仕組みを知る。<br>一緒に始める。</h2><p>全体像、参加方法、運営体制、お金の流れ、成果の考え方を、図解でまとめました。</p><div class="actions"><a class="button" href="guide/">構想説明書を読む <span>→</span></a><a class="button secondary" href="guide/'''+PDF+'''">PDFを読む <span>↓</span></a></div></div><div><div class="giant">12<small>PAGES</small></div><p class="route-labels">3つの参加方法<br>4つの運営機能<br>2つのお金の流れ</p><p class="subnote">規約・参加方法・運営方法 基本案 Ver.0.3</p></div></div></section><div class="ending wrap"><p>ここから、<br><span>大分の次を。</span></p><a href="#join" class="round-link" aria-label="参加方法を見る">↑</a></div></main>'''+footer()
home=home.replace('</footer>','<details class="photo-credits"><summary>写真について・クレジット</summary><p>地域での対話・住民説明・乗車の写真：MDLの既存公開サイト掲載資料（富士見が丘）。設立後のコンソーシアムの実績ではありません。</p><p>田ノ浦ビーチから望む別府湾・別府市（2021年）｜Project Kei / <a href="https://commons.wikimedia.org/wiki/File:Beppu_City_and_Beppu_Bay.jpg">原典</a> / <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。縮小・WebP変換、表示枠に応じてトリミング。写真の加工版には各記載のライセンスを適用。</p><p>大分県立美術館 OPAM（2015年）｜大分帰省中 / <a href="https://commons.wikimedia.org/wiki/File:Oita_OPAM_1.jpg">原典</a> / <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。縮小・WebP変換、表示枠に応じてトリミング。写真の加工版には各記載のライセンスを適用。</p><p>大分空港 旅客ターミナルとエプロン（2018年）｜Project Kei / <a href="https://commons.wikimedia.org/wiki/File:Oita_Airport_Passenger_Terminal_and_Apron.jpg">原典</a> / <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>。縮小・WebP変換、表示枠に応じてトリミング。写真の加工版には各記載のライセンスを適用。</p><p>くじゅう周辺の緑の風景（2023年）｜Raita Futo / <a href="https://commons.wikimedia.org/wiki/File:Kuju_green_fields_(53032548236).jpg">原典</a> / <a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>。縮小・WebP変換、表示枠に応じてトリミング。写真の加工版には各記載のライセンスを適用。</p></details>'+'</footer>')
(OUT/'index.html').write_text(home)
(OUT/'content.json').write_text(json.dumps({'version':'0.3','date':'2026-09-26','pages':[dict(id=x[0],category=x[1],title=x[2].replace('<br>',''),lead=x[3],source_sections=x[4],html=x[5]) for x in PAGES]},ensure_ascii=False,indent=2))
print('Built home and guide: 12 pages; 14 original topics preserved.')
