"""Bauhaus Cartoon homepage with real photographs of Garraway0."""
from bs4 import BeautifulSoup

def build_visual_pages(out, head, header, footer, resources, photo_story):
    cards = ''
    short = ['イベントを、<br>探す。','行って、<br>帰れる？','交通を、<br>読み解く。','地域で動く<br>力をつける。']
    for i,r in enumerate(resources):
        cards += f'''<a class="bau-resource bau-resource-{i+1}" href="explore/?view={r['id']}"><div class="bau-card-top"><span>{r['label']}</span><b>{r['number']}</b></div><h3>{short[i]}</h3><p class="bau-resource-name">{r['name']}</p><p>{r['description']}</p><div class="bau-card-action"><span>{r['action']}</span><b aria-hidden="true">↗</b></div></a>'''
    top = head('大分の未来に、成長投資を。').replace('class="home-page"','class="home-page bauhaus-page"').replace('</head>','<link rel="stylesheet" href="bauhaus.css?v=20260926.3"></head>')
    top += header()
    top += f'''<main id="main"><section class="bau-hero wrap" aria-labelledby="hero-title"><div class="bau-hero-copy"><div class="bau-eyebrow"><span>OITA / MIRAI / MOBILITY</span><span>設立に向けた構想</span></div><h1 id="hero-title">大分の未来に、<br><strong>成長投資を。</strong></h1><p class="bau-hero-lead">若者が、大分で挑戦したくなる。<br>そんな仕事と産業を、一緒につくる。</p><div class="bau-values"><span>所得</span><span>雇用</span><span>地域資産</span></div><div class="bau-hero-actions"><a href="#explore">4つの入口へ <b aria-hidden="true">↓</b></a><a href="guide/">構想を読む <b aria-hidden="true">↗</b></a></div></div><div class="bau-hero-art"><span class="bau-art-label">PEOPLE MEET POSSIBILITY.</span><img src="assets/bauhaus-community.png" alt="目のついたモビリティと手、笑顔がつながる幾何学的なキャラクター" width="1536" height="1024" fetchpriority="high"><p>人がつながる。<br>まちが動きだす。</p></div></section>
<section class="bau-explore wrap" id="explore"><header class="bau-section-head"><div><span class="bau-overline">LET’S GET STARTED</span><h2>知る。試す。学ぶ。</h2></div><p>いま知りたいことから、<br>大分の次の一歩へ。</p></header><div class="bau-resource-grid">{cards}</div><p class="bau-credit">提供・更新：モビリティデザインラボ</p></section>
<section class="bau-vision wrap" id="vision"><div class="bau-vision-title"><span class="bau-overline">OUR IDEA</span><h2>ひとつの課題に、<br>いろんな得意を。</h2><p>企業・行政・大学・地域。<br>違う強みが出会うと、できることが増えていく。</p></div><div class="bau-steps"><div><b>1</b><p>課題を<br><strong>持ち寄る。</strong></p></div><div><b>2</b><p>必要な仲間を<br><strong>つなぐ。</strong></p></div><div><b>3</b><p>プロジェクトを<br><strong>動かす。</strong></p></div></div><p class="bau-vision-note">法人を新設せず、任意団体から。事業は、それぞれに適した企業・団体が担います。</p></section>
<section class="bau-place bau-photo-place wrap" id="place"><div class="bau-photo-copy"><span class="bau-overline">GARRAWAY0 & LOCAL PRACTICE</span><h2>会って、話して、<br>やってみる。</h2><p>Garraway0の学びと交流。地域の人とつくる実証。<br>写真で、その現場をのぞいてみよう。</p><a href="activity/"><span>活動・拠点を見る</span><b aria-hidden="true">↗</b></a></div><figure class="bau-place-main"><img src="assets/garraway0-learning.webp" alt="Garraway0で開催されたモビリティ人材育成公開イベントの様子" width="1200" height="798" loading="lazy"><figcaption>LEARN / 学びを、行動へ。</figcaption></figure><figure><img src="assets/garraway0-space.webp" alt="Garraway0のソファと大型モニターがある交流空間" width="1600" height="844" loading="lazy"><figcaption>PLACE / 人が集まる場所。</figcaption></figure><figure><img src="assets/garraway0-cocreation.webp" alt="Garraway0でテーブルを囲んで話す利用者" width="1600" height="844" loading="lazy"><figcaption>PEOPLE / 違う得意が、出会う。</figcaption></figure></section>
<section class="bau-join wrap" id="join"><header class="bau-section-head"><div><span class="bau-overline">JOIN THE POSSIBILITY</span><h2>関わり方は、3つ。</h2></div><p>全部に参加しなくていい。<br>あなたの「やりたい」から。</p></header><div class="bau-join-grid"><a href="guide/#participation"><b>01</b><h3>発起人</h3><p>最初の形を、一緒につくる。</p><span>参加方法を読む ↗</span></a><a href="guide/#participation"><b>02</b><h3>参加メンバー</h3><p>関心のあるテーマに、力を持ち寄る。</p><span>参加方法を読む ↗</span></a><a href="guide/#participation"><b>03</b><h3>プロジェクト<br>パートナー</h3><p>この案件なら。一緒に試す。</p><span>参加方法を読む ↗</span></a></div><p class="bau-credit">参加方法・受付開始時期・会費は、設立準備期間中に協議します。</p></section>
<section class="bau-guide wrap"><div class="bau-guide-number">12<span>PAGES</span></div><div><span class="bau-overline">CONCEPT GUIDE / Ver.0.3</span><h2>仕組みを知る。<br>一緒に始める。</h2><p>全体像・参加方法・運営・お金の流れを、図解で。</p><div class="bau-guide-links"><a href="guide/">構想説明書を読む ↗</a><a href="guide/oita-consortium-concept-v03.pdf">PDFを読む ↓</a></div></div></section></main>'''
    top += footer().replace('</footer>','<p class="bau-photo-source">写真：<a href="https://garraway0.com/">Garraway0公式サイト</a>・<a href="https://note.com/garraway0/n/nb6136a6b1a1c">公式note</a>。既存の拠点・公開イベントの様子です。</p></footer>')
    (out/'index.html').write_text(top)
    soup = BeautifulSoup(photo_story,'html.parser')
    sections = ''.join(str(soup.select_one(x)) for x in ['#garraway0','#co-create'])
    # Photo asset links are local to the consortium root, one level above this page.
    sections += '<section class="community-portrait wrap"><img src="assets/garraway0-cocreation.webp" alt="Garraway0でテーブルを囲んで話す利用者の様子" width="1600" height="844" loading="lazy"><p>Garraway0｜人とアイデアが出会う風景。</p></section>'
    sections = sections.replace('src="assets/','src="../assets/').replace('src="../assets/home-evidence/','src="/assets/home-evidence/').replace('href="explore/','href="../explore/')
    credits = str(soup.select_one('.photo-credits')).replace('</details>', '<p>Garraway0の施設・利用者写真：<a href="https://garraway0.com/">Garraway0公式サイト</a>。人材育成公開イベントの写真：<a href="https://note.com/garraway0/n/nb6136a6b1a1c">Garraway0公式note</a>。画像の権利は原権利者に帰属します。</p></details>')
    activity = head('活動・拠点',guide=True).replace('guide/"','activity/"') + header(guide=True).replace(' aria-current="page"','')
    activity += '''<main id="main"><section class="activity-intro wrap"><p class="kicker">MEET THE PLACE / MEET THE PEOPLE</p><h1>挑戦は、<br>人が会うところから。</h1><p>Garraway0と、大分の地域での活動をご紹介します。</p><a class="text-link" href="../#explore">調べる・学ぶ、4つの入口へ →</a></section>'''+sections+'''<div class="activity-return wrap"><p>掲載写真はGarraway0の紹介・公開イベント、および富士見が丘の既存実証の様子です。</p><a class="button" href="../">コンソーシアムのホームへ →</a></div></main>'''+footer(guide=True)
    activity = activity.replace('</footer>',credits+'</footer>')
    (out/'activity').mkdir(exist_ok=True)
    (out/'activity/index.html').write_text(activity)
