'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Plus,BusFront,CalendarDays,LayoutGrid,MoreHorizontal,Zap,Check,Clock3,MapPin,ChevronRight,ChevronLeft,ShieldCheck,Users,ShoppingBag,RefreshCw,TriangleAlert,Link2,HandHelping,Settings2,X,Activity,Type,Ticket,ClipboardCheck} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {AppState,Booking,Command,PURPOSES,clockText,dateText,inputDate,fromInput,shift,fresh,nextBooking,readiness} from '@/lib/model';
import {nextAction,durationRange} from '@/lib/presentation';
export const NAV=[{id:'today',label:'今日',icon:LayoutGrid},{id:'schedule',label:'予定',icon:CalendarDays},{id:'vehicles',label:'車両',icon:BusFront},{id:'more',label:'その他',icon:MoreHorizontal}];
const STATUS:Record<string,string>={confirmed:'予定',active:'利用中',return_requested:'返却の受領待ち',received:'次回準備待ち',completed:'完了',cancelled:'取消'};
const CHARGING:Record<string,string>={not_connected:'未接続',connected:'接続・充電待ち',charging:'充電中',interrupted:'充電中断',target_reached:'必要量に到達',finished:'終了・解除待ち'};
type Props={state:AppState;view:string;setView:(view:string)=>void;open:(type:string,id?:string)=>void;command:(c:Command,close?:boolean)=>Promise<boolean>;guest:boolean;busy:boolean;offline:boolean;notice:string;error:string;onDismiss:()=>void;onRefresh:()=>void;children:React.ReactNode};
function Status({type,label}:{type:string;label:string}){return <span className={'status-pill '+type}>{type==='ready'?<Check size={17}/>:type==='blocked'||type==='unknown'?<TriangleAlert size={17}/>:<Clock3 size={17}/>}<span>{label}</span></span>;}
export function Brand(){return <span className="one-brand"><span className="one-brand-symbol">e</span><span>e-Palette <b>ONE</b></span></span>;}
export default function Workspace({state:s,view,setView,open,command,guest,busy,offline,notice,error,onDismiss,onRefresh,children}:Props){
 const [day,setDay]=useState(inputDate(s.clock).slice(0,10)),[filter,setFilter]=useState('all'),[large,setLarge]=useState(false);
 useEffect(()=>{try{const on=sessionStorage.getItem('epalette-text-large')==='yes';setLarge(on);document.documentElement.dataset.textSize=on?'large':'normal';}catch{}const key=window.location.hash.slice(1);if(NAV.some(n=>n.id===key))setView(key);},[setView]);
 function textSize(){const on=!large;setLarge(on);document.documentElement.dataset.textSize=on?'large':'normal';try{sessionStorage.setItem('epalette-text-large',on?'yes':'no');}catch{}}
 function navigate(id:string){setView(id);window.history.replaceState(null,'','#'+id);window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>document.getElementById('page-title')?.focus({preventScroll:true}));}
 const action=nextAction(s),tasks=s.tasks.filter(t=>t.status!=='completed'),today=s.bookings.filter(b=>inputDate(b.start).slice(0,10)===inputDate(s.clock).slice(0,10)&&b.status!=='cancelled').sort((a,b)=>a.start.localeCompare(b.start));
 const upcoming=today.filter(b=>!['completed','cancelled'].includes(b.status));
 const unavailable=s.vehicles.filter(v=>['blocked','unknown'].includes(readiness(s,v,nextBooking(s,v.id)).type)).length;
 const connectionHref=guest?'/connections':'/workspace/connections';
 const disabled=busy||offline;
 function row(b:Booking){return <button className={'agenda-row '+(b.status==='completed'?'past':'')} key={b.id} onClick={()=>open('detail',b.id)}><span className="agenda-time"><b>{clockText(b.start)}</b><span>{clockText(b.end)}まで</span></span><span className={'agenda-line '+b.purpose}/><span className="agenda-copy"><span className="agenda-meta">{b.vehicleId}<span>{PURPOSES[b.purpose]}</span></span><strong>{b.title}</strong><span className="agenda-route">{b.route}</span></span><span className={'agenda-state '+b.status}>{STATUS[b.status]}</span><ChevronRight className="agenda-arrow" size={22}/></button>;}
 const shortcuts=[{label:'乗車・降車',detail:'乗客を確認',icon:Users,type:'tickets'},{label:'オンデマンド',detail:`未割当 ${s.rides.filter(r=>r.status==='waiting').length}件`,icon:BusFront,type:'ride'},{label:'物販・受取',detail:`未受取 ${s.orders.filter(o=>!['handed','cancelled'].includes(o.status)).length}件`,icon:ShoppingBag,type:'orders'},{label:'引継ぎ',detail:`未完了 ${tasks.length}件`,icon:HandHelping,type:'tasks'}];
 return <SidebarProvider className="one-shell" style={{'--sidebar-width':'14.5rem'} as React.CSSProperties}>
  <a className="skip-link" href="#main-work">操作画面へ移動</a>
  <Sidebar collapsible="none" className="one-rail">
   <SidebarHeader><a href={guest?'/':'/workspace'} aria-label="e-Palette ONE 今日の画面"><Brand/></a><span className="rail-caption">共同利用・運行管理</span></SidebarHeader>
   <SidebarContent><SidebarMenu aria-label="メインメニュー">{NAV.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="one-nav-link" isActive={view===n.id} aria-current={view===n.id?'page':undefined} onClick={()=>navigate(n.id)}><n.icon/><span>{n.label}</span>{n.id==='today'&&unavailable>0&&<span className="nav-count">{unavailable}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
    <div className="rail-secondary"><span>すぐに開く</span><a href={connectionHref}><Ticket size={20}/>乗車予約<ArrowUpRight size={17}/></a><button onClick={()=>open('history')}><Activity size={20}/>実績・履歴</button></div>
   </SidebarContent><SidebarFooter><div className="rail-mode"><ShieldCheck size={20}/><div><b>{guest?'ログイン不要の体験版':'保存された検証データ'}</b><span>{guest?'操作はこのタブ内だけに保存':'本人の管理データを表示'}</span></div></div><span className="one-credit">MOBILITY DESIGN LAB</span></SidebarFooter>
  </Sidebar>
  <div className="one-work">
   <header className="one-header"><div className="mobile-logo"><Brand/></div><div className="header-location"><MapPin size={19}/><span>大分・共同利用エリア</span></div><div className="header-tools"><button className={'type-button '+(large?'selected':'')} aria-pressed={large} onClick={textSize}><Type size={21}/><span>{large?'文字 標準に':'文字 大きく'}</span></button><button className="refresh-button" aria-label="表示を更新" onClick={onRefresh}><RefreshCw size={21}/></button></div></header>
   <main id="main-work" className="one-main">
    <div className="one-demo"><span className="demo-label">体験版</span><p>模擬データです。実際の運行・課金は行いません。</p></div>
    {offline&&<div className="error-strip" role="alert">通信が切れています。表示済みの情報を確認できます。新しい操作は接続後に行ってください。</div>}
    {error&&<div className="error-strip" role="alert">{error}</div>}
    {notice&&<div className="saved-notice" role="status"><Check size={23}/><span>{notice}</span><button aria-label="保存結果を閉じる" onClick={onDismiss}><X size={22}/></button></div>}
    <div className="one-page-heading"><div><p className="page-kicker">{dateText(s.clock)}<span>検証時刻 {clockText(s.clock)}</span></p><h1 id="page-title" tabIndex={-1}>{{today:'今日の準備',schedule:'利用の予定',vehicles:'車両の状態',more:'ほかの仕事'}[view]}</h1></div>{view!=='more'&&<button className="btn secondary new-booking" onClick={()=>open('booking')}><Plus size={21}/><span>予定を追加</span></button>}</div>
    {view==='today'&&<>
     <div className="home-top">
      <section className={'action-panel '+action.tone} aria-labelledby="next-action-title"><div className="action-eyebrow"><span><Zap size={19}/>{action.label}</span><span className="action-vehicle">{action.vehicleId||'FLEET'}</span></div>
       <div className="action-body"><div className="action-copy"><h2 id="next-action-title">{action.title}</h2><p>{action.description}</p>{action.estimate?.valid&&<p className="action-estimate">急速充電 <strong>{durationRange(action.estimate.min,action.estimate.max)}</strong> の見込み</p>}</div>
       {action.deadline&&<div className="action-deadline"><span>{action.kind==='charge'?'充電へ出発する期限':'対応する期限'}</span>{inputDate(action.deadline).slice(0,10)!==inputDate(s.clock).slice(0,10)&&<span>{dateText(action.deadline)}</span>}<strong>{clockText(action.deadline)}</strong><span>までに</span></div>}</div>
       <button className="btn action-primary" onClick={()=>action.modal==='schedule'?navigate('schedule'):open(action.modal,action.id)}>{action.button}<ArrowRight size={23}/></button><p className="action-footnote"><ShieldCheck size={16}/>実車の安全確認は、開始前に別途行います。</p>
      </section>
      <section className="fleet-overview" aria-labelledby="fleet-title"><div className="panel-heading"><h2 id="fleet-title">次の利用への準備</h2><span>{s.vehicles.length}台</span></div>{s.vehicles.map(v=>{const b=nextBooking(s,v.id),r=readiness(s,v,b);return <button key={v.id} className="fleet-row" onClick={()=>open('vehicle',v.id)}><div className="fleet-row-main"><b>{v.id}</b><Status type={r.type} label={r.type==='ready'?'準備できる見込み':r.type==='action'?'対応が必要':r.label}/><span className="fleet-next">{b?`${clockText(b.start)} ${PURPOSES[b.purpose]}`:s.bookings.some(b=>b.vehicleId===v.id&&b.status==='active')?'利用中・返却前':'次の予定なし'}</span></div><div className="fleet-charge"><b>{v.soc.value??'—'}<small>%</small></b><Progress value={v.soc.value??0} className={'battery '+(!fresh(v.soc,s.clock)?'stale':'')}/><span>{fresh(v.soc,s.clock)?clockText(v.soc.observedAt)+' 更新':'更新を確認'}</span></div><ChevronRight size={18}/></button>})}</section>
     </div>
     <section className="quick-work" aria-label="よく使う仕事">{shortcuts.map(q=><button key={q.type} onClick={()=>open(q.type)}><q.icon size={26}/><span><strong>{q.label}</strong><small>{q.detail}</small></span><ChevronRight size={20}/></button>)}</section>
     <div className="home-bottom"><section className="one-panel"><div className="panel-heading"><h2>このあとの予定 <span className="number-chip">{upcoming.length}</span></h2><button className="text-button" onClick={()=>navigate('schedule')}>すべて<ArrowRight size={18}/></button></div>{upcoming.length?upcoming.map(row):<div className="empty"><CheckCircle/><p>今日の未完了の予定はありません</p></div>}{today.some(b=>b.status==='completed')&&<Collapsible><CollapsibleTrigger className="history-trigger">完了した予定を表示<ChevronRight size={19}/></CollapsibleTrigger><CollapsibleContent>{today.filter(b=>b.status==='completed').map(row)}</CollapsibleContent></Collapsible>}</section>
      <section className="one-panel handover-panel"><div className="panel-heading"><h2>引継ぎ</h2><span className="number-chip">{tasks.length}</span></div>{tasks.length?tasks.slice(0,2).map(t=><button className="handover-tile" key={t.id} onClick={()=>open('tasks',t.id)}><div><span className="status-pill action"><Clock3 size={16}/>{t.status==='requested'?'受領待ち':'作業待ち'}</span><b>{clockText(t.deadline)}まで</b></div><h3>{t.title}</h3><p>{s.staff.find(x=>x.id===t.owner)?.name??'担当者が未定です'}</p><span className="handover-link">内容を確認<ArrowRight size={19}/></span></button>):<p className="calm-message"><Check size={21}/>未完了の引継ぎはありません</p>}</section>
     </div>
    </>}
    {view==='schedule'&&<>
     <div className="schedule-toolbar"><div className="date-picker"><button aria-label="前の日" onClick={()=>setDay(inputDate(shift(fromInput(day+'T12:00'),-1440)).slice(0,10))}><ChevronLeft/></button><input type="date" aria-label="予定の日付" value={day} onChange={e=>setDay(e.target.value)}/><button aria-label="次の日" onClick={()=>setDay(inputDate(shift(fromInput(day+'T12:00'),1440)).slice(0,10))}><ChevronRight/></button></div><div className="vehicle-filters" role="group" aria-label="車両の絞り込み">{['all',...s.vehicles.map(v=>v.id)].map(id=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{id==='all'?'すべて':id}</button>)}</div></div>
     <section className="one-panel agenda-panel"><div className="panel-heading"><h2>時間順の予定</h2><span>準備・返却まで確認</span></div>{s.bookings.filter(b=>inputDate(b.start).slice(0,10)===day&&(filter==='all'||b.vehicleId===filter)).sort((a,b)=>a.start.localeCompare(b.start)).map(row)}{!s.bookings.some(b=>inputDate(b.start).slice(0,10)===day&&(filter==='all'||b.vehicleId===filter))&&<div className="empty"><CalendarDays size={32}/><p>この日の予定はありません</p><button className="btn secondary" onClick={()=>open('booking')}>予定を追加<Plus size={20}/></button></div>}</section>
     <p className="section-note"><ShieldCheck size={20}/>予定を開くと、安全確認・利用開始・返却へ進めます。</p>
    </>}
    {view==='vehicles'&&<><div className="vehicle-board">{s.vehicles.map(v=>{const b=nextBooking(s,v.id),r=readiness(s,v,b),valid=fresh(v.soc,s.clock);return <section className={'vehicle-tile '+r.type} key={v.id}><div className="vehicle-tile-heading"><span className="vehicle-model">e-Palette</span><BusFront size={31}/></div><h2>{v.id}</h2><Status type={r.type} label={r.label}/><div className="soc-display"><div><span>電池残量</span><strong>{v.soc.value??'—'}<small>%</small></strong></div><span className={'soc-state '+(!valid?'uncertain':'')}>{valid?'模擬データ':'情報が古い'}<br/>{clockText(v.soc.observedAt)} 更新</span></div><Progress value={v.soc.value??0} className={'battery '+(!valid?'stale':'')}/><p className="vehicle-reason">{r.reason}</p><div className="vehicle-location"><MapPin size={19}/><span>{v.location.value??'場所を確認できません'}</span></div><p className="vehicle-charging"><Zap size={19}/>{CHARGING[v.charging.value??'']??'充電状態を確認できません'}</p><div className="next-slot"><span>次の利用</span><b>{b?clockText(b.start):'予定なし'}</b><p>{b?.title??'現在の利用・返却を確認してください'}</p></div><button className="btn secondary full" onClick={()=>open('vehicle',v.id)}>状態・必要な対応を見る<ArrowRight size={20}/></button><button className="report-link" onClick={()=>open('incident',v.id)}><TriangleAlert size={19}/>異常を報告</button></section>})}</div><p className="section-note"><ShieldCheck size={20}/>残量・場所・充電状態は模擬データです。実車には接続されていません。</p></>}
    {view==='more'&&<><section className="more-section"><h2>利用者・現場の仕事</h2><div className="work-grid"><a href={connectionHref} className="work-tile"><Ticket/><div><h3>乗車予約・取消</h3><p>便を探す、自分の予約を確認</p></div><ArrowUpRight/></a>{shortcuts.map(q=><button className="work-tile" key={q.type} onClick={()=>open(q.type)}><q.icon/><div><h3>{q.label}</h3><p>{q.detail}</p></div><ChevronRight/></button>)}<button className="work-tile" onClick={()=>open('history')}><Activity/><div><h3>実績・操作履歴</h3><p>これまでの記録とCSV</p></div><ChevronRight/></button></div></section><section className="more-section"><h2>体験・接続の設定</h2><div className="work-grid"><button className="work-tile" onClick={()=>open('simulate')}><Settings2/><div><h3>車両状態を変えて試す</h3><p>残量、充電中断、更新遅れ</p></div><ChevronRight/></button><button className="work-tile" onClick={()=>open('connection')}><Link2/><div><h3>実車・AIの接続状況</h3><p>接続済みと未接続を確認</p></div><ChevronRight/></button><button className="work-tile" disabled={disabled} onClick={()=>void command({type:'advance_clock',minutes:30})}><Clock3/><div><h3>検証時刻を30分進める</h3><p>現在 {clockText(s.clock)}・鮮度も再計算</p></div><ChevronRight/></button><button className="work-tile" onClick={()=>open('reset')}><RefreshCw/><div><h3>体験を最初から</h3><p>確認後に模擬データを初期化</p></div><ChevronRight/></button></div></section><div className="private-workspace"><ShieldCheck size={22}/><div><h3>{guest?'保存した管理データは別に保護されています':'保存された検証用管理データを表示しています'}</h3><p>{guest?'体験結果は、このタブだけに保存されます。実際の個人情報は入力しないでください。':'このアカウントのデータは匿名の体験版には表示されません。'}</p>{guest?<a href="/workspace">管理データを開く（本人確認）<ArrowUpRight size={17}/></a>:<a href="/">ログイン不要の体験版へ<ArrowRight size={17}/></a>}</div></div></>}
    <footer className="one-footer"><span>e-Palette <b>ONE</b></span><span>{guest?'このタブだけに保存 · 実車未接続':'本人の管理データ · 実車未接続'}</span></footer>
   </main>
   <nav className="one-bottom-nav" aria-label="メインメニュー">{NAV.map(n=><button key={n.id} aria-current={view===n.id?'page':undefined} className={view===n.id?'selected':''} onClick={()=>navigate(n.id)}><n.icon size={23}/><span>{n.label}</span></button>)}</nav>
  </div>{children}
 </SidebarProvider>;
}
function CheckCircle(){return <ClipboardCheck size={32}/>;}
