import { z } from 'zod';
import { State,Principal,AgentTask,canonical,data,fail,parseInput,permit,prepare,readAction,commitApproved,getProposal,publicProposal } from './core';
import { tools } from './catalog';
export const agentCard=(origin:string)=>({name:'e-Palette ONE',description:'合成データで乗車予約案・車両状況・充電計画を扱う検証用エージェント。変更には本人確認が必要。',version:'1.2.0',supportedInterfaces:[{url:origin+'/a2a',protocolBinding:'JSONRPC',protocolVersion:'1.0'}],documentationUrl:origin+'/connections',capabilities:{streaming:false,pushNotifications:false,extendedAgentCard:false},securitySchemes:{delegatedKey:{httpAuthSecurityScheme:{scheme:'bearer',bearerFormat:'epo delegated credential'}}},securityRequirements:[{schemes:{delegatedKey:{list:[]}}}],defaultInputModes:['application/json'],defaultOutputModes:['application/json'],skills:[{id:'epalette-business-actions',name:'検索・予約案・充電計画',description:'DataPart.data に name と args を指定します。確定済み状態は共通DBから取得します。',tags:['mobility','approval'],examples:['get_charge_plan','search_trips']} ]});
const taskId=z.string().min(1).max(100);
const message=z.object({messageId:taskId,role:z.literal('ROLE_USER'),contextId:taskId.optional(),taskId:taskId.optional(),parts:z.array(z.object({data:z.object({name:z.string(),args:z.record(z.unknown())}).strict(),mediaType:z.literal('application/json').optional()}).strict()).length(1)}).strict();
export const sendInput=z.object({message,configuration:z.object({blocking:z.boolean().optional(),acceptedOutputModes:z.array(z.literal('application/json')).optional(),historyLength:z.number().int().min(0).optional()}).strict().optional()}).strict();
export function taskView(s:State,p:Principal,t:AgentTask){if(t.subject!==p.subject)fail(404,'Task not found');let state=t.state;let result=t.result;let timestamp=t.updatedAt??t.createdAt;if(t.proposalId){const a=getProposal(s,p,t.proposalId);if(a.status==='executed'){state='completed';result=publicProposal(a);timestamp=a.executedAt??a.approvedAt??timestamp;}else if(a.status==='rejected'){state='canceled';timestamp=a.approvedAt??timestamp;}else if(a.expiresAt<=new Date().toISOString()){state='failed';timestamp=a.expiresAt;}}
 return {id:t.id,contextId:t.contextId,status:{state:'TASK_STATE_'+state.replace('-','_').toUpperCase(),timestamp},artifacts:[{artifactId:t.id+'-result',parts:[{data:result,mediaType:'application/json'}]}]};}
export function sendTask(s:State,p:Principal,raw:unknown,now:string):{state:State;task:AgentTask}{const parsed=sendInput.safeParse(raw);if(!parsed.success)fail(400,'SendMessage は ROLE_USER と一つの data part（name, args）が必要です。');const msg=parsed.data.message;const request=canonical(raw);const old=data(s).agentTasks.find(t=>t.subject===p.subject&&(t.messageId===msg.messageId||t.messages?.some(m=>m.id===msg.messageId)));if(old){if((old.messages?.find(m=>m.id===msg.messageId)?.request??old.request)!==request)fail(409,'同じ messageId を別の内容に再利用できません。');return {state:s,task:old};}
 const payload=msg.parts[0].data;const args=parseInput(payload.name,payload.args);permit(p,payload.name);
 let next=structuredClone(s);next.integration=data(next);let task:AgentTask;
 if(msg.taskId){const prev=next.integration.agentTasks.find(t=>t.id===msg.taskId&&t.subject===p.subject);if(!prev)fail(404,'Task not found');if(msg.contextId&&prev.contextId!==msg.contextId)fail(400,'contextId mismatch');if(prev.state!=='input-required'||payload.name!=='execute_approved'||args.proposalId!==prev.proposalId)fail(409,'このタスクは承認済み内容の再開のみ可能です。');next=commitApproved(next,p,String(args.proposalId),now);task={...prev,messageId:msg.messageId,request,messages:[...(prev.messages??[{id:prev.messageId,request:prev.request}]),{id:msg.messageId,request}],state:'completed',updatedAt:now,result:publicProposal(getProposal(next,p,String(args.proposalId)))};const index=data(next).agentTasks.findIndex(t=>t.id===task.id);data(next).agentTasks[index]=task;return {state:next,task};}
 if(msg.contextId&&!next.integration.agentTasks.some(t=>t.contextId===msg.contextId&&t.subject===p.subject))fail(404,'Context not found');
 const id=crypto.randomUUID();const contextId=msg.contextId??crypto.randomUUID();let result:unknown;let proposalId:string|undefined;
 if(payload.name.startsWith('prepare_')){proposalId='proposal-'+id;next=prepare(next,p,payload.name,args,proposalId,now);result=publicProposal(getProposal(next,p,proposalId));}
 else if(payload.name==='execute_approved'){next=commitApproved(next,p,String(args.proposalId),now);result=publicProposal(getProposal(next,p,String(args.proposalId)));if(next.version===s.version)next={...next,version:s.version+1};}
 else {result=readAction(next,p,payload.name,args,now);next.version++;}
 task={id,subject:p.subject,contextId,messageId:msg.messageId,request,messages:[{id:msg.messageId,request}],state:proposalId?'input-required':'completed',proposalId,result,createdAt:now};next.integration=data(next);next.integration.agentTasks.push(task);return {state:next,task};
}
export function cancelTask(s:State,p:Principal,id:string,now:string){const next=structuredClone(s);const t=data(next).agentTasks.find(t=>t.id===id&&t.subject===p.subject);if(!t)fail(404,'Task not found');if(t.state==='canceled')return next;if(t.state!=='input-required')fail(409,'Task not cancelable');if(t.proposalId){const a=getProposal(next,p,t.proposalId);if(a.status!=='pending')fail(409,'Task not cancelable');a.status='rejected';}t.state='canceled';t.updatedAt=now;next.version++;return next;}
export const a2aTools=tools;
