import document from './contracts/demand.json';
import * as validators from './contracts/validators.mjs';
import {State,Principal,tripRecords,ownReservations,stops,passengerType,serviceId,getProposal,canonical,fail} from './core';
import {inputDate} from '../model';
type Json=Record<string,any>;
export const demandDocument=document as Json;
export function validateContract(operation:string,phase:string,value:unknown){const key=`demand_${operation}_${phase}`;const fn=(validators as Record<string,(v:unknown)=>boolean>)[key];if(!fn||!fn(value))fail(phase==='request'?400:503,phase==='request'?'標準仕様の入力項目・型・必須条件を確認してください。':'応答が標準仕様を満たさないため、結果を返しません。');}
export function candidate(s:State,tripId:string,count:number){const t=tripRecords(s).find(t=>t.id===tripId);if(!t)fail(404,'便が見つかりません。');const location=(i:number)=>({type:'Point',coordinates:[stops[i].lon,stops[i].lat]});return {reservation_request:{candidate_id:`${t.id}:${count}`,service_id:serviceId,pickup:{type:'fixed_stop',stop_id:stops[0].id,location:location(0),datetime:t.start},dropoff:{type:'fixed_stop',stop_id:stops[1].id,location:location(1),datetime:t.end},passenger_count:[{passenger_type_id:passengerType,count}],accessibility_feature_count:[],vehicle_id:t.vehicleId},display:{pickup:{display_name:stops[0].name},dropoff:{display_name:stops[1].name},fare:{per_passenger_type:[{passenger_type_id:passengerType,subtotal:0}],total:0},vehicle:{id:t.vehicleId,name:'e-Palette',capacity:{seats:s.bookings.find(b=>b.id===t.id)!.seats,accessibility_features:[]}}}};}
export function standardReservation(s:State,p:Principal,id:string){const r=ownReservations(s,p).find(r=>r.ticketId===id);if(!r)fail(404,'予約が見つかりません。');const c=candidate(s,r.tripId,r.count);const status=({reserved:'confirmed',boarded:'in_transit',alighted:'completed',cancelled:'cancelled'} as Record<string,string>)[r.status];if(!status)fail(503,'予約状態を確認できません。');return {id:r.ticketId,passenger_id:p.subject,status,service_id:serviceId,pickup:{...c.reservation_request.pickup,...c.display.pickup},dropoff:{...c.reservation_request.dropoff,...c.display.dropoff},passenger_count:c.reservation_request.passenger_count,accessibility_feature_count:[],fare:c.display.fare,vehicle:c.display.vehicle,created_at:r.createdAt};}
export function candidateQuery(body:Json){validateContract('postReservationsCandidates','request',body);if(body.service_ids.length!==1||body.service_ids[0]!==serviceId||body.preferred_time.type!=='pickup'||body.pickup.type!=='fixed_stop'||body.dropoff.type!=='fixed_stop'||body.passenger_count.length!==1||body.passenger_count[0].passenger_type_id!==passengerType||body.accessibility_feature_count.length)fail(422,'検証対象は、指定乗降点・乗車時刻指定・一般区分・補助設備指定なしです。未設定の条件は予約できません。');return {date:inputDate(body.preferred_time.datetime).slice(0,10),fromStop:body.pickup.stop_id,toStop:body.dropoff.stop_id,count:body.passenger_count[0].count,wheelchairs:0};}
export function standardWrite(s:State,p:Principal,operation:string,body:Json,proposalId:string,reservationId?:string){validateContract(operation,'request',body);if(body.passenger_id!==p.subject)fail(403,'本人の予約のみ変更できます。');const a=getProposal(s,p,proposalId);let expected:unknown;
 if(operation==='postReservations'){if(a.action!=='prepare_ride_booking')fail(403,'乗車予約の承認が必要です。');expected={...candidate(s,String(a.args.tripId),Number(a.args.count)).reservation_request,passenger_id:p.subject};}
 else {if(a.action!=='prepare_ride_cancellation'||a.args.reservationId!==reservationId)fail(403,'対象予約の取消承認が必要です。');const r=standardReservation(s,p,String(reservationId));expected={passenger_id:r.passenger_id,status:'cancelled',service_id:r.service_id,pickup:r.pickup,dropoff:r.dropoff,passenger_count:r.passenger_count,accessibility_feature_count:r.accessibility_feature_count,...(body.vehicle?{vehicle:r.vehicle}:{})};}
 if(canonical(expected)!==canonical(body))fail(403,'乗降場所・日時・人数・車両が確認した内容と一致しません。');return a;
}
export function standardList(s:State,p:Principal,query:URLSearchParams){const allowed=['pickup_date_from','pickup_date_to','reservation_ids','status','offset','limit'];for(const key of query.keys())if(!allowed.includes(key))fail(400,'未定義の検索条件です。');const offset=Number(query.get('offset')??0),limit=Number(query.get('limit')??20);if(!Number.isInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1||limit>100)fail(400,'offset/limit を確認してください。');const from=query.get('pickup_date_from'),to=query.get('pickup_date_to');if((from&&!/^\d{4}-\d{2}-\d{2}$/.test(from))||(to&&!/^\d{4}-\d{2}-\d{2}$/.test(to))||(from&&to&&from>to))fail(400,'日付範囲を確認してください。');const statuses=query.get('status')?.split(',');if(statuses?.some(v=>!['tentative','confirmed','no_show','in_transit','completed','cancelled'].includes(v)))fail(400,'予約状態を確認してください。');const ids=query.get('reservation_ids')?.split(',');const items=ownReservations(s,p).map(r=>standardReservation(s,p,r.ticketId)).filter(r=>(!statuses||statuses.includes(r.status))&&(!ids||ids.includes(r.id))&&(!from||inputDate(r.pickup.datetime).slice(0,10)>=from)&&(!to||inputDate(r.pickup.datetime).slice(0,10)<=to));return {reservations:items.slice(offset,offset+limit),total:items.length,offset,limit};}
export const implementedOperations=['postReservationsCandidates','postReservations','putReservationsId','getPassengersIdReservations'];
